### ISSUE TITLE
Can not install Indy-node 

### ISSUE THREAD

**Issue by shubhamm033** [hyperledger/indy-sdk#1044]
Hi, I am a newbie in this field and cant set up indy-node on my ubuntu 16.04. Could someone provide step by step guideline to set up the indy-node?

**Comment by dklesev** [comment]
https://github.com/hyperledger/indy-sdk/blob/master/README.md#how-to-start-local-nodes-pool-with-docker

**Comment by vsudip** [comment]
@dklesev This generates the genesis transaction file in docker instance. Now to get the handle for the pool genesis file is required from indy-sdk api (indy-sdk api is invoked outside of docker container). How can I get hold of genesis transaction ? Or is there anyother way to get handle of pool ledger ?

pool_config = json.dumps({'genesis_txn': genesis_file_path})
pool.create_pool_ledger_config(config_name=pool_name, config=pool_config)
pool_handle = await pool.open_pool_ledger(config_name=pool_name, config=None)

Thanks!

**Comment by vsudip** [comment]
I haven't faced above error, can you check if above url is accessible and there is no proxy set on your network.
