### ISSUE TITLE
Credential Definition Bugs

### ISSUE THREAD

**Issue by arra1997** [hyperledger/indy-sdk#1072]
I try to build a get credential definition request using the documented API (with a DID and credential def ID, the latter of which is a string that comes from issuing a credential definition based on an existing schema), but the API throws a CommonInvalidStructure error. I am using the Nodejs wrapper (v.1.6.1 ) for LibIndy (v1.6). Could someone look into this?

**Comment by lodo1995** [comment]
Can you post your code here? Both the one to create the credential definition and the one to create the get credential definition request?

**Comment by arra1997** [comment]
Prior to this I created a schema, published it to the chain and was able to retrieve it. Then
To create a credential definition:
1)  credential_def = await indy.issuerCreateAndStoreCredentialDef(wallet_handle, verinym['did'], schema_info,'TAG', 'CL', '{"support_revocation": false}')
where verinym['did'] is the DID associated with my identity, and schema_info is the second element that comes from issuerCreateSchema()
which successfully creates a credential_definition (with is a 2-tuple (credential_def_id, credential_def_json))

2) Using this credential def, I create a request
let credential_def_request = await indy.buildCredDefRequest(verinym['did'], credential_def[1])
which works well

3) Set credential_def_request['operation']['ref'] to 1 (by default it was 0) to stop the node network from complaining when I publish the request in step 4. I didn't find any method to set this "ref" value nor any documentation about what it means, so this might be a separate bug you want to look into

4) Publish credential def by signing and submitting request
let cred_def_res = await indy.signAndSubmitRequest(pool_handle, wallet_handle, verinym['did'], credential_def_request)
which also works

5) Build get credential def request (which fails)
let get_cred_def_request =  await indy.buildGetCredDefRequest(verinym['did'], credential_def[0])
where credential_def[0] as explained in step 1 contains the credential_def_id

which fails with a CommonInvalidStructure IndyError.

**Comment by burdettadam** [comment]
We are using Jira to track issues now, please use this [Jira IS-979 ticket](https://jira.hyperledger.org/browse/IS-979) for any further discussion.
