### ISSUE TITLE
cached libraries don't update on new versions

### ISSUE THREAD

**Issue by Alexis-Falquier** [hyperledger/indy-sdk#1080]
I was having a problem where the updated API meant the python methods were changed (i.e. create_wallet taking two parameters rather than five) when the update was pushed I was having trouble running my code as the cached library in `/home/user/.local/lib/python3.5/site-packages/indy/` was not updated and was still trying to run the deprecated wrapper.

**I fixed my issue by copying the updated wrapper into the cached folder.** 

I am assuming at some point in the installation of the sdk, or in running the python code the cached folder was created, so it might be worth looking into a way to check that this cached folder is either not created or is updated when needed.

**Comment by burdettadam** [comment]
We are using Jira to track issues now, please use this [Jira IS-977 ticket](https://jira.hyperledger.org/browse/IS-977) for any further discussion.
