### ISSUE TITLE
Timeout error when trying the NodeJS How To's

### ISSUE THREAD

**Issue by AnissaSchirock** [hyperledger/indy-sdk#1084]
Hello,

Im trying to create an indy project in NodeJS and started with the how to's, but I can a PoolLedgerTimeout every time I try to send something to the Sovrin test network.

I tried the fix I found on the sovrin forum (https://forum.sovrin.org/t/indyerror-poolledgertimeout-when-connecting-to-sovrin-sandbox-network/820/4) but unfortunately, this doesn't fix my problem. 
I tried it with a NYM and a claim.

**Comment by burdettadam** [comment]
We are using Jira to track issues now, please use this [Jira IS-976 ticket](https://jira.hyperledger.org/browse/IS-976) for any further discussion.
