### ISSUE TITLE
React-Native support

### ISSUE THREAD

**Issue by TorstenRegemortel** [hyperledger/indy-sdk#1085]
I'm trying to create a mobile application for android and ios using react-native. I wanted to use the node.js sdk but it needs C++ and python 2. I also looked at the android and IOS sdk but using the android sdk doesn't look like the best option.

Any ideas on how to get started?

**Comment by lodo1995** [comment]
My team managed to have libindy work on React Native (both iOS and, partially, Android) some time ago. At that time, official support for Android was not there, so we had to do some magic to cross-compile libindy from source. Nowadays, I think you can just use the official build instructions to build libindy for Android. The official iOS wrapper, on the other hand, was already working, more or less.

Coming to the hard part, you have to write the bindings from Android/iOS native code to React-Native yourself. I won't cover this here, as it is well explained in the official React-Native docs (for both [Android](https://facebook.github.io/react-native/docs/native-modules-android) and [iOS](https://facebook.github.io/react-native/docs/native-modules-ios.html)), but basically you have to write some Java and Objective-C/Swift code, respectively, to bridge the gap between the native libindy and the interpreted React-Native code. This means that you will have to eject from CRNA and manage the folder structure and build process by yourself.

**Comment by burdettadam** [comment]
We are using Jira to track issues now, please use this [Jira IS-975 ticket](https://jira.hyperledger.org/browse/IS-975) for any further discussion.
