### ISSUE TITLE
ErrorCode.LedgerInvalidTransaction

### ISSUE THREAD

**Issue by ghost** [hyperledger/indy-sdk#1092]
Using python version:
Getting error while calling `parse_get_cred_def_response` 
```
_indy_loop_callback: Function returned error 304
Error occurred: ErrorCode.LedgerInvalidTransaction

```
**As `submit_request`  response data is null**
`{"result":{"signature_type":"CL","data":null,"type":"108","tag":"governID","state_proof":{"root_hash":"CAHa6F79nfRe2quf4qdqhNEQj4T2gzFDfJp1yoJr48vq","multi_signature":{"participants":["Node4","Node2","Node3"],"signature":"QnXzhzzMKeeCtLR5mQ7t13svBMRfFGygzuoH2dxpHpWrDp8you6KyR2aDzWfQ1YdttfN7QshsCgaXi5g1U9MiDfJmtWwSAekD816waf9EG94eni7BjD8pjChzU9a86Dd2xe4mFYDssKqc21wVrSwMYBkMyzo6xfnNiSZiWL59Yvjwd","value":{"timestamp":1535264361,"pool_state_root_hash":"ADNBz2dUcSd2GdKUtEGw2aQCjtqhcQFz1W5DYKYzvcxY","state_root_hash":"CAHa6F79nfRe2quf4qdqhNEQj4T2gzFDfJp1yoJr48vq","txn_root_hash":"8rMnx84d2Yvkn3f5H72qBY9GTrrRfeNgqJSdPmQPMc2K","ledger_id":1}},"proof_nodes":"+QMo+QERgKAVnj5\/XkTxOz43QLLk7E6SFXQHhviEX5KInw+mqOvypYCAoA2polmma2ST4q\/fsdznOQejkiWoQu64RQX6xcEgVNbTgICAoElXgAjEgDE2OdTvAsIJseMFAaZzzzbOwAf+NoL7flp+oJV5rbFmUQXVZCUwGyRvGOGUlca1vnw\/C6DRlRJPCOqkoLn5igdCRqOvhYpMpC48FCAdCj5YUlhh0fdxiST9EMADoLTBbsJMJR3t8PJvvJyUQTg99A4gqU2Q3IrSBY+jw42roN\/JlMuMa7n6grRe0aDY9QMaVIuEEpSpIaB7CPU5kjTXoILlJ70EBwvft2SHy92Y1iUCsIhh3HYdlh\/xBAk9QiE2gICA+QIRoFibhi6jRo8dsZobdlznDutQqRlPfXF39zqwPjNQiZIZoBlOzJ45WMO9Qo3zODUhI3HANJnrHctZevXR2VuCGO1eoOzh42r38ZiUqLYOgWGupOLqIbNyU3gv7eORbx8zjmBtoIB9QGjXNBJ8P+C9qTbLdPLhgEYlWeZLGIm7yTnu3lxdoCy6AKgXblZdsFHZQh2Psjfivbnuw+Gq6\/B63csz\/w0noFqJA3JwS\/u0bor7MlB8rnLXE8t19NrojAzl6bMCzb4CoLRXRhp4kFp0L+expHeFnZvEkP8w5OgC\/ukSDxyiblHqoPpiBDtA\/6LkofctroljhbH6EodH75zPQOnox1L8yc6QoMZs+4nKOlIuaYlCAZf+zpqBEOoxicwGvmVjsvvYTEtvoLXq1g\/XeYArX9QFdcIpvIp1G8LTPNclRFwogIDMMIaToBXyafzdRyAdNLsyjAPZFsxVA0RF7rKe\/k4g9xv5FhiMoNiH7vqLyyPn0VcWZmIk72o0iVS3dDYdJdw0AaPGoZUAoMU6aJpkrM\/ipERSv5Pk5Cbjepn3oXkAl2bF8ChZ99F0oFsogBtno4zi56NTSydHl9R+LSM\/tqE01JXawKtjve+FoJiIi\/glRQG6F+SwGjSh+MR+gpaFyQYfExYxkWlFM\/kUoFXrn7dfL45kCYFBNWBsOvz4\/bQy\/NnD0A1bCuw5R9QygA=="},"origin":"VspCEZTw1wnvSybou1TKB4","ref":1,"seqNo":null,"identifier":"Th7MpTaRZVRYnPiabds81Y","reqId":1535264371385593370,"txnTime":null},"op":"REPLY"}`

**Comment by vimmerru** [comment]
Yes, for now transaction parsers return LedgerInvalidTransaction when there is no corresponded data on the ledger. We plan to change it in the next sprints.

**Comment by vimmerru** [comment]
See https://jira.hyperledger.org/browse/IS-932

**Comment by burdettadam** [comment]
We are using Jira to track issues now, please use this [Jira IS-974 ticket](https://jira.hyperledger.org/browse/IS-974) for any further discussion.
