### ISSUE TITLE
Known High Severity Security Vulnerability in 'marked'

### ISSUE THREAD

**Issue by tijohnson** [hyperledger/indy-sdk#1117]
A GitHub security scan identified the following issue:

We found a potential security vulnerability in a repository for which you have been granted security alert access.

hyperledger/indy-sdk

Known high severity security vulnerability detected in marked <0.3.9 defined in: https://github.com/hyperledger/indy-sdk/blob/master/vcx/wrappers/node/package-lock.json

package-lock.json update suggested: marked ~> 0.3.9.

These issues were also found:

Known moderate severity security vulnerability detected in marked < 0.3.9 defined in package-lock.json. 
Known moderate severity security vulnerability detected in marked < 0.3.7 defined in package-lock.json.

**Comment by burdettadam** [comment]
We are using Jira to track issues now, please use this [Jira IS-972 ticket](https://jira.hyperledger.org/browse/IS-972) for any further discussion.
