### ISSUE TITLE
Known Low Severity Security Vulnerability in 'debug'

### ISSUE THREAD

**Issue by tijohnson** [hyperledger/indy-sdk#1118]
The GitHub security scan found the following issue:
We found a potential security vulnerability in a repository for which you have been granted security alert access.
hyperledger/indy-sdk

Known  low severity security vulnerability detected in debug < 2.6.9 defined in: https://github.com/hyperledger/indy-sdk/blob/master/vcx/wrappers/node/package-lock.json

package-lock.json update suggested: debug ~> 2.6.9.

**Comment by burdettadam** [comment]
We are using Jira to track issues now, please use this [Jira IS-971 ticket](https://jira.hyperledger.org/browse/IS-971) for any further discussion.
