### ISSUE TITLE
Known High Severity Security Vulnerability in 'lodash'

### ISSUE THREAD

**Issue by tijohnson** [hyperledger/indy-sdk#1119]
The GitHub security has found the following issue:
We found a potential security vulnerability in a repository for which you have been granted security alert access in hyperledeger/indy-sdk

Known  high severity security vulnerability detected in lodash <4.17.5 defined in: https://github.com/hyperledger/indy-sdk/blob/master/vcx/wrappers/node/package-lock.json

package-lock.json update suggested: lodash ~> 4.17.5.

**Comment by burdettadam** [comment]
We are using Jira to track issues now, please use this [Jira IS-970 ticket](https://jira.hyperledger.org/browse/IS-970) for any further discussion.
