### ISSUE TITLE
libvcx: protocol version hardcoded

### ISSUE THREAD

**Issue by phillipgibb** [hyperledger/indy-sdk#1135]
The Protocol version is hardcoded to 2
`match Pool::set_protocol_version(2)`
This means that you cannot connect to the Sovrin testnetwork which is version 1.
If you want to use VCX you have to be connected to the STN.
So this version should be defaulted to 1 and be possible to change based on the vcx config.

**Comment by phillipgibb** [comment]
added pull request https://github.com/hyperledger/indy-sdk/pull/1138
regarding this

**Comment by burdettadam** [comment]
We are using Jira to track issues now, please use this [Jira IS-965 ticket](https://jira.hyperledger.org/browse/IS-965) for any further discussion.
