### ISSUE TITLE
bump rust openssl version to 0.10.x

### ISSUE THREAD

**Issue by AxelNennker** [hyperledger/indy-sdk#1139]
Currently rust openssl is fixed to version 0.9.24 but the latest version is 0.10.11
https://github.com/AxelNennker/indy-sdk/blob/master/libindy/Cargo.toml#L57

Also consider using feature vendored at least for cross-compilation.
Current openssl version 1.1.1 which has improvements to make compiling for Android simpler and rust openssl uses openssl version 1.1.1.
https://github.com/openssl/openssl/blob/master/NOTES.ANDROID

So bumping rust openssl probably helps compiling for Android.

**Comment by AxelNennker** [comment]
https://github.com/hyperledger/indy-sdk/pull/1142

**Comment by burdettadam** [comment]
We are using Jira to track issues now, please use this [Jira IS-962 ticket](https://jira.hyperledger.org/browse/IS-962) for any further discussion.
