### ISSUE TITLE
Installing libvcx on ubuntu

### ISSUE THREAD

**Issue by andrewBSTan** [hyperledger/indy-sdk#1145]
I was following the steps in https://github.com/hyperledger/indy-sdk/tree/master/vcx to create the VCX debian package and subsequently installing on the environment via gdebi but have gotten that there's a missing dependency.
![image](https://user-images.githubusercontent.com/37392630/45662722-973fc600-bb35-11e8-806f-776e5d181a16.png)

How can this be resolved?
Also, on https://github.com/hyperledger/indy-sdk/tree/master/vcx under section "Debians and Artifacts", what are the provision scripts mentioned in that section?  A bit confused on that section as it mentioned not only the deb but other files which I do not see them in the output folder as well.

Assistance on the above much appreciated.

**Comment by burdettadam** [comment]
We are using Jira to track issues now, please use this [Jira IS-958 ticket](https://jira.hyperledger.org/browse/IS-958) for any further discussion.
