### ISSUE TITLE
indy_register_wallet_type callbacks

### ISSUE THREAD

**Issue by skibz** [hyperledger/indy-sdk#182]
the callback function signatures for the arguments to `indy_register_wallet_type` are not consistent with the rest of libindy.

was this intentional? if so, what is the reasoning behind this decision?

i was expecting to see callback functions with signatures like:
```c
void (*some_callback)(indy_handle_t handle, indy_error_t error, char* another_param);
```

which would allow for the passing of the error value to a caller.

**Comment by jovfer** [comment]
> i was expecting to see callback functions with signatures like:
> `void (*some_callback)(indy_handle_t handle, indy_error_t error, char* another_param);`

This signature is used for callbacks to async return result of some API call.

But in case of `indy_register_wallet_type` some callbacks (except the last one) will be used by library for internal purposes, not as direct reaction on API call. So it should not include `indy_handle_t` or `indy_error_t` parameters.

**Comment by skibz** [comment]
perfect, thanks @jovfer
