### ISSUE TITLE
Links Broken in CLI Readme

### ISSUE THREAD

**Issue by mwbenedi** [hyperledger/indy-sdk#2168]
I noticed that the links for the MacOS CLI and indy-sdk are broken in the readme. Can you please update these? Thanks.

https://github.com/hyperledger/indy-sdk/blob/master/cli/README.md

**Comment by ryjones** [comment]
@mwbenedi if you replace the `release channel` with the one you want, it looks like they're all there.

https://repo.sovrin.org/macos/indy-cli/ shows:
```master/                                            08-May-2020 18:00                   -
rc/                                                25-Mar-2020 17:58                   -
stable/                                            26-Mar-2020 13:33                   -
stable-test/                                       02-Sep-2019 12:47                   -
test/                                              02-Sep-2019 12:47                   -
```
for instance.
