### ISSUE TITLE
location of crypto function call

### ISSUE THREAD

**Issue by chaosma** [hyperledger/indy-sdk#2173]
I tried to find the actual implementations of crypto functions, such as the ones defined in libindy/include/indy_anoncreds.h

I suppose they are defined in indy.dll.

Anyone knows where are the actual implementations? Are they open-sourced? Thanks!

**Comment by dhh1128** [comment]
@chaosma: I believe the implementations are all in Hyperledger Ursa, unless they come from libsodium primitives. You can check them out at https://github.com/hyperledger/ursa.

**Comment by chaosma** [comment]
@dhh1128  Thanks! I found the location, they are in ursa as well as part of indy-sdk.
