### ISSUE TITLE
Provide the way to configure logging on C API level

### ISSUE THREAD

**Issue by vimmerru** [hyperledger/indy-sdk#22]
Currently, libsovrin uses popular https://github.com/rust-lang-nursery/log facade. It allows linking with logger implementation in runtime.

We use env_logger that allows logging configuration by environment variables for our tests, but there is no logger initialization provided on C API level. I suggest the following:

1. Call env_logger init method during initialization of CommandExecutor singleton
2. Provide API that will allow registering custom callbacks for the logger. It will allow re-using same logging infrastructure as the main application that uses libsovrin.

Point 2 can be postponed.

**Comment by dhh1128** [comment]
I am happy with this approach.

**Comment by peacekeeper** [comment]
Sounds good.

**Comment by vimmerru** [comment]
> Call env_logger init method during initialization of CommandExecutor singleton

It is already merged. 

Currently, the library activates trace by default at info level for all modules.
This behavior can be changed by setting environment variable `RUST_LOG`.
```RUST_LOG=<common_log_level>
RUST_LOG=<module>=<log_level>[,<module>=<log_level>]*
```
E.g. `RUST_LOG=sovrin=trace,zmq=debug` (edited)

**Comment by lodo1995** [comment]
@vimmerru is there any progress on point 2? I would really like to be able to intercept log calls of libindy and handle them in a custom way.

**Comment by jovfer** [comment]
https://jira.hyperledger.org/browse/IS-2
