### ISSUE TITLE
LibVCX state machines update make too strong assumptions

### ISSUE THREAD

**Issue by Patrik-Stas** [hyperledger/indy-sdk#2211]
There's this common pattern across libvcx objects (credential/proof) where upon creation, or on next expected step after creation, the user passes in connection handle. Let's take issuer's side of credential for instance.

1. Credential instance is created by `vcx_issuer_create_credential` - all good so far. Creates state machine in `IssuerState::Initial` state.
2. The next expected step is to call `vcx_issuer_send_credential_offer` which takes `credential_handle` and `connection_handle` as parameters. It moves state from `IssuerState::Initial` to `IssuerState::OfferSent` and embeds provided `connection_handle` into the state machine. It's responsibility of the caller to provide correct `connection_handle`.
3. Now the issuer should call `vcx_issuer_credential_update_state` or `vcx_issuer_credential_update_state_with_message`. This tries to move state machine from `IssuerState::OfferSent` to `IssuerState::Finished` and in the process of doing so, it uses `connection_handle` provided from the step `2`. 

The problem here is that IssuerCredential statemachine (and others too) assume that the connection handle reference they keep within their state machine will be valid on the next call, but that assumption can be broken easily if you:
Run step `1`, `2`, serialize `IssuerCredential`, kill process, run new process, load up and deserialize the `IssuerCredential` instance. Next `updateState()` will fail because the state machine refers to connection handle which is not valid anymore.

This is a bit hairy example, but the same thing can easily happen in distributed environment when steps `1`, `2` happens on process `A` and `3` happens in process `B`, both reading/writing serialized vcx objects from/to shared storage.

### Solution proposal 1
For sake of avoiding breaking changes, add methods (specific method naming can be discussed):
- `vcx_issuer_credential_update_state_safely` 
- `vcx_issuer_credential_update_state_with_message_safely`
which should take extra parameters of `connection_handle` so no assumptions on memory state would be made.

So for example:
```
pub extern fn vcx_issuer_credential_update_state(command_handle: CommandHandle,
                                                 credential_handle: u32,
                                                 cb: Option<extern fn(xcommand_handle: CommandHandle, err: u32, state: u32)>) -> u32 {
```
would have safe alternative
```
pub extern fn vcx_issuer_credential_update_state_safely(command_handle: CommandHandle,
                                                 credential_handle: u32,
                                                 connection_handle: u32,
                                                 cb: Option<extern fn(xcommand_handle: CommandHandle, err: u32, state: u32)>) -> u32 {
```
which would use provided handle, instead the one stored in SM `IssuerSM.state.OfferSent(OfferSentState).connection_handle`

### Alternative proposal 2
The proposal number 1 would mean adding quite a few methods on API level as well as internally. Possible solution requiring less changes would be something like `vcx_*_update_connection_handle` and so caller would be responsible to call this method after doing vcx object deserialization and passing correct connection handle.

@Artemkaaas @jovfer @ryMarsh44 what do you think? Is this valid concern or am I possibly missing something? 

Props to @airoasis for pointing this out!

**Comment by airoasis** [comment]
Here is a temporary workaround for this issue

**Comment by Artemkaaas** [comment]
Thanks, Patrik
We also came across this problem recently.  

In Evernym fork we did breaking change by the embedding of the whole required connection-related data into Issuance / Presentation state machines. I think it's the most proper way, but it makes `not completed` state machines broken but keep API and steps the same. 
We did that breaking change because there are no production uses for `aries` protocols yet for Evernym products and we consider VCX `aries` protocols as `in progress`. 

There is also the option of using indy Wallet to persist connection information by corresponding thread id. But that case we need to care about freeing data on completion and releasing. And as far LibVcx doesn't manage the persistence of the state machine we declined that option to be relevant with the flow.

Describing your options: 
1) In that case, we need to deprecate the existing `update_state` methods and force users to migrate to a new one. That actually almost equals to doing breaking change now. 
2) The flow getting more complex and unclear.

**Comment by Patrik-Stas** [comment]
@Artemkaaas thanks for feedback!

I am not sure if I like the idea of embedding all connection data (probably a DDO?) into credential/proof state machines (do I get it right?) I think this must conflate them a lot, turning them inbto quite deep data structure..? Also connection can change within its life time, the parties might rotate keys, change endpoints (although this is not in VCX yet and I am not sure if there's even RFCs for this, I presume some "pairwise connection update" protocols will exists). So if connection might change, it could be cumbersome to keep track which objects needs to have their embedded information updated.

I agree the proposal `2` would be error prone and developer unfriendly, but wouldn't require of deprecation of `update_state`. Instead, it would be **strongly recommended** to adjust existing code and always update connection handle before calling `update_state`.

I'd prefer the proposal `1` from my first the most. The connection can have its own lifetime and be injected to other objects on demand whenever needed. Also it can be implemented as nonbreaking change by adding methods. And I agree that the current `update_state` should be deprecated, but seem to me like it would be done so for a good reason.

**Comment by Artemkaaas** [comment]
I agree that option 1 (passing connection_handle to every depending function) is the most proper way. I'm only concerned about new APIs.

**Comment by Patrik-Stas** [comment]
Do you think it can't be implemented without doing breaking changes? I think there can be several ways of implementing that with varying amount of breaking changes. Correct me if I am missing something, I think completely non-breaking without be:

- As proposed, addition of following methods:
```
vcx_*_update_state_safely
```
everything can stay as is. Calling the currently existing methods `vcx_*_update_state`, it will use the cached `connection_handle`, everything stays as is. However, if user calls `vcx_*_update_state_safely`, it will do extra "preparation step"
1. Update `connection_handle` record in the state machine
2. Proceed same way as `vcx_*_update_state` did before.

**Comment by KitHat** [comment]
@Patrik-Stas 
I have read your proposal and discussion with @Artemkaaas 
It is a good change to make connection handle updatable in the connection but the implementation does not seem correct to me.
I am voting for the option 1 (make a new call) but with a slight tweak.
LibVCX API is not really convenient for development purposes. I suggest to start making a API v2 and the first change would be to introduce a connection handle to `*_update_state` functions.
We will mark this API as experimental so if we will feel that we made a mistake we will just break it. When we will feel that it is a good API that is comfortable to use we will deprecate the old calls and make the new API stable. However, due to SemVer we will not be able to drop the old API until we release a new major release (this should be contacted with Hyperledger)

**Comment by Patrik-Stas** [comment]
@KitHat 
Yeah I think have experimental V2 API can be alright, it would be nice to have an API with only 1, clear, proper way of updating state machines. Since you say
> LibVCX API is not really convenient for development purposes.
- Do you have other changes in mind you would consider introducing with V2 API?

- 2nd question - do you oppose extending current API layer with update methods taking additional parameter?

**Comment by KitHat** [comment]
@Patrik-Stas

> Do you have other changes in mind you would consider introducing with V2 API?

Not yet. But I think we need to form all flows into a more homogenous style -- they should have the same naming convention and not to have some helpers that allow to do switch machines without some params.

> 2nd question - do you oppose extending current API layer with update methods taking additional parameter?

I personally do not like the naming. `_safely` suffix does not tell you anything about the difference between this function and I had hard time to express it in the function name. So I thought that the old way of updating is erroneous and we should just deprecate it.

**Comment by Patrik-Stas** [comment]
@KitHat 
> I personally do not like the naming. _safely suffix does not tell you anything about the difference between this function and I had hard time to express it in the function name. So I thought that the old way of updating is erroneous and we should just deprecate it.

Yeah the `_safely` suffix was just first thing that came up in my mind to illustrate my point. Rather the question is/was whether you'd be okay with adding alternative version of `vcx_*_update_state` with additional connection parameter to current VCX API, rather than to V2 API. Naming can be different. Maybe simply `vcx_*_update_state_v2`? Trying to be "descriptive" names like `vcx_*_update_state_safely` or something like `vcx_*_update_state_using_connection` is getting quite long and only arguably accurate.

**Comment by KitHat** [comment]
I think that `vcx_v2_*_update_state` would be the best variant. Also I would consider changing names of entities we operate with -- some of them are really misleading, like `disclosed_proof`

**Comment by Patrik-Stas** [comment]
@KitHat 
Cool! Just to make sure we are on the same page - so do you agree on:
- not yet adding new, full blown, V2 experimental API layer, 
- but rather extending current LibVCX API addition of methods named `vcx_v2_*_update_state` alongside existing `vcx_*_update_state`?

**Comment by KitHat** [comment]
@Patrik-Stas 
Yes, but I would suggest to create a separate directory in `api` of libvcx
