### ISSUE TITLE
Native IOS wrappers

### ISSUE THREAD

**Issue by Alexis-Falquier** [hyperledger/indy-sdk#2213]
I was wondering what happened to the native IOS wrappers? Are they being maintained somewhere? https://jenkins.hyperledger.org/ is not available anymore and the last build on https://repo.sovrin.org/ios/libindy/master/indy-objc/ is two years old.

**Comment by ardzarana** [comment]
I am having the same issue, testflight won't let me upload my app because wrappers are compiled for an unsupported iOS version, needs to be iOS 12.1 or greater. I am trying to compile the Indy SDK in Xcode 13, however most scripts have issues and I require many external libraries / sources.  Its a rather large development environment to setup.

**Comment by pabloromeu** [comment]
Trying to build them it looks for some methods not available at Libindy... I think nobody is maintaining that...

**Comment by lalc** [comment]
Was there any progress on this issue? We are hitting the same issue and trying to build it ourselves now and wondering if someone has maintained this.

**Comment by rebink** [comment]
After a long trial and error session, I was able to run the project. Follow the below steps, hope it will help.

 1. Add below pods to podfile
` 
pod 'libindy'
pod 'libsodium'
pod 'libzmq'
pod 'GRKOpenSSLFramework'
pod 'CoreBitcoin', :podspec => 'https://raw.github.com/oleganza/CoreBitcoin/master/CoreBitcoin.podspec'
`

2. Drag and drop the "Indy" folder(indy-sdk-master/wrappers/ios/libindy-pod) to your project.

3. Remove reference for the files BlobStorage.h & BlobStorage.mm (Indy/wrapper).

4. Create "Objective-C Bridging Header" and add `#import 'Indy.h'` inside it (for swift projects).

5. Disable bitcode for the project.

6.  Build and run.

**Comment by lalc** [comment]
Super good @rebink! Lets get cracking them with our mobile agent implementation.
