### ISSUE TITLE
Can't connect to another indy ledger with demo

### ISSUE THREAD

**Issue by steven0301** [hyperledger/indy-sdk#2225]
Hi,
I'm testing indy python demos (indy-sdk/vcx/wrappers/python3/demo) and I have some questions.
I wanted to test whether "alice", which is using vcx, can connect to another indy ledger which has its own transaction file.
I ran dummy cloud agent without indy pool and after that I ran ledger of von-network on local computer
I tried to change docker.txn file and then executed "python3 alice.py", followed by error messages below.

Could you tell me on which point I made a mistake?
Or, are there any options like genesis_url so that I can use it instead of using genesis transaction file?
Thank you.

--------------------------------------------------- messages ---------------------------------------------------
#8 Initialize libvcx with new configuration
Traceback (most recent call last):
  File "alice.py", line 138, in <module>
    loop.run_until_complete(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "alice.py", line 29, in main
    await init()
  File "alice.py", line 78, in init
    await vcx_init_with_config(config)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vcx/api/vcx_init.py", line 68, in vcx_init_with_config
    vcx_init_with_config.cb)
vcx.error.VcxError: (<ErrorCode.CreatePoolConfigParameters: 1025>, {'backtrace': '', 'cause': 'Error: Invalid library state\n  Caused by: Ledger merkle tree is not acceptable for current tree.\n\n', 'error': 'Connection to Pool Ledger.', 'message': 'Error: Connection to Pool Ledger.\n  Caused by: Can not open Pool Ledger\n  Caused by: \nindyrs::IndyError: Geneses transactions are invalid.\n  Caused by: Error: Invalid library state\n  Caused by: Ledger merkle tree is not acceptable for current tree.\n\n\n'})
---------------------------------------------------------------------------------------------------------------------------

**Comment by krgko** [comment]
Hi,

You can try to delete the file at `~/.indy_client` to clear pool config and wallet then try again. Do not forget to change `docket.txn` config to your indy network.

As I see current demo scripts it does not support genesis_url yet.

**Comment by steven0301** [comment]
@krgko Thank you, It works. I really appreciate it.
I have one more question.
I've got these message below when I ran faber.py
It seems TAA is needed to create scheme so I set TAA_ACCEPT as True and changed version and name of schema so that the ID of schema is not duplicated.
I don't think this error occurred because of ID duplication.
Could you give me an advice what to do to set TAA properly?

--------------------------------------- log ---------------------------------------
#3 Create a new schema on the ledger
Traceback (most recent call last):
  File "faber.py", line 210, in <module>
    loop.run_until_complete(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "faber.py", line 89, in main
    schema = await Schema.create('schema_uuid', '**degree1agree schema**', **version**, ['email', 'first_name', 'last_name'], 0)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vcx/api/schema.py", line 107, in create
    schema = await Schema._create("vcx_schema_create", constructor_params, c_params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vcx/api/vcx_base.py", line 47, in _create
    cls.create.cb)
vcx.error.VcxError: (<ErrorCode.DuplicateSchema: 1088>, {'backtrace': '', 'cause': 'Reject { reason: "client request invalid: InvalidClientTaaAcceptanceError(\\\'Incorrect Txn Author Agreement(digest=273df4edd0756bc4354f587e2f73db01acee711f925fef69bc85f878c3b7dc) in the request\\\',)" }', 'error': 'Duplicate Schema: Ledger Already Contains Schema For Given DID, Version, and Name Combination', 'message': 'Error: Duplicate Schema: Ledger Already Contains Schema For Given DID, Version, and Name Combination\n  Caused by: Reject { reason: "client request invalid: InvalidClientTaaAcceptanceError(\\\'Incorrect Txn Author Agreement(digest=273df4edd0756bc4354f587e2f73db01acee711f925fef69bc85f878c3b7dc) in the request\\\',)" }\n'})

**Comment by krgko** [comment]
Hi @steven0301,

The problem should be a version of requirements.txt out to date. You can go to `indy-sdk/vcx/wrappers/python3/demo` at `requirements.txt`, change the wrapper version from `python3-wrapper-vcx==0.6.2` to `python3-wrapper-vcx==0.8.0dev1565` which is latest one then pip install again that could works.

**Comment by gamertense** [comment]
I've been stuck with this issue for two hours and never realised that the library was really this old.
Thank you very much @krgko ! You just saved my day!

FYI: After changing `wrapper-vcx version`, I used this command to install the newer version of VCX: `pip install -r requirements.txt`
