### ISSUE TITLE
Postgres plug-in sha256 index is only supported on Postgres 11 or later

### ISSUE THREAD

**Issue by ianco** [hyperledger/indy-sdk#2231]
The recent change to the postgres plug-in to use a sha256 index breaks in postgres versions 10 and earlier (which is what we currently have deployed in BC Gov)

Suggestion to EITHER:
- have the plug-in auto-detect the postgres version, and for 10 and earlier us the "old style" index and for 11 and newer use the "sha256" index
- add a parameter to the wallet storage (for postgres) to allow selection of EITHER of the two index options

**Comment by ianco** [comment]
PS  Verified that the unit tests fail when run against a postgres 10 image

**Comment by WadeBarnes** [comment]
My preference would be to auto-detect method.

**Comment by andrewwhitehead** [comment]
I would prefer it didn't create large encrypted tags in the first place. What is the use case for that, is somebody going to use an image as a restriction in a proof request?

**Comment by jsaur** [comment]
Sorry about this - it might be simplest just to switch back to a md5 index, we only made the last minute swap to sha256 for ascetic reasons, we don't actually need any of the cryptographic properties of sha256.

**Comment by ianco** [comment]
I ran a quick test and md5 seems to work with postgres 10

**Comment by jsaur** [comment]
Ok here's a PR to switch it back to md5: https://github.com/hyperledger/indy-sdk/pull/2232

**Comment by WadeBarnes** [comment]
@andrewwhitehead, Wasn't there some mention of whether or not the index was even being used?

**Comment by ianco** [comment]
It's used when you do a WQL query against one of the attribute values

**Comment by andrewwhitehead** [comment]
I don't think the new index is used.

```
t=# CREATE TABLE t (data BYTEA);
CREATE TABLE
t=# CREATE INDEX t_d ON t(data);
CREATE INDEX
t=# EXPLAIN SELECT * FROM t WHERE data='test';
                            QUERY PLAN                            
------------------------------------------------------------------
 Bitmap Heap Scan on t  (cost=4.21..14.35 rows=7 width=32)
   Recheck Cond: (data = '\x74657374'::bytea)
   ->  Bitmap Index Scan on t_d  (cost=0.00..4.21 rows=7 width=0)
         Index Cond: (data = '\x74657374'::bytea)
```


```
t=# CREATE TABLE t (data BYTEA);
CREATE TABLE
t=# CREATE INDEX t_d ON t(sha256(data));
CREATE INDEX
t=# EXPLAIN SELECT * FROM t WHERE data='test';
                    QUERY PLAN                     
---------------------------------------------------
 Seq Scan on t  (cost=0.00..27.00 rows=7 width=32)
   Filter: (data = '\x74657374'::bytea)
```
