### ISSUE TITLE
What is the tails-server-base-url? and how should it be configured?

### ISSUE THREAD

**Issue by HarshMultani** [hyperledger/indy-sdk#2247]
I have installed the indy-sdk in my system and started the ledger network (It is running).
After that I setup the aries-cloudagent and ran the agent (as a steward) using the aca-py command.

Now, with the help of this agent, I have published the schema on the ledger, but when I am trying to send a credential definition on the ledger.. It is giving me the error :- 400: tails_server_base_url not configured..

Can anyone explain what is it and how can it be resolved?

**Comment by dhh1128** [comment]
Tagging @swcurran : who on your team worked on tails file impl, who might be able to help Harsh?

**Comment by swcurran** [comment]
This has been appropriately taken over to the ACA-Py repo, although technically, this is independent of ACA-Py. 

For those wondering, tails-server ([https://github.com/bcgov/indy-tails-server](https://github.com/bcgov/indy-tails-server)) is an implementation of a file server for publishing Indy revocation tails files.  It's basically a simple file server that has some extra checking to make sure that it is only serving actual tails files.  BC Gov has posted a public instance of a tails server that any indy issuer could use for posting their tails files.
