### ISSUE TITLE
Issue building postgres plugin on windows

### ISSUE THREAD

**Issue by RinkalBhojani** [hyperledger/indy-sdk#2248]
**I am trying to build postgres plugin on windows 10 and getting below error.
I have installed vcpkg from https://github.com/Microsoft/vcpkg and followed the steps of README.md

What can be the issue? or how can I compile and build the plugin for windows?**

 PS D:\Aries\indy-sdk\experimental\plugins\postgres_storage>> cargo build
   Compiling openssl-sys v0.9.53
   Compiling rust-libindy-wrapper v0.2.13
   Compiling zmq v0.8.3
error[E0463]: can't find crate for `vcpkg`                                                       
 --> C:\Users\admin\.cargo\registry\src\github.com-1ecc6299db9ec823\rust-libindy-wrapper-0.2.13\build.rs:3:1
  |
3 | extern crate vcpkg;
  | ^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `rust-libindy-wrapper`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: linking with `link.exe` failed: exit code: 1181                                           
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\\Users\\admin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "D:\\Aries\\indy-sdk\\experimental\\plugins\\postgres_storage\\target\\debug\\build\\zmq-0d95c5c1ffab67c0\\build_script_build-0d95c5c1ffab67c0.build_script_build.wrcokjew-cgu.0.rcgu.o" "D:\\Aries\\indy-sdk\\experimental\\plugins\\postgres_storage\\target\\debug\\build\\zmq-0d95c5c1ffab67c0\\build_script_build-0d95c5c1ffab67c0.build_script_build.wrcokjew-cgu.1.rcgu.o" "D:\\Aries\\indy-sdk\\experimental\\plugins\\postgres_storage\\target\\debug\\build\\zmq-0d95c5c1ffab67c0\\build_script_build-0d95c5c1ffab67c0.build_script_build.wrcokjew-cgu.10.rcgu.o" "D:\\Aries\\indy-sdk\\experimental\\plugins\\postgres_storage\\target\\debug\\build\\zmq-0d95c5c1ffab67c0\\build_script_build-0d95c5c1ffab67c0.build_script_build.wrcokjew-cgu.11.rcgu.o" "D:\\Aries\\indy-sdk\\experimental\\plugins\\postgres_storage\\target\\debug\\build\\zmq-0d95c5c1ffab67c0\\build_script_build-0d95c5c1ffab67c0.build_script_build.wrcokjew-cgu.12.rcgu.o" "D:\\Aries\\indy-sdk\\experimental\\plugins\\postgres_storage\\target\\debug\\build\\zmq-0d95c5c1ffab67c0\\build_script_build-0d95c5c1ffab67c0.build_script_build.wrcokjew-cgu.13.rcgu.o" "D:\\Aries\\indy-sdk\\experimental\\plugins\\postgres_storage\\target\\debug\\build\\zmq-0d95c5c1ffab67c0\\build_script_build-0d95c5c1ffab67c0.build_script_build.wrcokjew-cgu.14.rcgu.o" "D:\\Aries\\indy-sdk\\experimental\\plugins\\postgres_storage\\target\\debug\\build\\zmq-0d95c5c1ffab67c0\\build_script_build-0d95c5c1ffab67c0.build_script_build.wrcokjew-cgu.15.rcgu.o" "D:\\Aries\\indy-sdk\\experimental\\plugins\\postgres_storage\\target\\debug\\build\\zmq-0d95c5c1ffab67c0\\build_script_build-0d95c5c1ffab67c0.build_script_build.wrcokjew-cgu.2.rcgu.o" "D:\\Aries\\indy-sdk\\experimental\\plugins\\postgres_storage\\target\\debug\\build\\zmq-0d95c5c1ffab67c0\\build_script_build-0d95c5c1ffab67c0.build_script_build.wrcokjew-cgu.3.rcgu.o" "D:\\Aries\\indy-sdk\\experimental\\plugins\\postgres_storage\\target\\debug\\build\\zmq-0d95c5c1ffab67c0\\build_script_build-0d95c5c1ffab67c0.build_script_build.wrcokjew-cgu.4.rcgu.o" "D:\\Aries\\indy-sdk\\experimental\\plugins\\postgres_storage\\target\\debug\\build\\zmq-0d95c5c1ffab67c0\\build_script_build-0d95c5c1ffab67c0.build_script_build.wrcokjew-cgu.5.rcgu.o" "D:\\Aries\\indy-sdk\\experimental\\plugins\\postgres_storage\\target\\debug\\build\\zmq-0d95c5c1ffab67c0\\build_script_build-0d95c5c1ffab67c0.build_script_build.wrcokjew-cgu.6.rcgu.o" "D:\\Aries\\indy-sdk\\experimental\\plugins\\postgres_storage\\target\\debug\\build\\zmq-0d95c5c1ffab67c0\\build_script_build-0d95c5c1ffab67c0.build_script_build.wrcokjew-cgu.7.rcgu.o" "D:\\Aries\\indy-sdk\\experimental\\plugins\\postgres_storage\\target\\debug\\build\\zmq-0d95c5c1ffab67c0\\build_script_build-0d95c5c1ffab67c0.build_script_build.wrcokjew-cgu.8.rcgu.o" "D:\\Aries\\indy-sdk\\experimental\\plugins\\postgres_storage\\target\\debug\\build\\zmq-0d95c5c1ffab67c0\\build_script_build-0d95c5c1ffab67c0.build_script_build.wrcokjew-cgu.9.rcgu.o" "/OUT:D:\\Aries\\indy-sdk\\experimental\\plugins\\postgres_storage\\target\\debug\\build\\zmq-0d95c5c1ffab67c0\\build_script_build-0d95c5c1ffab67c0.exe" "D:\\Aries\\indy-sdk\\experimental\\plugins\\postgres_storage\\target\\debug\\build\\zmq-0d95c5c1ffab67c0\\build_script_build-0d95c5c1ffab67c0.59jh4sr0ybh8bcwn.rcgu.o" "/OPT:REF,NOICF" "/DEBUG" "/NATVIS:C:\\Users\\admin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\admin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\admin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/NATVIS:C:\\Users\\admin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libstd.natvis" "/LIBPATH:D:\\Aries\\indy-sdk\\experimental\\plugins\\postgres_storage\\target\\debug\\deps" "/LIBPATH:C:\\Windows\\System32\\lib" "/LIBPATH:C:\\Users\\admin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "D:\\Aries\\indy-sdk\\experimental\\plugins\\postgres_storage\\target\\debug\\deps\\libzmq_sys-e48e55f5143b346f.rlib" "D:\\Aries\\indy-sdk\\experimental\\plugins\\postgres_storage\\target\\debug\\deps\\liblibc-56d1094e4a067f3a.rlib" "C:\\Users\\admin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-1feb4ba9912f83e4.rlib" "C:\\Users\\admin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-10caf631bf17818d.rlib" "C:\\Users\\admin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_demangle-5f5b841e7dcb5069.rlib" "C:\\Users\\admin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libhashbrown-886e42042440a542.rlib" "C:\\Users\\admin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_alloc-fc3dfd2deda68757.rlib" "C:\\Users\\admin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-4765baa3d9fc6a1b.rlib" "C:\\Users\\admin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcfg_if-2af04b7075550e2b.rlib" "C:\\Users\\admin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-9f4eae3434a19b51.rlib" "C:\\Users\\admin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-14b08c3097e998dc.rlib" "C:\\Users\\admin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_core-9c0450bb353ef0cc.rlib" "C:\\Users\\admin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-4856f32e5e48bded.rlib" "C:\\Users\\admin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-0f66c8d6b2ebbbc4.rlib" "zmq.lib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "msvcrt.lib"  
  = note: LINK : fatal error LNK1181: cannot open input file 'zmq.lib'

error: aborting due to previous error

error: build failed

**Comment by MaticDiba** [comment]
Hi,
I'm getting this same error when trying to run `cargo build`. Is there any update on building postgres plugin on windows?
