### ISSUE TITLE
listMyDidsWithMeta API specification is different from implementation

### ISSUE THREAD

**Issue by toshirin33** [hyperledger/indy-sdk#2249]
As I pointed out in #2238 , listMyDidsWithMeta API returns json which includes tempVerkey field but  https://github.com/hyperledger/indy-sdk/blob/master/wrappers/nodejs/README.md does not say so.

**Comment by swcurran** [comment]
Link to description: https://github.com/hyperledger/indy-sdk/blob/master/wrappers/nodejs/README.md#listmydidswithmeta--wh----dids
