### ISSUE TITLE
Couldn't find libindy.so file in the targets folder

### ISSUE THREAD

**Issue by josmilan** [hyperledger/indy-sdk#2253]
Hi,

I have followed the steps in this [link](https://github.com/hyperledger/indy-sdk/tree/master/wrappers/java) and the cargo build was successful, but as a result, I was expecting the libindy.so file. but as a result, it didn't create libindy.so file. What I got are 
1. libindy.rlib
2. libindy.dylib.dSYM
3. libindy.dlib
4. libindy.d
5. libindy.a

Can anyone help

**Comment by geonnave** [comment]
Similar issue here, I followed this [python tutorial](https://github.com/hyperledger/indy-sdk/blob/master/docs/how-tos/write-did-and-query-verkey/README.md) and after doing `pip3 install python3-indy` I got the error `_load_cdll: Can't load libindy: libindy.so: cannot open shared object file: No such file or directory`.

**Comment by znss1989** [comment]
I encountered exactly the same issue following the Python tutorial. @geonnave Have you solved the problem, after `cargo build`? It seems not working for me. If yes, could you give some detailed steps to make the tutorial work? Thanks.

**Comment by geonnave** [comment]
@znss1989 yep the cargo build works. I'm on mobile now, but in short you have to follow another tutorial that explains how to build the libindy.so library. It is explained in the link I mentioned (for Ubuntu), but you can also check the main README for instructions for other platforms.

**Comment by znss1989** [comment]
@geonnave Thanks for the reply. After `cargo build`, I didn't result in a `libindy.so` file, but a directory `target/` with `.rustc_info.json` and stuff. Should it be found in the `/libindy/target/`?

**Comment by geonnave** [comment]
@znss1989 yes, it should be like this:

```
cd indy-sdk/libindy
cargo build
ls target/debug # libindy.so is here
```

Then, before testing the wrapper, `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/<replace this with the right path>/indy-sdk/libindy/target/debug` and `sudo ldconfig`.

**Comment by znss1989** [comment]
@geonnave Really thanks. That works for me.
