### ISSUE TITLE
Is there any clear and Proper Guide to integrate Indy on Native iOS ?

### ISSUE THREAD

**Issue by pavanMude** [hyperledger/indy-sdk#2259]
It is super excited to use Hyperledger Indy on iOS. But when it comes to the matter of Integration, it gets lot of confusion. I am working on Integrating Indy on iOS, and started through installing pods on Xcode Project. I have two pods named 
`pod 'libindy'` `pod 'libindy-objc', '~> 1.8.2'` There seems to be no problem in adding these two pods into the app. The real problem starts when running the app to check if its working or not, it breaks with the error:
  
**dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/pavankumarnaik/Library/Developer/CoreSimulator/Devices/0B216E4E-5073-4201-9F5F-15453276F2BE/data/Containers/Bundle/Application/91EECD31-2B1C-47C5-95C6-B013F91BF129/IndySdk.app/Frameworks/Indy.framework/Indy
  Reason: image not found**

I am struck at this point and I hope I would get some help to resume my work by solving the above mentioned issue. And I would request repo maintainers to provide Proper and Clear Readme/Guidelines so that it will be easy to integrate on requisite platforms.

**Comment by dhh1128** [comment]
Tagging @khagesh , @jovfer , and @smccown ; they may have useful guidance to offer.

**Comment by khagesh** [comment]
@pavanMude I think the actual error is related to this file `@rpath/libswiftCore.dylib` not getting found. This might be due to some issues on Xcode 11 and above.
Try manually adding `@rpath/libswiftCore.dylib` and it should work.

**Comment by pavanMude** [comment]
@khagesh I guess it has solved the problem however another problem raised here <unknown>:0: error: module compiled with Swift 4.2.1 cannot be imported by the Swift 5.3 compiler `/Users/IndySdk/ios/Pods/libindy-objc/libindy-objc/Indy.framework/Modules/Indy.swiftmodule/arm64.swiftmodule.`  `Libindy-objc` is not maintained frequently it seems. What can be done here, Can we expect a new release to avoid swift compiler error !?

**Comment by pavanMude** [comment]
@khagesh @dhh1128 @jovfer instead of all this confused steps and wrapper setups, Why don't we have a working demo app to make integration clear !?

**Comment by pavanMude** [comment]
Solved this issue, Closing.
