### ISSUE TITLE
indy-sdk-cd build fails with "error: component 'rust-std' for 'armv7-apple-ios' is unavailable for download"

### ISSUE THREAD

**Issue by WadeBarnes** [hyperledger/indy-sdk#2270]
The **iOS Test** step of the `indy-sdk-cd` build is failing while trying to install dependencies.

```
+ rustup target add aarch64-apple-ios armv7-apple-ios armv7s-apple-ios i386-apple-ios x86_64-apple-ios
info: component 'rust-std' for target 'aarch64-apple-ios' is up to date
error: component 'rust-std' for 'armv7-apple-ios' is unavailable for download
```

![image](https://user-images.githubusercontent.com/10504350/97718721-80455f00-1a83-11eb-8ba3-5dd54ea7a7b5.png)

Related build step:
- https://github.com/hyperledger/indy-sdk/blob/master/Jenkinsfile.cd#L769

The issue is seemingly related to the reduction of support for 32-bit.  The build is using Rust 1.46.0; https://github.com/hyperledger/indy-sdk/blob/master/Jenkinsfile.cd#L1769.  The reduction in support for the 32-bit targets started in Rust 1.42.0; [Reducing support for 32-bit Apple targets](https://blog.rust-lang.org/2020/01/03/reducing-support-for-32-bit-apple-targets.html)

**Comment by tmarkovski** [comment]
You're right, this issue is exactly due to dropping support for 320bit targets from the stable toolchain. Looks like you need to pin the toolchain to a specific nightly version as explained here.

https://blog.rust-lang.org/2020/01/03/reducing-support-for-32-bit-apple-targets.html#what-about-the-nightly-channel

```
rustup toolchain install nightly-2019-12-01

# Default to this nightly system-wide...
rustup default nightly-2019-12-01

# ...or use this nightly for a single build
cargo +nightly-2019-12-01 build
```

It may also be worthwhile dropping the 32bit targets from the static libraries altogether.

**Comment by WadeBarnes** [comment]
Personally I'm not a fan of pinning the toolchain.  @tmarkovski, What are the ramifications to the user community with respect to dropping the 32bit targets?

**Comment by tmarkovski** [comment]
Probably very low to none. Apple dropped support for 32bit apps in 2017.

**Comment by dhh1128** [comment]
Evernym may have some use cases where 32-bit android support is important, but not 32-bit iOS. Let me check.

**Comment by tmarkovski** [comment]
I believe we're only considering 32-bit iOS targets here. Android 32-bit is fairly common.

**Comment by mccown** [comment]
Apple stopped supporting 32-bit with iOS 11 in 2017.  From what I'm reading, 98.8% of all iOS devices now use iOS version 11 or later.  I think its reasonable to drop 32-bit support.
