### ISSUE TITLE
Fix broken indy-sdk CD on Jenkins

### ISSUE THREAD

**Issue by Toktar** [hyperledger/indy-sdk#2277]
The latest master builds cannot be completed due to the problem with building packages for iOS.
Problem reason: Apple reduced support for 32-bit platforms, so Rust reduced it too, it can be fixed by removing 32-bit builds from Indy SDK CD. Quickest and most straightforward way to solve this is to remove packages for the following architectures:
- ```armv7-apple-ios```
- ```armv7s-apple-ios```
- ```i386-apple-ios```

https://blog.rust-lang.org/2020/01/03/reducing-support-for-32-bit-apple-targets.html

**Comment by Toktar** [comment]
PR: https://github.com/hyperledger/indy-sdk/pull/2276

**Comment by adenishchenko** [comment]
PR: #2280

Work in progress
