### ISSUE TITLE
Cannot build libindy-objc with iOS 14

### ISSUE THREAD

**Issue by berkakkerman** [hyperledger/indy-sdk#2278]
When I tried to import Indy throws an compiler error like below;

`import Indy`

>  _Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.3 compiler: ....Pods/libindy-objc/libindy-objc/Indy.framework/Modules/Indy.swiftmodule/arm.swiftmodule_

Will a new version be released?

Also I tried with 'pod libindy' but libindy has not enough documentation for ios. How can I use libindy in my iOS project? How to import 'libindy.a'?

**Comment by riccardocaranfil** [comment]
@berkakkerman just look at this issue, finally got it for swift 5

[https://github.com/AbsaOSS/rn-indy-sdk/issues/20#issuecomment-725611052](https://github.com/AbsaOSS/rn-indy-sdk/issues/20#issuecomment-725611052)
