### ISSUE TITLE
Rust 1.48.0 Issues ( libindy ) thread panicked at 'attempted to leave type linked_hash_map

### ISSUE THREAD

**Issue by saeveritt** [hyperledger/indy-sdk#2301]
The following error was encountered after building libindy with Rust 1.48.0 https://github.com/rust-lang/rust/blob/master/RELEASES.md

When creating DIDs or new Payment Address I experienced the following error,

_thread '<unnamed>' panicked at 'attempted to leave type linked_hash_map::Node<std::string::String, raw_statement::RawStatement> uninitialized, which is invalid', /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/mem/mod.rs:658:9_

**Temporary Solution:**
Revert to version 1.47.0
`rustup default 1.47.0`
Rebuild libindy
`cargo build`

**Comment by OoDeLally** [comment]
We also experience hangings with Rust 1.48.0 when calling `configure_trustee_did` (which calls `libindy_prover_create_master_secret`).
The hanging doesn't occur when compiled with 1.45.
Probably related.

**Comment by AxelNennker** [comment]
I think this https://github.com/hyperledger/indy-sdk/pull/2311 fixes this issue
