### ISSUE TITLE
postgres plugin build issue

### ISSUE THREAD

**Issue by paliwalg** [hyperledger/indy-sdk#2316]
Able to successfully do the cargo build for postgres but don't see libindystrgpostgres.dylib getting generated. After successful build I see these files under target/debug/ folder

indystrgpostgres-4c6aead9638eafd3*
indystrgpostgres-4c6aead9638eafd3.d
libindystrgpostgres.a
libindystrgpostgres.d
libindystrgpostgres.rlib
libindystrgpostgres.so*

Because of this load-plugin library=../experimental/plugins/postgres_storage/target/debug/libindystrgpostgres.dylib initializer=postgresstorage_init fails with the file missing error.

Please advice .

**Comment by ianco** [comment]
What platform are you running on?  The .dylib is a Mac-specific library

**Comment by paliwalg** [comment]
Ok, it is ubuntu 18 and I am referring to script at location https://github.com/hyperledger/indy-sdk/blob/master/experimental/plugins/postgres_storage/cli_ps_test.txt
What should I use in place of .dylib ? 

Thanks

**Comment by ianco** [comment]
Yes use the .so file
