### ISSUE TITLE
RUSTSEC-2020-0053: dirs: dirs is unmaintained, use dirs-next instead 

### ISSUE THREAD

**Issue by brightly-salty** [hyperledger/indy-sdk#2325]
https://rustsec.org/advisories/RUSTSEC-2020-0053

```
Crate:         dirs
Version:       2.0.2
Warning:       unmaintained
Title:         dirs is unmaintained, use dirs-next instead
Date:          2020-10-16
ID:            RUSTSEC-2020-0053
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0053
Dependency tree:
dirs 2.0.2
```

dirs is unmaintained, dirs-next should be used instead. This is specifically for the libindy crate.

I would be willing to implement this and submit a PR if it would be accepted.

**Comment by dhh1128** [comment]
Please do! We'd love to have it!

**Comment by brightly-salty** [comment]
The build in the PR has failed, but when I try to see details, it sends me to an auth page. I ran `cargo check` on my machine and everything works fine. What should my next step be?

**Comment by jovfer** [comment]
@brightly-salty thanks for identifying the problem and providing the PR with a fix!

I'll post logs of the pipeline to the PR.
