### ISSUE TITLE
ipython-notebook not found when creating the docker container in the getting-started section.

### ISSUE THREAD

**Issue by mihaipop11** [hyperledger/indy-sdk#2347]
After navigating to `docs/getting-started` and calling `$ docker-compose up`, `ipython-notebook` doesn't have an installation candidate in the docker container.

```
  Could not find a version that satisfies the requirement ipython-notebook (from versions: )
No matching distribution found for ipython-notebook
You are using pip version 8.1.1, however version 20.3.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by mihaipop11** [comment]
The `ipython-notebook` package seems to have been removed. The notebook installation can be fixed by installing `ipython[notebook]` instead of `ipython-notebook`.

What do you think about this solution? I would be more than happy to open a PR with this change.

**Comment by conwaychriscosmo** [comment]
I had to change the dockerfile too.
```
FROM ubuntu:16.04

RUN useradd -ms /bin/bash indy

# Install environment
RUN apt-get update -y && apt-get install -y \
	wget \
	python3.5 \
	python3-pip \
	python-setuptools \
	apt-transport-https \
	ca-certificates \
	software-properties-common

WORKDIR /home/indy
RUN pip3 install -Iv pip==19.1.1
RUN pip3 install -U \
	pip \
    ipython==7.9 \
	setuptools \
	jupyter \
	python3-indy==1.11.0

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CE7709D068DB5E88 \
    && add-apt-repository "deb https://repo.sovrin.org/sdk/deb xenial stable" \
    && apt-get update \
    && apt-get install -y \
    libindy=1.11.0

USER indy

EXPOSE 8888
```

**Comment by conwaychriscosmo** [comment]
I installed pip 19.1.1 because the latest version is incompatible with python v3.5 and the error message suggested upgrading pip from version 8.  I then removed the ipython-notebook line.  The getting started jupyter notebook then ran properly.

**Comment by conwaychriscosmo** [comment]
Someone addressed it in this unmerged pr https://github.com/hyperledger/indy-sdk/pull/2261
