### ISSUE TITLE
RuntimeError: Cannot run the event loop while another loop is running

### ISSUE THREAD

**Issue by abhik-99** [hyperledger/indy-sdk#2371]
I am trying to run the [Getting Started Jupyter Notebook](https://github.com/hyperledger/indy-sdk/blob/master/docs/getting-started/getting-started.ipynb) after getting a network up by following the instructions given at [Indy Getting Started with Docker](https://hyperledger-indy.readthedocs.io/projects/sdk/en/latest/docs/getting-started/run-getting-started.html). 

Once the network of docker containers startup, I am trying to execute the notebook however it is displaying the following error:-

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-34cc7413584a> in <module>
    731     loop = asyncio.new_event_loop()
    732     asyncio.set_event_loop(loop)
--> 733     loop.run_until_complete(run())
    734     time.sleep(1)  # FIXME waiting for libindy thread complete

/usr/lib/python3.6/asyncio/base_events.py in run_until_complete(self, future)
    469         future.add_done_callback(_run_until_complete_cb)
    470         try:
--> 471             self.run_forever()
    472         except:
    473             if new_task and future.done() and not future.cancelled():

/usr/lib/python3.6/asyncio/base_events.py in run_forever(self)
    426         if events._get_running_loop() is not None:
    427             raise RuntimeError(
--> 428                 'Cannot run the event loop while another loop is running')
    429         self._set_coroutine_wrapper(self._debug)
    430         self._thread_id = threading.get_ident()

RuntimeError: Cannot run the event loop while another loop is running
```
The Getting Started notebook only has one cell with all the code included as a big script in one cell. On running the cell the above error is displayed. Please help.

PS: Also, it would be very helpful if the code in the notebook is well-segregated into different cells for each task with proper markdown cells in-between explaining the function performed by the cell.

**Comment by xoryouyou** [comment]
I am not sure why but this seems to work https://github.com/hyperledger/indy-sdk/issues/2379#issuecomment-909142303

Maybe due to awaiting somehow captures the jupyter event loop.

Someone with more insight might give this a look, but "it works" :shrug:
