### ISSUE TITLE
BUILD SUCCESSFULL - TEST FAILED !! Could not successfully test the libindy build 

### ISSUE THREAD

**Issue by Aashish07** [hyperledger/indy-sdk#2381]
This error comes running this command :-
services::pool::merkle_tree_factory::tests::pool_worker_build_node_state_works_for_old_format stdout ----
thread 'services::pool::merkle_tree_factory::tests::pool_worker_build_node_state_works_for_old_format' panicked at 'called `Result::unwrap()` on an `Err` value: IndyError { inner: 

Libindy PROTOCOL_VERSION is 2 but Pool Genesis Transactions are of version 1.3.Call indy_set_protocol_version(1) to set correct PROTOCOL_VERSION

Pool Genesis Transactions are not compatible with Protocol version }', src/services/pool/merkle_tree_factory.rs:345:64

---- services::pool::request_handler::tests::single::request_handler_process_reply_event_from_single_state_works_for_state_proof_from_past stdout ----
thread 'services::pool::request_handler::tests::single::request_handler_process_reply_event_from_single_state_works_for_state_proof_from_past' panicked at 'assertion failed: match request_handler_ref.state {\n    RequestState::Single(_) => true,\n    _ => false,\n}', src/services/pool/request_handler.rs:1332:17

failures:
    services::pool::merkle_tree_factory::tests::pool_worker_build_node_state_works_for_new_format
    services::pool::merkle_tree_factory::tests::pool_worker_build_node_state_works_for_old_format
    services::pool::request_handler::tests::single::request_handler_process_reply_event_from_single_state_works_for_state_proof_from_past

test result: FAILED. 398 passed; 3 failed; 1 ignored; 0 measured; 0 filtered out; finished in 7.69s

**Comment by SajanRajak** [comment]
Facing the same issue :
Libindy PROTOCOL_VERSION is 2 but Pool Genesis Transactions are of version 1.3.Call indy_set_protocol_version(1) to set correct PROTOCOL_VERSION. Did you got any way through??
