### ISSUE TITLE
Get the mining time of a transaction

### ISSUE THREAD

**Issue by RadNi** [hyperledger/indy-sdk#2384]
I'm using the indy-cli tool to send a simple new nym command to the ledger. [Here](https://hyperledger-indy.readthedocs.io/projects/plenum/en/latest/request_handling.html) it is written that the target node only responds when the request is mined:

> If the ORDERED message above was sent by the master replica then the node executes the request; meaning they commit any changes made to the ledger and state by that request by calling commit_batch method of write_manager and send a Reply back to client.

The above note is also completely verifiable from the [source code](https://github.com/hyperledger/indy-plenum/blob/master/plenum/server/node.py#L2753)

I would like to know when I'm sending transactions using indy-cli, when the transactions actually have been mined. Can I say when the client shows `Nym request has been sent to Ledger.` my transaction is mined, or it only indicates that the transaction is just sent to the network?
Below I provided my simple test-case:

`ledger nym did="PhW4VDkXkU7M1YEvnfji4m" verkey="~YRGE6bGuatnAduxGztDKeV" role="TRUST_ANCHOR"`

The command works properly and after execution it outputs:

```
Nym request has been sent to Ledger.
Metadata:
+------------------------+-----------------+---------------------+---------------------+
| From                   | Sequence Number | Request ID          | Transaction time    |
+------------------------+-----------------+---------------------+---------------------+
| Th7MpTaRZVRYnPiabds81Y | 17              | 1619192224942594170 | 2021-04-23 15:37:05 |
+------------------------+-----------------+---------------------+---------------------+
Data:
+------------------------+-------------------------+----------+
| Did                    | Verkey                  | Role     |
+------------------------+-------------------------+----------+
| PhW4VDkXkU7M1YEvnfji4m | ~YRGE6bGuatnAduxGztDKeV | ENDORSER |
+------------------------+-------------------------+----------+
```

If it only tells me that the transaction just sent to the network, then how can I determine the mining time of my request?

**Comment by andrewwhitehead** [comment]
Indy-Node is a permissioned blockchain, there is no mining involved. The sequence number in the output indicates that the transaction has been written.

**Comment by RadNi** [comment]
@andrewwhitehead  Sorry, by mining I mean, as far as I know, nodes need to perform a consensus protocol and agree upon writing this new transaction on the ledger. So I'm seeking a way to calculate the time needed to write a new valid transaction in the ledger. 
From what I learned from your note, I can say that the time I see the output of my request could be a good indicator of what I am looking for if I am not mistaken.
