### ISSUE TITLE
sovrin_store_their_did call doesn't support verkeys in and abbreviated form

### ISSUE THREAD

**Issue by vimmerru** [hyperledger/indy-sdk#24]
sovrin_store_their_did call doesn't support verkeys in and abbreviated form. I suggest adding support of providing verkey in abbreviated form.

**Comment by dhh1128** [comment]
Seems like a good suggestion. Let's do it.

**Comment by jovfer** [comment]
Fixed in https://github.com/hyperledger/indy-sdk/pull/307
