### ISSUE TITLE
Indy SDK Getting Started Docker Compose Problem

### ISSUE THREAD

**Issue by rajgohel89** [hyperledger/indy-sdk#2404]
I'm using Ubuntu 16.4 64bit os.

I have created virtual environment-
virtualenv -p python3.5 **indyvenv**
source indyvenv/bin/activate

Now, i executed - `docker-compose up`

Error - 
Step 6/9 : RUN pip3 install -U 	pip 	ipython-notebook       ipython==7.9 	setuptools 	jupyter 	python3-indy==1.11.0
 ---> Running in 9676201b2a3e
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 7, in <module>
    from pip._internal.cli.main import main
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/main.py", line 58
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax

**Comment by ianco** [comment]
I suspect in your docker you have the wrong version of python (2 vs 3)

**Comment by 89bitrelation-89** [comment]
i tried with both but no luck. spent more than 6 hr. If you can help then would be great.

**Comment by 89bitrelation-89** [comment]
`python3 --version`
Command gave - `Python 3.5.2`

**Comment by ianco** [comment]
Can you provide a link to the document you are following?

**Comment by 89bitrelation-89** [comment]
@ianco i'm following - https://hyperledger-indy.readthedocs.io/projects/sdk/en/latest/docs/getting-started/run-getting-started.html

**Comment by ianco** [comment]
Ah ok I haven't tried this tutorial, I tried to run a jupyter notebook once and I couldn't get it to work.  I suspect this demo is out of date and needs to be updated.

What are you trying to accomplish, just learning about indy?  You may be better off looking at one of the Aries tutorials.  (Aries agents "wrap" indy and provide a higher level set of API's.  There are Aries agents in Python, Go and other languages, and the docs/tutorials are a bit more up-to-date.  I can recommend aries-cloudagent-python since this is the project I'm involved with, but the other are equally good.)

**Comment by 89bitrelation-89** [comment]
@ianco i did few changes able to proceed but now error is something different.

/docs/getting-started$ docker-compose up
Creating network "getting-started_pool_network" with driver "bridge"
Creating indy_pool ... done
Creating getting_started ... done
Attaching to indy_pool, getting_started
indy_pool | 2021-06-29 17:25:17,131 CRIT Set uid to user 1000
getting_started | Traceback (most recent call last):
getting_started | File "/usr/local/bin/jupyter-notebook", line 6, in
getting_started | from notebook.notebookapp import main
getting_started | File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 81, in
getting_started | from .services.kernels.kernelmanager import MappingKernelManager, AsyncMappingKernelManager
getting_started | File "/usr/local/lib/python3.5/dist-packages/notebook/services/kernels/kernelmanager.py", line 18, in
getting_started | from jupyter_client.session import Session
getting_started | File "/usr/local/lib/python3.5/dist-packages/jupyter_client/init.py", line 6, in
getting_started | from .asynchronous import AsyncKernelClient # noqa
getting_started | File "/usr/local/lib/python3.5/dist-packages/jupyter_client/asynchronous/init.py", line 1, in
getting_started | from .client import AsyncKernelClient # noqa
getting_started | File "/usr/local/lib/python3.5/dist-packages/jupyter_client/asynchronous/client.py", line 6, in
getting_started | from jupyter_client.channels import HBChannel
getting_started | File "/usr/local/lib/python3.5/dist-packages/jupyter_client/channels.py", line 47
getting_started | time_to_dead: float = 1.0
getting_started | ^
getting_started | SyntaxError: invalid syntax
getting_started exited with code 1

**Comment by kingworm** [comment]
+1

**Comment by kingworm** [comment]
@89bitrelation-89 

I've installed jupyter in ubuntu 16.04 dockerfile successfully.

**Comment by kingworm** [comment]
@89bitrelation-89 
I've succeed to build GSG.dockerfile !!

**Comment by kingworm** [comment]
#2410  I've created PR for changes

**Comment by matapo** [comment]
@kingworm thanks! I was starting to procrastinate already

**Comment by kingworm** [comment]
Hi, @matapo 
have you tried reset docker cache?
Or "remove" the container & images and then try again.

for now, I'm not using indy-sdk, but using ACA-py. :)

**Comment by Hormuz1** [comment]
Good Morning from Australia, Recently our developers have encountered this issue:
https://github.com/hyperledger/indy-sdk/issues/2404

Can some one please help us in finding a solution and the steps taken to ensure this error doesn't happen. 

thank you
Hormuz
