### ISSUE TITLE
How to build a production network？

### ISSUE THREAD

**Issue by Ning-Qing** [hyperledger/indy-sdk#2454]
### Create a pool in container A with only one node in the pool
`generate_indy_pool_transactions --nodes=1 --clients=5 --nodeNum=1`
`start_indy_node Node1 0.0.0.0 9701 0.0.0.0 9702`
### Create a node in container B
`init_indy_node Node2 0.0.0.0 9701 0.0.0.0 9702`
`start_indy_node Node2 0.0.0.0 9701 0.0.0.0 9702`
### Use indy-cli in container A and use Steward to add nodes
`ledger node target=HJsE33JARsLFriCfw6etAkjrHgXwkDZD8d3mucoUWoBZ client_port=9704 client_ip=172.22.93.139 alias=Node2 node_ip=172.22.93.139 node_port=9703 services=VALIDATOR blskey=3riyWmVNFTEmuHEWHjoaGzGFV5c32dsuJBRpjJqtjYwjKWqe1GfdWSQXMSP45phkojF4dCqiaTpPtbmQfyKF7a4m2NXJnuVmoq9AvGcp44gnzyY4GFwi24A2pFKxnCxxzB2CZJu9X8RDVtu4wqSv3Ys8ZTVyHyFtK1jWELemLJkCJFy blskey_pop=RXkfiJQ3Vsyxi6nZysDJ2eTmwx6NcEX8SCLWLhF95f8vwescyEGppKAXrPUFRNbGLiYpdW1mxQEmVVxiNNv2jCAkvbntNsdgt83h1FGTDnVdQSsUcqMCkrYhDkFixJ1eC6w74ncu9fLUwwRvGDw8YF1ZQx9JLGkvmwXi5v81B3D7nw`
**docker inet is 172.22.86.104，Ports 9701 and 9702 of container B are mapped to  9703 and 9704**
### Failed to add node
Transaction response has not been received

### So how to create a pool where nodes can be added

**Comment by WadeBarnes** [comment]
This question should be asked over here; https://github.com/hyperledger/indy-node/issues

Regardless, here are some resources:

If you are using the network for development and testing I'd recommend using:
- https://github.com/bcgov/von-network
or
- https://github.com/IDunion/indy-node-container

If you're intent on building the network from scratch there are these resources:
- https://github.com/hyperledger/indy-node/issues/1674
which is the basis of
- https://github.com/hyperledger/indy-node/pull/1689

**Comment by Ning-Qing** [comment]
thanks

**Comment by WadeBarnes** [comment]
https://github.com/hyperledger/indy-node/blob/master/docs/source/NewNetwork/NewNetwork.md
