### ISSUE TITLE
Mac OS when I install the pod file using indy-idk-master file then libzmq platform.hpp file not exist

### ISSUE THREAD

**Issue by ChaJaewook** [hyperledger/indy-sdk#2456]
Hi. I try to use Hyperledger indy sdk in apple mobile device.
So I use the cocoa pods to install the pod files in 'indy-sdk-master/wrappers/ios/libindy-pod'
When I 'pod install' command result is

`user@userui-MacBookPro libindy-pod % pod install
Analyzing dependencies
Downloading dependencies
Installing OpenSSL (1.0.210)
Installing libindy (1.15.0)
Installing libsodium (1.0.12)
Installing libzmq (4.0.4)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `Indy.xcworkspace` for this project from now on.
Pod installation complete! There are 4 dependencies from the Podfile and 4 total pods installed.`

and makes Pods folder, Indy.xcworkspace, Profile.lock.
So I think pod installed well but when I open Indy.xcworkspace using Xcode program the 'libzmq' doesn't have platform.hpp file.

I search that platform.hpp made by cmake or autotools using cmakelist file. but I can't find it plz help! 
Thanks. 

pod file code is
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/hyperledger/indy-sdk.git'
platform :ios, '13.5'

workspace 'Indy.xcworkspace'

def appPods
    pod 'libsodium'
    pod 'libzmq', "4.2.3"
    pod 'OpenSSL'
    pod 'libindy', "1.15.0"
end

target 'Indy' do
    project 'Indy'
    appPods
end

# ignore all warnings from all pods
#inhibit_all_warnings!

post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'libzmq'
        target.build_configurations.each do |config|
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'ZMQ_BUILD_DRAFT_API=1']
        end
      end
      if target.name == 'libsodium'
        target.build_configurations.each do |config|
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'NATIVE_LITTLE_ENDIAN=1 PACKAGE_NAME=\"libsodium\" PACKAGE_TARNAME=\"libsodium\" PACKAGE_VERSION=\"1.0.12\" PACKAGE_STRING=\"libsodium\ 1.0.12\" PACKAGE_BUGREPORT=\"https://github.com/jedisct1/libsodium/issues\" PACKAGE_URL=\"https://github.com/jedisct1/libsodium\" PACKAGE=\"libsodium\" VERSION=\"1.0.12\" HAVE_PTHREAD_PRIO_INHERIT=1 HAVE_PTHREAD=1 STDC_HEADERS=1 HAVE_SYS_TYPES_H=1 HAVE_SYS_STAT_H=1 HAVE_STDLIB_H=1 HAVE_STRING_H=1 HAVE_MEMORY_H=1 HAVE_STRINGS_H=1 HAVE_INTTYPES_H=1 HAVE_STDINT_H=1 HAVE_UNISTD_H=1 _POSIX_PTHREAD_SEMANTICS=1 NATIVE_LITTLE_ENDIAN=1 HAVE_WEAK_SYMBOLS=1 CPU_UNALIGNED_ACCESS=1 CONFIGURED=1']
        end
      end
    end
end

**Comment by WadeBarnes** [comment]
@smccown, @mirgee, Any thoughts?

**Comment by JamesKEbert** [comment]
In case helpful for anyone in the future--I also ran into this issue. The instructions didn't specify to install cmake prior to running the pod install--if you run the pod install with `--verbose` without cmake, it does mention not being able to find cmake. 

This is the relevant comment/issue from ZMQ: https://github.com/zeromq/libzmq/issues/1928#issuecomment-1067569139
