### ISSUE TITLE
Cannot install iOS wrapper pods

### ISSUE THREAD

**Issue by MosCD3** [hyperledger/indy-sdk#2459]
When I attempt to install pods here
indy-sdk/wrappers/ios/libindy-pod/

I get this

`Fetching podspec for `CoreBitcoin` from `https://raw.github.com/oleganza/CoreBitcoin/master/CoreBitcoin.podspec`
Downloading dependencies
Installing CoreBitcoin (0.6.8.1)
Installing ISO8601DateFormatter (0.8)
Installing OpenSSL (1.0.210)
[!] /bin/bash -c 
set -e
VERSION="1.0.2j"
SDKVERSION=`xcrun --sdk iphoneos --show-sdk-version 2> /dev/null`
MIN_SDK_VERSION_FLAG="-miphoneos-version-min=7.0"

BASEPATH="${PWD}"
CURRENTPATH="/tmp/openssl"
ARCHS="i386 x86_64 armv7 armv7s arm64"
DEVELOPER=`xcode-select -print-path`

mkdir -p "${CURRENTPATH}"
mkdir -p "${CURRENTPATH}/bin"

cp "file.tgz" "${CURRENTPATH}/file.tgz"
cd "${CURRENTPATH}"
tar -xzf file.tgz
cd "openssl-${VERSION}"

for ARCH in ${ARCHS}
do
  CONFIGURE_FOR="iphoneos-cross"

  if [ "${ARCH}" == "i386" ] || [ "${ARCH}" == "x86_64" ] ;
  then
    PLATFORM="iPhoneSimulator"
    if [ "${ARCH}" == "x86_64" ] ;
    then
      CONFIGURE_FOR="darwin64-x86_64-cc"
    fi
  else
    sed -ie "s!static volatile sig_atomic_t intr_signal;!static volatile intr_signal;!" "crypto/ui/ui_openssl.c"
    PLATFORM="iPhoneOS"
  fi

  export CROSS_TOP="${DEVELOPER}/Platforms/${PLATFORM}.platform/Developer"
  export CROSS_SDK="${PLATFORM}${SDKVERSION}.sdk"

  echo "Building openssl-${VERSION} for ${PLATFORM} ${SDKVERSION} ${ARCH}"
  echo "Please stand by..."

  export CC="${DEVELOPER}/usr/bin/gcc -arch ${ARCH} ${MIN_SDK_VERSION_FLAG}"
  mkdir -p "${CURRENTPATH}/bin/${PLATFORM}${SDKVERSION}-${ARCH}.sdk"
  LOG="${CURRENTPATH}/bin/${PLATFORM}${SDKVERSION}-${ARCH}.sdk/build-openssl-${VERSION}.log"

  LIPO_LIBSSL="${LIPO_LIBSSL} ${CURRENTPATH}/bin/${PLATFORM}${SDKVERSION}-${ARCH}.sdk/lib/libssl.a"
  LIPO_LIBCRYPTO="${LIPO_LIBCRYPTO} ${CURRENTPATH}/bin/${PLATFORM}${SDKVERSION}-${ARCH}.sdk/lib/libcrypto.a"

  ./Configure ${CONFIGURE_FOR} --openssldir="${CURRENTPATH}/bin/${PLATFORM}${SDKVERSION}-${ARCH}.sdk" > "${LOG}" 2>&1
  sed -ie "s!^CFLAG=!CFLAG=-isysroot ${CROSS_TOP}/SDKs/${CROSS_SDK} !" "Makefile"

  make >> "${LOG}" 2>&1
  make all install_sw >> "${LOG}" 2>&1
  make clean >> "${LOG}" 2>&1
done

echo "Build library..."
rm -rf "${BASEPATH}/lib/"
mkdir -p "${BASEPATH}/lib/"
lipo -create ${LIPO_LIBSSL}    -output "${BASEPATH}/lib/libssl.a"
lipo -create ${LIPO_LIBCRYPTO} -output "${BASEPATH}/lib/libcrypto.a"

echo "Copying headers..."
rm -rf "${BASEPATH}/opensslIncludes/"
mkdir -p "${BASEPATH}/opensslIncludes/"
cp -RL "${CURRENTPATH}/openssl-${VERSION}/include/openssl" "${BASEPATH}/opensslIncludes/"

cd "${BASEPATH}"
echo "Building done."

echo "Cleaning up..."
rm -rf "${CURRENTPATH}"
echo "Done."

[!] The Podfile contains framework or static library targets (Indy), for which the Podfile does not contain host targets (targets which embed the framework).
If this project is for doing framework development, you can ignore this message. Otherwise, add a target to the Podfile that embeds these frameworks to make this message go away (e.g. a test target).
`

Any Idea?

What I am trying to do is 

1- To re-build the framework by executing 

xcodebuild archive \
-scheme [Whatever] \
-configuration Release \
-destination 'generic/platform=iOS Simulator' \
-archivePath '[whatever]' \
SKIP_INSTALL=NO \
BUILD_LIBRARIES_FOR_DISTRIBUTION=YES

Or use the "universal_framework.sh" if I couldn't build one for simulator
I believe I should install the pods first then try to build the framework

Thanks in advance

**Comment by blu3beri** [comment]
Following [these instructions](https://github.com/hyperledger/indy-sdk/blob/master/wrappers/ios/README.md#how-to-manually-build) left me with a static library which can then be converted into a `XCFramework` with 

```bash
xcodebuild -create-xcframework -library libindy.a -headers ... -output libindy.xcframework
```

I did encounter the same error as you while doing `pod install`. I am not too familiar with the inner workings of pods and I can not help you with that unfortunately.

**Comment by MosCD3** [comment]
I am stuck at the instructions at this line
7. Run the script Validate the output that all goes well.
it says run the script so I believe its the 
 ./ios-build.sh
Can you tell me the exact run commandyou used ? like what 
 ./ios-build.sh [other parameters]

**Comment by blu3beri** [comment]
I just executed `./indy-build.sh libindy`. 

For crossplatform there might be some additional setup that I am unaware of. I am also quite sure Libindy will never get support for ios smulators as openSSL for iOS, that we depend on, is not build for the simulator. Messed around with it today and could not get it to work. I must say that I am not an iOS expert and it might be possible by changing the openssl dependency to one that works for the sim.

**Comment by MosCD3** [comment]
It turns out that the docs really needs overhaul. 
There is steps missing and vague guides, this repo really needs attention
After lots search on the web for every step I could finally manually build the framework
I'll be creating a PR for adding and clarifying some more steps and troubleshooting for that
So right now I have the framework build to 
libindy>out_pod
Now am confused, how to convert that to Indy.framework 
Again the guide is confusing 
Do I have to manually create a framework project then copy those files created to that project then build it?
Am really confused

**Comment by blu3beri** [comment]
Not too sure about the next step, sorry. 

I completely agree about the guides, however I am not too sure if PRs are still being accepted. It would be very helpful ofcourse but I can not merge is sadly. If you have a guide I can test it for you and review it though.

**Comment by WadeBarnes** [comment]
I can help make sure the updated documentation gets merged.

**Comment by MosCD3** [comment]
I will prepare a PR
