### ISSUE TITLE
Builds failing due to Rust (Cargo) version issues

### ISSUE THREAD

**Issue by WadeBarnes** [hyperledger/indy-sdk#2460]
`indy-sdk` Jenkins builds are failing with the following error:

```
error: failed to parse manifest at `/home/indy/.cargo/registry/src/github.com-1ecc6299db9ec823/crypto-bigint-0.2.11/Cargo.toml`

Caused by:
  feature `resolver` is required
  this Cargo does not support nightly features, but if you
  switch to nightly channel you can add
  `cargo-features = ["resolver"]` to enable this feature
script returned exit code 101
```

**Comment by WadeBarnes** [comment]
Additional details from @ianco:

This is happening on a couple of dependencies (const-oid above, also pkcs8). Looks like they are including resolver = "2" in their Cargo.toml files, and then the builds are failing because the Rust version we are using doesn't support this feature.

Seems to relate to this: https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2

I tried locally with the latest rust version (1.57.0) and get the same error. If I install rust nightly (1.59.0-nightly) then the build seems to work :-S

(Also if I build everything using the nightly rust, and then switch back to stable everything seems to work, so it's an issue downloading the dependencies but not building them)

**Comment by WadeBarnes** [comment]
@ianco, Can you think of any concerns with updating the pipelines to use the Rust 1.59.0-nightly release?  My concern would be stability.

**Comment by ianco** [comment]
> @ianco, Can you think of any concerns with updating the pipelines to use the Rust 1.59.0-nightly release? My concern would be stability.

I'd prefer to not use a nightly release, however the "stable" release isn't working, so an unstable release that works would be an improvement?

I don't think there are any releases planned in the near future so probably not an issue to update the version so we can get our builds to pass.  Maybe also create an issue to switch to the sable version once it's stable?

**Comment by jovfer** [comment]
you can just pin such dependencies to previous versions, I guess...

**Comment by jovfer** [comment]
e.g. https://github.com/RustCrypto/crypto-bigint/blob/v0.2.9/Cargo.toml doesn't contain resolver feature

**Comment by WadeBarnes** [comment]
This issue has been resolved via this PR; https://github.com/hyperledger/indy-sdk/pull/2470

Any PRs affected by this issue will need to rebase their changes onto `2d2140f06369ecdb037f0f275df2862a917d64a3` (latest at the time of writing) or newer in order to have Jenkins use the fixed pipeline version.
