### ISSUE TITLE
Unable to install libindy in ubuntu 18.04

### ISSUE THREAD

**Issue by ShubhankerB** [hyperledger/indy-sdk#2476]
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 68DB5E88
sudo add-apt-repository "deb https://repo.sovrin.org/sdk/deb xenial stable"
sudo apt-get update
sudo apt-get install -y libindy -> Raising error that package not found
sudo apt-get install -y indy-cli -> Raising error that package not found

**Comment by TheseusDeus** [comment]
the tutorial says to use _bionic _ on 18.04, but I cant seem to get that working either.
sudo add-apt-repository "deb https://repo.sovrin.org/sdk/deb xenial stable"  -> sudo add-apt-repository "deb https://repo.sovrin.org/sdk/deb _bionic_ stable"

**Comment by WadeBarnes** [comment]
Which tutorial/instructions are you both following?

**Comment by TheseusDeus** [comment]
Dont know if it's an issue or not, but tried to follow the tutorial for ubuntu 18.04 LTS
https://github.com/hyperledger/indy-sdk#ubuntu-based-distributions-ubuntu-1604-and-1804

**Comment by TheseusDeus** [comment]
I have tried all release channels and they all produce the same error:

> W:` Skipping acquire of configured file 'release/binary-amd64/Packages' as repository 'https://repo.sovrin.org/sdk/deb bionic InRelease' doesn't have the component 'release' (component misspelt in sources.list?)

>W: Skipping acquire of configured file 'release/i18n/Translation-en' as repository 'https://repo.sovrin.org/sdk/deb bionic InRelease' doesn't have the component 'release' (component misspelt in sources.list?)

>W: Skipping acquire of configured file 'release/cnf/Commands-amd64' as repository 'https://repo.sovrin.org/sdk/deb bionic InRelease' doesn't have the component 'release' (component misspelt in sources.list?)

**Comment by WadeBarnes** [comment]
This works (Dockerfile), and installs the stable release of `libindy 1.16.0-bionic` as expected:
```
FROM ubuntu:18.04

RUN apt-get update -y && apt-get install -y \
    gnupg \
    ca-certificates

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CE7709D068DB5E88
RUN echo "deb https://repo.sovrin.org/sdk/deb bionic stable" >> /etc/apt/sources.list
RUN apt-get update -y && apt-get install -y \
    libindy
```

**Comment by genaris** [comment]
I've recently experienced this issue when building a docker image in a new computer setup (i.e. no previous docker cache). It seems that it was complaining for certificate validity:

```bash
Err:5 https://repo.sovrin.org/sdk/deb bionic Release
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 3.17.126.236 443]
```
Installing `ca-certificates` package before adding sovrin repo (as in @WadeBarnes Dockerfile) was key to solve this problem.

**Comment by edbkei** [comment]
is there any other key?

ubuntu@eduardoito-bionic:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic
ubuntu@eduardoito-bionic:~$ cat Dockerfile
FROM ubuntu:18.04

RUN apt-get update -y && apt-get install -y \
    gnupg \
    ca-certificates

RUN apt-key adv --keyserver keyserver.ubuntu.com:80 --recv-keys CE7709D068DB5E88
RUN echo "deb https://repo.sovrin.org/sdk/deb bionic stable" >> /etc/apt/sources.list
RUN apt-get update -y && apt-get install -y \
    libindy
ubuntu@eduardoito-bionic:~$ docker build ./
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&target=&ulimits=null&version=1": dial unix /var/run/docker.sock: connect: permission denied
ubuntu@eduardoito-bionic:~$ sudo docker build ./
Sending build context to Docker daemon  19.97kB
Step 1/5 : FROM ubuntu:18.04
 ---> f5cbed4244ba
Step 2/5 : RUN apt-get update -y && apt-get install -y     gnupg     ca-certificates
 ---> Using cache
 ---> 7df744ce49d8
Step 3/5 : RUN apt-key adv --keyserver keyserver.ubuntu.com:80 --recv-keys CE7709D068DB5E88
 ---> Running in c6736359dd9f
Warning: apt-key output should not be parsed (stdout is not a terminal)
Executing: /tmp/apt-key-gpghome.DrwZiFGoaO/gpg.1.sh --keyserver keyserver.ubuntu.com:80 --recv-keys CE7709D068DB5E88
gpg: keyserver receive failed: No keyserver available
The command '/bin/sh -c apt-key adv --keyserver keyserver.ubuntu.com:80 --recv-keys CE7709D068DB5E88' returned a non-zero code: 2
ubuntu@eduardoito-bionic:~$

**Comment by WadeBarnes** [comment]
@edbkei, That is the correct key.  I just ran the docker build on my machine and it worked without error.

**Comment by edbkei** [comment]
In another way, the key works.

ubuntu@eduardoito-bionic:~$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CE7709D068DB5E88
Executing: /tmp/apt-key-gpghome.0rNYjJjmgU/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys CE7709D068DB5E88
gpg: key CE7709D068DB5E88: "Sovrin-Repo-Master (Master key for repo.sovring.org) <repo@sovrin.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1

But when adding repository:

ubuntu@eduardoito-bionic:~$ sudo add-apt-repository "deb https://repo.sovrin.org/sdk/deb (xenial|bionic) {release channel}"
Hit:1 https://download.docker.com/linux/ubuntu bionic InRelease
Hit:2 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:3 http://nova.clouds.archive.ubuntu.com/ubuntu bionic InRelease
Ign:4 https://repo.sovrin.org/sdk/deb (xenial|bionic) InRelease
Hit:5 http://nova.clouds.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:6 https://repo.sovrin.org/sdk/deb xenial InRelease
Hit:7 http://nova.clouds.archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:8 https://repo.sovrin.org/sdk/deb bionic InRelease
Err:9 https://repo.sovrin.org/sdk/deb (xenial|bionic) Release
  404  Not Found [IP: 3.17.126.236 443]
Reading package lists... Done
E: The repository 'https://repo.sovrin.org/sdk/deb (xenial|bionic) Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Perhaps, it is a syntax error, that I don´t know (but it is the command reference at https://github.com/hyperledger/indy-sdk#ubuntu-based-distributions-ubuntu-1604-and-1804) about Release file not found (??)

because, we see that INDY-SDK is somewhere in:
https://repo.sovrin.org/sdk/deb/

**Comment by WadeBarnes** [comment]
This is your issue `deb https://repo.sovrin.org/sdk/deb (xenial|bionic) {release channel}`.

With that line you nee to pick one or the other and specify the `release channel`.  Such as`deb https://repo.sovrin.org/sdk/deb bionic stable`

**Comment by edbkei** [comment]
OK, thanks.

**Comment by edbkei** [comment]
Apparentlly, I got the original error. Sorry for disturbing you.

ubuntu@eduardoito-bionic:~$ sudo apt-get install -y libindy
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libindy : Depends: libsodium18 but it is not installable
E: Unable to correct problems, you have held broken packages.

Then, I´ve done some searching. And, I found that: libsodium version is here:
https://download.libsodium.org/libsodium/releases/

And, I´ve not tested yet, but I found the following instruction at:
https://lists.hyperledger.org/g/indy/topic/indy_node_on_ubuntu_18_04/27326643?p=

Perhaps the solution is something like below (but not sure yet):
cd /tmp && \
  curl https://download.libsodium.org/libsodium/releases/libsodium-1.0.18.tar.gz | tar -xz && \
  cd /tmp/libsodium-1.0.18 && \
  ./configure && \
  make && \
  make install && \
  rm -rf /tmp/libsodium-1.0.18

**Comment by edbkei** [comment]
-

**Comment by WadeBarnes** [comment]
@edbkei, Are you saying that installing `libindy` using this method (https://github.com/hyperledger/indy-sdk/issues/2476#issuecomment-1029043832) does not work for you?  It works for me consistently without error.

**Comment by edbkei** [comment]
Yes, that´s right. I am using a clean Ubuntu 18.04 from private cloud. I have another Ubuntu 18.04 in VB, that´s worser, I am not able to update with basic apt-get. But, if possible to compile libsodium, it would be OK. At the moment, I am still evaluating. Indeed, I would not need anything about this, I am looking for genesis file containing different number of nodes. I was told that if we increase the number of nodes (beyond the default 4), the performance increases. With 4 nodes, the performance is poor.  Then, my idea is to increase the number of nodes and INDY-SDK is the only option.

**Comment by WadeBarnes** [comment]
If you follow the steps exactly (adding `sudo` as needed) what errors do you encounter?

Also, is the purpose of this exercise for you to simply install the `indy-cli` in order to interact with a node pool (indy-node network) you've setup?  If so an easier option would be to use the containerized `indy-cli` available in `von-network`; https://github.com/bcgov/von-network/blob/main/docs/Indy-CLI.md.  The containerized `indy-cli` in `von-network` also has built-in tools for generating the genesis files for new networks.

Documentation for creating a new indy-node network can be found here; https://github.com/hyperledger/indy-node/blob/master/docs/source/NewNetwork/NewNetwork.md

**Comment by edbkei** [comment]
yes, sudo helped. And, now, it looks good. Glad to receive your references, very precious. Thanks.

**Comment by pSchlarb** [comment]
@edbkei 
Your Problem with uninstallable packages is known.... 
> ubuntu@eduardoito-bionic:~$ sudo apt-get install -y libindy Reading package lists... Done Building dependency tree Reading state information... Done Some packages could not be installed. This may mean that you have requested an impossible situation or if you are using the unstable distribution that some required packages have not yet been created or been moved out of Incoming. The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies: libindy : Depends: libsodium18 but it is not installable E: Unable to correct problems, you have held broken packages.

Indy node /plenum depend on fixed versions of packages, but since there are newer version of that packages in the official repos apt is complaining.

Chaining the cmd together like `sudo apt install indy-plenum=1.13.0~dev175 python3-libnacl=1.6.1 python3-sortedcontainers=1.5.7` works.

Further information can be found here [here](https://unix.stackexchange.com/questions/350192/apt-get-not-properly-resolving-a-dependency-on-a-fixed-version-in-a-debian-ubunt)
>
>The apt resolver does not consider the possibility that you might want to install something that is not the most recent available version of a package in a given target release; Debian just doesn't support installing anything but the most up to date version of a package for your system.
>
>    If you're using different repositories for each version of a (set of) package(s), then you can use pinning to prefer a given origin, or give them a different codename and use apt's -t option to select the target release. Otherwise it's just not possible.


Will close this issue.
Feel free to reopen, if the problem still exists.

**Comment by edbkei** [comment]
First of all, I´m using Ubuntu 18.04, but also I have Ubuntu 20.04. 

Unfortunately, there are more dependency problems.

As for your recommendation:
ubuntu@eduardoito-bionic:~/rocksdb$ sudo apt install indy-plenum=1.13.0~dev175 python3-libnacl=1.6.1 python3-sortedcontainers=1.5.7
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Version '1.13.0~dev175' for 'indy-plenum' was not found

As recommended by https://libraries.io/pypi/indy-plenum:
pip3 install indy-plenum==1.13.0.dev8
:::
Failed building wheel for python-rocksdb
:::
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-hylyicpw/python-rocksdb/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-yjrfbyr3-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-hylyicpw/python-rocksdb/

NOTE: Apparently, python-rocksdb missing. Then, according to reference: https://python-rocksdb.readthedocs.io/en/latest/installation.html, Compilation is possible, but it fails at:
pip3 install git+git://github.com/twmht/python-rocksdb.git#egg=python-rocksdb
with:
ubuntu@eduardoito-bionic:~/rocksdb$ sudo apt install indy-plenum=1.13.0~dev175 python3-libnacl=1.6.1 python3-sortedcontainers=1.5.7
Reading package lists... Done
Building dependency tree
Reading state information... Done

and

E: Version '1.13.0~dev175' for 'indy-plenum' was not found
ubuntu@eduardoito-bionic:~/rocksdb$ pip3 install git+git://github.com/twmht/python-rocksdb.git#egg=python-rocksdb
Collecting python-rocksdb from git+git://github.com/twmht/python-rocksdb.git#egg=python-rocksdb
  Cloning git://github.com/twmht/python-rocksdb.git to /tmp/pip-build-0b8_rujn/python-rocksdb
fatal: remote error:
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
Command "git clone -q git://github.com/twmht/python-rocksdb.git /tmp/pip-build-0b8_rujn/python-rocksdb" failed with error code 128 in None

**Comment by pSchlarb** [comment]
I am not sure why you get the error that the plenum package is not available...
Running  the following under the indy- node 20.04 gitpod image (which is derived from a ubuntu20.04 image) finds the package. It is installable when the other dependend packages are also selected with the version as stated in my last comment. 
Maybe some errors in the apt sources?

```
gitpod /workspace/indy-node (GHARefactoring) $ sudo apt install indy-plenum=1.13.0~dev175
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 indy-plenum : Depends: python3-libnacl (= 1.6.1) but 1.7.1-1 is to be installed
               Depends: python3-sortedcontainers (= 1.5.7) but 2.1.0-2 is to be installed
               Depends: python3-ujson (= 1.33) but 1.35-4build1 is to be installed
E: Unable to correct problems, you have held broken packages.
gitpod /workspace/indy-node (GHARefactoring) $ cat /etc/apt/sources.list
# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb http://archive.ubuntu.com/ubuntu/ focal main restricted
# deb-src http://archive.ubuntu.com/ubuntu/ focal main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://archive.ubuntu.com/ubuntu/ focal-updates main restricted
# deb-src http://archive.ubuntu.com/ubuntu/ focal-updates main restricted

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
deb http://archive.ubuntu.com/ubuntu/ focal universe
# deb-src http://archive.ubuntu.com/ubuntu/ focal universe
deb http://archive.ubuntu.com/ubuntu/ focal-updates universe
# deb-src http://archive.ubuntu.com/ubuntu/ focal-updates universe

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team, and may not be under a free licence. Please satisfy yourself as to
## your rights to use the software. Also, please note that software in
## multiverse WILL NOT receive any review or updates from the Ubuntu
## security team.
deb http://archive.ubuntu.com/ubuntu/ focal multiverse
# deb-src http://archive.ubuntu.com/ubuntu/ focal multiverse
deb http://archive.ubuntu.com/ubuntu/ focal-updates multiverse
# deb-src http://archive.ubuntu.com/ubuntu/ focal-updates multiverse

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
deb http://archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse
# deb-src http://archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse

## Uncomment the following two lines to add software from Canonical's
## 'partner' repository.
## This software is not part of Ubuntu, but is offered by Canonical and the
## respective vendors as a service to Ubuntu users.
# deb http://archive.canonical.com/ubuntu focal partner
# deb-src http://archive.canonical.com/ubuntu focal partner

deb http://security.ubuntu.com/ubuntu/ focal-security main restricted
# deb-src http://security.ubuntu.com/ubuntu/ focal-security main restricted
deb http://security.ubuntu.com/ubuntu/ focal-security universe
# deb-src http://security.ubuntu.com/ubuntu/ focal-security universe
deb http://security.ubuntu.com/ubuntu/ focal-security multiverse
# deb-src http://security.ubuntu.com/ubuntu/ focal-security multiverse
deb https://hyperledger.jfrog.io/artifactory/indy focal dev
# deb-src https://hyperledger.jfrog.io/artifactory/indy focal dev
deb http://security.ubuntu.com/ubuntu bionic-security main
# deb-src http://security.ubuntu.com/ubuntu bionic-security main
deb https://repo.sovrin.org/deb bionic master
# deb-src https://repo.sovrin.org/deb bionic master
deb https://repo.sovrin.org/sdk/deb bionic master
# deb-src https://repo.sovrin.org/sdk/deb bionic master
```

**Comment by pSchlarb** [comment]
Will close this issue, since it seems to be stalled.

**Comment by edbkei** [comment]
sudo apt install indy-plenum=1.13.0~dev175
Reading package lists... Done
Building dependency tree
Reading state information... Done

E: Version '1.13.0~dev175' for 'indy-plenum' was not found

This happens with Ubuntu 18.04 and 20.04, still.

**Comment by pSchlarb** [comment]
@edbkei 
I am sorry but i am unable to recreate your problem. 
Starting with a clean Gitpod docker image (which is based on ubuntu20.04), i am able to find the package **AFTER** adding the repositories.

```
gitpod ~ $ history
    2  sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 9692C00E657DDE61
    3  sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CE7709D068DB5E88
    4  sudo add-apt-repository 'deb  https://hyperledger.jfrog.io/artifactory/indy focal dev' &&     sudo add-apt-repository 'deb http://security.ubuntu.com/ubuntu bionic-security main' &&     sudo add-apt-repository 'deb https://repo.sovrin.org/deb bionic master'  &&     sudo add-apt-repository 'deb https://repo.sovrin.org/sdk/deb bionic master'
    5  sudo apt install indy-plenum=1.13.0~dev175
    6  history
```
[Sure apt is complaining about the fixed versions](https://github.com/hyperledger/indy-sdk/issues/2476#issuecomment-1108306605)

Please double check your apt-sources list. 

But it is installable after specifying all the versions:
`sudo apt install indy-plenum=1.13.0~dev175 python3-libnacl=1.6.1 python3-sortedcontainers=1.5.7 python3-ujson=1.33 python3-pyzmq=18.1.0`

**Comment by edbkei** [comment]
This´s worked in my Google Cloud VM, Ubuntu 20.04. Thanks. 

FYI,  sudo apt install indy-plenum=1.13.0~dev175 really not works

This is my APT list:
grep -r --include '*.list' '^deb ' /etc/apt/ | sed -re 's/^\/etc\/apt\/sources\.list((\.d\/)?|(:)?)//' -e 's/(.*\.list):/\[\1\] /' -e 's/deb http:\/\/ppa.launchpad.net\/(.*?)\/ubuntu .*/ppa:\1/'
deb http://us-central1.gce.archive.ubuntu.com/ubuntu/ focal main restricted
deb http://us-central1.gce.archive.ubuntu.com/ubuntu/ focal-updates main restricted
deb http://us-central1.gce.archive.ubuntu.com/ubuntu/ focal universe
deb http://us-central1.gce.archive.ubuntu.com/ubuntu/ focal-updates universe
deb http://us-central1.gce.archive.ubuntu.com/ubuntu/ focal multiverse
deb http://us-central1.gce.archive.ubuntu.com/ubuntu/ focal-updates multiverse
deb http://us-central1.gce.archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse
deb http://security.ubuntu.com/ubuntu focal-security main restricted
deb http://security.ubuntu.com/ubuntu focal-security universe
deb http://security.ubuntu.com/ubuntu focal-security multiverse
deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
deb https://hyperledger.jfrog.io/artifactory/indy focal dev
deb http://security.ubuntu.com/ubuntu bionic-security main
deb https://repo.sovrin.org/deb bionic master
deb https://repo.sovrin.org/sdk/deb bionic master
[nodesource.list] deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_17.x focal main
[docker.list] deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu   focal stable
[mongodb-org-5.0.list] deb [arch=amd64,arm64] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse
[deadsnakes-ubuntu-ppa-focal.list] ppa:deadsnakes/ppa

**Comment by pSchlarb** [comment]
Since the main issue here has been resolved (installation problems with libindy) i will close this issue.

@edbkei It seems your problem is more connected to indy-node / indy-plenum and the installation of a new node and not the indy-sdk. I would urge you to look in their repositories and open an issue there if you can't find answers.
