### ISSUE TITLE
 Build docker with master image fail docker build -f indy-pool.dockerfile -t indy_pool . 

### ISSUE THREAD

**Issue by vaibhavhpatil12345** [hyperledger/indy-sdk#2479]
docker build -f indy-pool.dockerfile -t indy_pool . 

https://raw.githubusercontent.com/hyperledger-archives/indy-agent/master/nodejs/indy-pool.dockerfile

#9 7.518 Building dependency tree...
#9 7.625 Reading state information...
#9 7.641 E: Unable to locate package python3-pyzmq
#9 7.641 E: Unable to locate package indy-plenum
#9 7.641 E: Unable to locate package indy-node
#9 7.641 E: Unable to locate package python3-indy-crypto
#9 7.641 E: Unable to locate package libindy-crypto
#9 7.641 E: Unable to locate package python3-orderedset
#9 7.641 E: Version '5.4.3' for 'python3-psutil' was not found
#9 7.641 E: Unable to locate package python3-pympler
------
executor failed running [/bin/sh -c apt-get update -y && apt-get install -y         python3-pyzmq=${python3_pyzmq_ver}         indy-plenum=${indy_plenum_ver}         indy-node=${indy_node_ver}         python3-indy-crypto=${python3_indy_crypto_ver}         libindy-crypto=${indy_crypto_ver}         python3-orderedset=${python3_orderedset_ver}         python3-psutil=${python3_psutil_ver}         python3-pympler=${python3_pympler_ver}         vim]: exit code: 100
ayanworks@ayanworkss-MacBook-Air ci %

**Comment by WadeBarnes** [comment]
The referenced dockerfile is in an archived repository the has not been maintained for a while.

If you want to spin up an indy-node pool for test purposes, may I recommend; https://github.com/bcgov/von-network

**Comment by vaibhavhpatil12345** [comment]
https://github.com/bcgov/von-network works for me closing this ticket thanks

**Comment by Swhite215** [comment]
Two of my colleagues just ran into this same issue. Should the official instructions to use the docker image to run a local pool be updated?
