### ISSUE TITLE
Realpath command not found

### ISSUE THREAD

**Issue by mgkarakaya** [hyperledger/indy-sdk#2491]
++ realpath /tmp/android_build/toolchains/darwin/x86/bin/i686-linux-android-ar
android.build.sh: line 42: realpath: command not found
++ realpath /tmp/android_build/toolchains/darwin/x86/bin/i686-linux-android-clang
android.build.sh: line 42: realpath: command not found

cargo config file doesn't get correct ar and linker path, so couldn't compile ursa.

**Comment by WadeBarnes** [comment]
@mgkarakaya, would you be able to provide the steps to reproduce this issue and details on where you're seeing this error?
