### ISSUE TITLE
How do I add an age to my did

### ISSUE THREAD

**Issue by altEr1125** [hyperledger/indy-sdk#2498]
I use this command to add an age to my did -- “ledger schema name=<name-value> version=<version-value> attr_names=<attr_names-value> [source_payment_address=<source_payment_address-value>] [fee=<fee-value>] [fees_inputs=<source-1,..,source-n>] [fees_outputs=(<recipient-1>,<amount>),..,(<recipient-n>,<amount>)] [extra=<extra>] [sign=<true or false>]  [send=<true or false>] [endorser=<endorser did>]”

But I got this error：
“Transaction author agreement Acceptance Mechanism isn't set.”

I tried using this command to solve：
“ ledger txn-acceptance-mechanisms aml={"Click Agreement":"some description"} version=1”

But I got this error：
“Transaction has been rejected: Not enough TRUSTEE signatures”

I don't know what I should do anymore, I have searched a lot of information but still no solution.
I'm guessing it might be a wrong parameter in the command.As you can see, I am just learning to use this project and I hope you can help me with this.

**Comment by altEr1125** [comment]
<img width="930" alt="image" src="https://user-images.githubusercontent.com/75016675/161983580-807fdae9-8a57-4434-b433-610037641a5a.png">
like this

**Comment by WadeBarnes** [comment]
It's the TAA acceptance workflow you want to follow; https://github.com/hyperledger/indy-sdk/blob/master/docs/how-tos/transaction-author-agreement.md#taa-acceptance-workflow.

When using the `indy-cli` you may find it easier to use the containerized `indy-cli` included with `von-network`; https://github.com/bcgov/von-network/blob/main/docs/Indy-CLI.md

The most common acceptance mechanism when using the `indy-cli` is "for_session" as described here; https://github.com/bcgov/von-network/blob/main/docs/Indy-CLI.md#open-an-interactive-indy-cli-session

**Comment by altEr1125** [comment]
> Since you are new to all this, you should join Hyperledger Discord where you can ask questions about this and other related projects;https://lists.hyperledger.org/g/media-entertainment-sig/message/263
> 
> I would also recommend having a look at https://github.com/Hyperledger/aries-cloudagent-python and once you join Hyperledger Discord have a look at the pinned messages on the `#aries` channel for links to other resources and courses. Aries builds on the `indy-sdk` and abstracts many of the complexities making it easier for you to get started with building applications.

Thank you very much, I solved this problem using von-network and it is indeed easier!
I have joined the Hyperledger Discord and look forward to learning more later
