### ISSUE TITLE
sovrin_create_and_store_my_did doesn't support creation of seed based CID

### ISSUE THREAD

**Issue by vimmerru** [hyperledger/indy-sdk#25]
If DID isn't provided sovrin_create_and_store_my_did always use first 16 bytes of generated verkey as DID, but identities in pool ledger generated by init scripts use full verkey as DID.

I now that CID is deprecated, but in the current state, it is hard to use libsovrin with private pool. Current integration tests use verkey instead of did as rough workaround and it can confuse potential library users.

I suggest adding support of optional "cid" attribute to did_json param. If it is true full generated verkey will be used as DID if there is no explicit DID.

**Comment by dhh1128** [comment]
Okay, sounds fine.

**Comment by peacekeeper** [comment]
In the code comments I found this line:

> /// "cid": string, (optional; if not set then false is used;)

Is this really a JSON string as the comment says, or a boolean, i.e. will the parameter be:

> "cid": "false"

or

> "cid": false

Guess it should be the latter and the comment should be changed?

**Comment by vimmerru** [comment]
the cid parameter type is boolean. So we will change the comment. Thank you for this finding.

**Comment by vimmerru** [comment]
Now sovrin_create_and_store_my_did supports optional "cid" field in did_json param that allows a creation of DID from seed as CID. As result, this issue seems solved.
