### ISSUE TITLE
error: indy error [REQNACK] Issue

### ISSUE THREAD

**Issue by KISMIDEV** [hyperledger/indy-sdk#2506]
I'm using indy-sdk version 1.16.0 just fine. However, the recent Issuer's Schema registration (_**indy.signAndSubmitRequest**_) and the operation of calling Credential Def on the Ledger (_**indy.parseGetCredDefResponse**_) keep getting errors.

In _**indy.signAndSubmitRequest**_, op: 'REQNACK' , reason: 'client request invalid: could not authenticate, verkey for SK8di1uRdeC8e1zMksoHUz cannot be found' error occurs, and _**indy.parseGetCredDefResponse**_ causes LedgerNotFound error.

Any feedback on what could be causing this issue would be appreciated.

**Comment by WadeBarnes** [comment]
@ianco, Any thoughts?

**Comment by ianco** [comment]
> client request invalid: could not authenticate, verkey for SK8di1uRdeC8e1zMksoHUz cannot be found

... implies that the DID is missing from the wallet or ledger (verkey can't be found so can't authenticate the transaction)

**Comment by KISMIDEV** [comment]
> > client request invalid: could not authenticate, verkey for SK8di1uRdeC8e1zMksoHUz cannot be found
> 
> ... implies that the DID is missing from the wallet or ledger (verkey can't be found so can't authenticate the transaction)
Our infrastructure environment uses kubernetes.
And data related to indy is safely managed and backed up through pv and pvc.
So there is no risk of losing the wallet or ledger of DID.
It's a running service, isn't there a good solution?

**Comment by ianco** [comment]
I haven't seen this error before, so I'm just guessing about the cause.  If you're getting this error then there is some issue with your environment, and I'm guessing it's a missing DID somewhere (either on the ledger or in the wallet).  I don't know much about your application or setup so other than trying to track down the error I'm not sure what advice I can provide.

**Comment by KISMIDEV** [comment]
@ianco 

Thank you
