### ISSUE TITLE
Upgrade to a later NodeJS version

### ISSUE THREAD

**Issue by johnwen84** [hyperledger/indy-sdk#2535]
Hi, we use jsonld-signatures to support W3C credentials. The latest jsonld-signatures (10.0.0) requests NodeJS 14 or later. We need to upgrade to it to solve some security issues. But this conflicts with the indy-sdk NodeJS requirement of NodeJS 12. Since NodeJS 12 is over 3 years old and reached end of life for support. I wonder if indy-sdk will upgrade to support a later NodeJS version soon.
Thanks

**Comment by blu3beri** [comment]
If you are talking about the `indy-sdk` released on npm, it supports higher node versions. I use it daily with node 16 and 17 and they work without issues.
