### ISSUE TITLE
anoncreds.GenerateNonceAsync() function returns System.EntryPointNotFoundException in dotnet

### ISSUE THREAD

**Issue by erenakyildiz-code** [hyperledger/indy-sdk#2547]
Hello Hyperledger Indy team,

Currently I am using dotnet wrapper for my project, and when I try to run anoncreds.GenerateNonceAsync().

I am getting this error:

System.EntryPointNotFoundException: 'Unable to find an entry point named 'indy_generate_nonce' in DLL 'indy'.'

Everything else I have used in anoncreds works fine.

Sorry if my explanation is not enough, this is the first issue I have created.

**Comment by KangUkG** [comment]
Me, either! So I create random 80bit binary number. I want to know Indy team's answer...
