### ISSUE TITLE
Getting Started Client install  - indy-node

### ISSUE THREAD

**Issue by vinomaster** [hyperledger/indy-sdk#255]
Following the instructions [here](https://github.com/hyperledger/indy-node/blob/master/docs/Sovrin_Running_Locally.md), experiencing issues executing the following command:

```
pip3 install -U --no-cache-dir sovrin-client
```

which yields

```
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DBENCHMARK_ENABLED=1 -Icharm/core/utilities/ -Icharm/core/benchmark/ -I/usr/include/python3.5m -c charm/core/math/pairing/pairingmodule.c -o build/temp.linux-x86_64-3.5/charm/core/math/pairing/pairingmodule.o
In file included from charm/core/math/pairing/pairingmodule.c:30:0:
charm/core/math/pairing/pairingmodule.h:37:17: fatal error: gmp.h: No such file or directory
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;file='/tmp/pip-build-t8l864o5/Charm-Crypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(file).read().replace('\r\n', '\n'), file, 'exec'))" install --record /tmp/pip-5oj3fh_2-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-t8l864o5/Charm-Crypto/
root@619ca0be244e:/#
```
This issue is discussed [here](https://sovrin.discoursehosting.net/t/sovrin-getting-started-guide/15/10) BUT I have tried the Xcode approach with the latest version of Mac OS including repairing the crypto.h file for openssl and was unable to fix the issue reported above. My mac os ver is 10.12.6.

I then decided to do a simple docker container for Ubuntu with a docker attach so that I can hit my local sovrin cluster of 4 validator nodes. Unfortunately, I get the same error.

In both cases the issue is with the gmp.h file.

Is there a better crypto package that works and is more dev-ops friendly across platforms?

Any suggestions?

Am I following the wrong getting started instructions?

**Comment by asararatnakar** [comment]
I hit this issue too

```
Icharm/core/utilities/ -Icharm/core/benchmark/ -I/usr/include/python3.5m -c charm/core/math/pairing/pairingmodule.c -o build/temp.linux-x86_64-3.5/charm/core/math/pairing/pairingmodule.o
    In file included from charm/core/math/pairing/pairingmodule.c:30:0:
    charm/core/math/pairing/pairingmodule.h:37:17: fatal error: gmp.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ijh5x0ue/Charm-Crypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-tg8twk2k-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-ijh5x0ue/Charm-Crypto/
```

**Comment by phptek** [comment]
I have just hit the same issue (btw, I had to guess to use `sovrin-client` when the instructions read as `indy-client`.

Ubuntu Xenial using Vagrant LXC.

**Comment by ashcherbakov** [comment]
Both sovrin-client and indy-client are deprecated ones. 
Please find up to date documentation there: https://github.com/hyperledger/indy-node/blob/master/README.md.
Please note that the client in indy-node repo (started by `indy` command) is going to be deprecated soon.
Please use indy-sdk based CLI: https://github.com/hyperledger/indy-sdk/tree/master/cli

**Comment by benjsmi** [comment]
https://docs.google.com/document/d/1Da6adGCoRhCntQwPQPzz1H1dJRHAmgyyDi0k01ncvuw/edit# shows instructions to install a package named `sovrin`. Probably no longer the case.
