### ISSUE TITLE
Ubuntu 18.04 -apt repository does not have a release file

### ISSUE THREAD

**Issue by demos2022** [hyperledger/indy-sdk#2554]
Hi, I am trying to run this demo locally in my Ubuntu system (version 18.04) and upon running the below command
sudo add-apt-repository "deb https://repo.sovrin.org/sdk/deb bionic stable"
, it throws an error. Attached is the error screenshot. Please assist. This seems to be similar to issue - https://github.com/hyperledger/indy-sdk/issues/2476. The issue is closed but I cannot seem to find a solution in that.
![Error](https://user-images.githubusercontent.com/109317376/185523714-4eea8044-6e9a-4b29-be75-53531376f477.PNG)

**Comment by stockschlaeger** [comment]
what device are you using?

**Comment by WadeBarnes** [comment]
A couple items to note for anyone having this issue.
- The signing keys for the repo have changed.  Therefore you need to download the new public keys.
- There is no repository `https://repo.sovrin.org/sdk/deb bionic Release`.  If this is in your repo list you should remove it.

Working Docker Example:
```
FROM ubuntu:18.04
RUN apt-get update -y && apt-get install -y \
    gnupg \
    software-properties-common \
    apt-transport-https \
    ca-certificates

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CE7709D068DB5E88
RUN add-apt-repository "deb https://repo.sovrin.org/sdk/deb bionic stable"
RUN apt-get update -y && apt-get install -y \
    libindy
```
