### ISSUE TITLE
Rust error E0512

### ISSUE THREAD

**Issue by teodem** [hyperledger/indy-sdk#2556]
Hi guys, 

i was following the installation process described in the [documentation](https://aries.js.org/guides/tutorials/postgres-database-nodejs/macos) for Postgres. I've installed Rust and Cargo correctly. 
If i run: `cargo build --release` inside indy-sdk/experimental/plugins/postgres_storage, i get: 
```
error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
   --> /Users/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.11/src/sockaddr.rs:156:9
    |
156 |         mem::transmute::<SocketAddrV4, sockaddr_in>(v4);
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: source type: `SocketAddrV4` (48 bits)
    = note: target type: `sockaddr_in` (128 bits)

For more information about this error, try `rustc --explain E0512`.
error: could not compile `socket2` due to previous error
```
Any idea how can i solve this? Thank you!

**Comment by darapich92** [comment]
@teodem I also face the same problem. Did you solve it?

**Comment by miroslav-inc** [comment]
Any update on this? :/
