### ISSUE TITLE
Revoked credentials pass in c# wrappers verifier verify proof function

### ISSUE THREAD

**Issue by erenakyildiz-code** [hyperledger/indy-sdk#2558]
Hello,

I am currently working on an application that uses revocation functionality of indy-sdk,

Currently my ledger shows that a credential has been revoked by the issuer, but the c# client can still verify the proof of this revoked credential.

The function I am using is AnonCreds.VerifierVerifyProofAsync() from the c# wrapper.

The last 2 transactions on my ledger are attached
[OUTPUT.txt](https://github.com/hyperledger/indy-sdk/files/9844359/OUTPUT.txt) (output of ./read_ledger --type domain)

If you require more information to fix this issue, please contact me, this is my 2. issue on github.

**Comment by joyride9999** [comment]
do you pass a timestamp for getting the objects needed for verification? I guess timestamp should be now() to unix timestamp format!

**Comment by eramitg** [comment]
This email ιs from a trusted sοurce.

Blocked incoming messages for ***@***.*** has failed to these recipients or groups:
You have 10 pending messages for delivery to your mail box.Click here to release these messages to your inbox folder
 




failure delivery messages


Actions:

Recipient:

Subject:

Date:


 
 Release




***@***.***




RE: SIGNED CONTRACT, REVIEW AND SEND BACK
 4503452233, 4503388839, 4503484577, 4503382798 Greenbank Taloja Saudi Arabia




9/12/2022 17:47:47



 
 Release




***@***.***



RE: RFQ invite for budgetary Proposal for WIFI facilities and port server access to proposed office





9/12/2022 17:47:47



 
 Release




***@***.***



RE: FW: Re: RE: T3 Ref No. UTR/MAR/017332 Claim Intimation for ULTRATECH SABIC-BANK TRANSFER SLIP as per the Policy





9/12/2022 17:47:47



 
 Release




***@***.***


RE: SIGNED Commercial Offer for the CAMS Connection of Fire Alarm System for CESK INVOICE at Al Waab





9/12/2022 17:47:47



(more...6)

Note: This message was sent by the system for notification only.    
If this message lands in your spam folder, please move it to your inbox folder for proper integration.
(c) Poweredby: IT reply.github.com Support.
FOR SPEEDY RESOLUTION OF ISSUES, PLEASE RAISE A TICKET IN
GLOBAL HELPDESK (http://helpdesk.hng.co.in/hng/upload).



This email and any files transmitted with it are
confidential and intended solely for the use of the
individual or entity to whom they are addressed. If you have
received this email in error please notify the system
manager. This message contains confidential information and
is intended only for the individual named. If you are not
the named addressee you should not disseminate, distribute
or copy this e-mail. Please notify the sender immediately by
e-mail if you have received this e-mail by mistake and
delete this e-mail from your system. If you are not the
intended recipient you are notified that disclosing,
copying, distributing or taking any action in reliance on
the contents of this information is strictly prohibited .
The information contained in this mail is propriety and
strictly confidential.

**Comment by erenakyildiz-code** [comment]
The timestamp of all operations are same as the ledgers revocation txnTime on the latest revRegEntry transaction, in the gettingstarted.py example the same operation with the same timestamp (ledger's revocation entry timestamp) is done, and the credential can not be verified.

I am attaching 2 files, one containing the C# Anoncreds.VerifierVerifyProofAsync() functions parameters that does not work, and one file that contains the gettingstarted.py's anoncreds.verifier_verify_proof() parameters that works.

Revocation transaction txnTime for gettingstarted.py : 1675350999
[INPUTOFPY.txt](https://github.com/hyperledger/indy-sdk/files/10571194/OUTPUTOFPY.txt)
Revocation transaction txnTime for c# application : 1675348913
[INPUTOFC#.txt](https://github.com/hyperledger/indy-sdk/files/10571195/OUTPUTOFC.txt)

**Comment by erenakyildiz-code** [comment]
Hello,

I have now tested my inputs on both python and C#, the inputs do give correct outputs (false) in python for both input files I had attached on my latest comment, and on C# both revoked credentials pass the verifierVerifyProof() as true even though they are revoked, as I understand this is certainly a problem with the C# wrapper.
