### ISSUE TITLE
Problem installing the Indy SDK in Ubuntu 22.04

### ISSUE THREAD

**Issue by santidediego** [hyperledger/indy-sdk#2562]
Error raises when doing `sudo apt-get install -y libnullpay` or any other library.

Error message:`Depends: libssl1.1 but it is not installable`

Any solution/workaround?

**Comment by santidediego** [comment]
Seems like something is wrong with my current libssl version, solved as detailed in [this comment](https://github.com/dotnet/sdk/issues/24759#issuecomment-1214190207).

Just for curiosity, is there any other way to install it without downgrading the libssl?

Anyway you can mark it as closed.

**Comment by manolaz** [comment]
Fixing by install with ROOT SUDO

sudo -i


wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
