### ISSUE TITLE
Please address these license issues

### ISSUE THREAD

**Issue by ryjones** [hyperledger/indy-sdk#2579]
[Please address these license issues](https://lfscanning.org/reports/hyperledger/indy-2022-12-31-3e8ff9d3-d56e-4899-ba4e-2fbb7310e581.html)

https://github.com/hyperledger/indy-sdk/blob/ae9f8a252bb99e8b80c6d34c6c985fd95abfadef/vcx/libvcx/build_scripts/android/openssl/make_openssl.sh#L4-L5

https://github.com/hyperledger/indy-sdk/blob/ae9f8a252bb99e8b80c6d34c6c985fd95abfadef/Specs/libzmq/4.2.3/libzmq.podspec.json#L7-L9

https://github.com/hyperledger/indy-sdk/blob/ae9f8a252bb99e8b80c6d34c6c985fd95abfadef/Specs/libzmq-pw/4.2.2/libzmq-pw.podspec.json#L7-L10

**Comment by jeffcshapiro** [comment]
The main concern here is the LGPLv3 license.  The OpenSSL license should not be a concern.

**Comment by swcurran** [comment]
I can answer the questions posed.  I don’t know what is required to “address these license issues”.

AFAIK — libzmq is used within the Indy SDK, and libzmq-pw seems to be a fork of libzmq created by Evernym.   From the codebase I found this about libzmq-pw: "ZeroMQ fork with PairwiseCurveCP support”. I don’t see any documentation in the Evernym repo.

I don’t know if it matters, but it looks to me like libzmq is downloaded as binary artifact in builds - e.g. a dll.

**Comment by ryjones** [comment]
From the linked report:

**Priority: High**
This metadata file indicates it is for components under LGPL-3.0, libzmq / libzmq-pw. Are these two components used by indy, and/or is their code contained anywhere in the repo?

**Comment by swcurran** [comment]
I saw that. It asks a question and I’ve tried to answer it, but it doesn’t say what to do given the answer I provided.

**Comment by ryjones** [comment]
Gotcha. @jeffcshapiro ?

**Comment by jeffcshapiro** [comment]
Sorry, the question should have been worded as a recommendation:  If LGPL licensed code is in your repo as source code it can contaminate the codebase.  If it is only used as a binary (DLL) then it is OK.

**Comment by swcurran** [comment]
@brentzundel — can you please confirm that libzmq is only used in binary form in this repo?  Same applies for libzmq-pw.

Thanks

**Comment by brentzundel** [comment]
To my understanding, libzmq and libzmq-pw are only used as binaries.

**Comment by swcurran** [comment]
Thanks. @jeffcshapiro — now that we know that libzmq and -pw are binary only, what action do we need to take?

**Comment by ryjones** [comment]
I _think_ @jeffcshapiro makes note of it in his tool and closes the issue

**Comment by jeffcshapiro** [comment]
Issue resolved, no license conflict - ZeroMQ used as binaries only

**Comment by jeffcshapiro** [comment]
looks like I can't close the issue, please close
