### ISSUE TITLE
Unable to Submit Cred Def Request to VON Ledger

### ISSUE THREAD

**Issue by Swhite215** [hyperledger/indy-sdk#2582]
I get the below error when submiting a credential definition request to a VON ledger as an Issuer Trust Anchor. I am able to successfully submit a schema request to the ledger as the Issuer.

ERROR
`Schema Def response:
{'identifier': 'Th7MpTaRZVRYnPiabds81Y',
 'op': 'REQNACK',
 'reason': 'client request invalid: '
           "InvalidClientRequest('Th7MpTaRZVRYnPiabds81Y', "
           "1677710265550217000, 'validation error "
           '[ClientClaimDefSubmitOperation]: cannot be smaller than 1 '
           "(ref=0)')",
 'reqId': 1677710265550217000}`

**Comment by swcurran** [comment]
Can you share the CredDef txn you submited, including the creddef?  I suspect that one of the data values is invalid, and you are getting an obscure error as a result.

**Comment by Swhite215** [comment]
`Credential definition: 
{'id': 'LmfLaUo9aUjfCcbrVnnhYB:3:CL:LmfLaUo9aUjfCcbrVnnhYB:2:vbc:1.0:TAG1',
 'schemaId': 'LmfLaUo9aUjfCcbrVnnhYB:2:vbc:1.0',
 'tag': 'TAG1',
 'type': 'CL',
 'value': {'primary': {'n': '83629154032880622385855668597280636937736271967919622113434485288503320891572431510666473334380377806562823403162146088855643828853816519602470995470837666517271973173538925041007034806432116899889014546623809802247427192668917926614918817444558164271417688610995304633366924213357590001385739710074947145546397633091506623667461046128389844761437972898436405785356592676754653971863652864173089279507337927770621051406658505977944198717363624464666277726947253652653838341867332742868913335040300202142662897018530871708800105667996325003560393476617467980563533916432838939765487754033259445298858194237428590359897',
                       'r': {'color': '45502821683921860699782311524828249657671714339594071843600296391559876918093748164749678297540337424206860900635224040556030003165968632585389539191886009826648488595369303464405452889429119233363547760888923597225656798913566675340916942309003137679115618767298101558918444099041914511744190189562552216782325319511080342257479601574967074183170124733042746982139544927987383568459671156657740178989635611456689352642983487111015671486775914741278929580930302749999274610848228326790856203308700608185719560321945899619676947010734032581593349784200894906836953766687431193107414278141969660933982945290660430294361',
                             'country_of_origin': '51109094475024304877418141959127412328834830397564047506056570767574900424704662500750340813160234595766077925516248022243489035624458113942479671021716207310783381934073475843569846958570741202040812860547719703657420870615196726925775284672073025742292074831132153408761805096078131931729418138139150643815357015668083475738619447425124916401719299783288972565108311227080848912845496192548087590927369538780520346351028692345134381161434531683014112300590921339748848383179015695154583427737998284268294852853378477241078931831744269460616213760822494096650937295797136919004807703229393579726648815764404696937437',
                             'date_of_production': '35241146781522743549632338005612663660466848637746334928515110796860744764171974835466522453090477879902772520247021725247482123286479258918763333053371791606475514854176246161747624007390340050370158933198640747650417594725070489101934754098136685068305368099875472098491434002573581316524987035890748788992278687661882225368706180368051902672383493757845492088816795008565486304462000165334274854854859929610508694504206145672342547510115918304814702234179860654599327874317004864155351028793921606629044937650374341104672921006109717288976365715697839549179713869570173108092806655947496980729529214016983277053277',
                             'engine_code': '40996843106002864213255958829658737955192146102615709232495404618880327950556711480181993589958913641288773448422014027248180095277929830959340133077866383160457585719586588779539681642392400088380827821986004529844141113501314767673609312752960805668796460315197187162973040757590541306235783162613810145712218493847429160658747747832596477803959442757710405676000159204721701613863046758265752558879923103672363482956163240732542298652017429355042334121404826535759496929657450584485330004175798955065345188894125763476607962939412600575003043862280040729713640056175350946533868711776285785697752623275230223556063',
                             'engine_serial_number': '70002906040597738221916013655385455547539679143510707152029033130953514573749579210645574496613854615391352671800837746198860553141461610777826366893326825536718296639912998469891314763995027644631681323308735117387733821029443478341747447026892616274346387799515718855263873239002384524969307781015427812895068336815008795715575869432623236333681941748143382262702181710448746592248795863445441044728166474804389952017806417609284880534714133692364237916238468281677840394005917752653312164188428777738599597723626963866637294740759183168401175804006333121137459832218449371254216870803994048723441753445308015856542',
                             'fuel_type': '47172903698366838858783637411417897439351549509646921785914076437531092991008265558808293019105882599567089091665695935442884669799961631285648474792374943296900858562223736156244577844710403240488839940478843379738294459831159508678816467434978569989680088503829446245012994182529130366491543161792796416099718988100154272789889252127508789196446423044989159454053902476380676182577936514777884771756090358324955025119454607985858066759373052158118047495367673790098569168100331788830554648821508769470038207844485354184474635643977097146710587957330700425452143099701903493964609799696447710164802423146557542291767',
                             'manufacturer': '45460242112979216652862168100125941003804142630326552956504677273638138569336482910134436163697657366644328657728938975126124163618689045126094594302042449396879053302325912411235810699505954834542671544654487978082048916909458244645832535849518715359509287822579397020065185827618300956929620541396838967054074540694580402755820517484587578877424663775829888024769673881980714135383134274546377756879895547843481954618594621702521315987815911359727202565500645404812115143736424273418798195663309017528129154806076593146539581756965814853027556026086936635762606225548198905150266471079720981412650289452349839596791',
                             'master_secret': '32775381470115452871201623798656711667498369741376939230499331463770223233975113350368945714662145346462038694019994709691349397026662963353744305418367324859541178564972379457343163296398034724046537024652292124796006543907968487611249067280043058915989249144481532163870540326990734171297158070303470664842158863128192497247001447060982917404711354362690971184729147453355850366148519321366103071122047558322105181448761947727154529926781642280759693350700739094787828464825153940678480496582150658517961585993302064668443901168643319132625556214099122908034737018541922080276811813500911764557420951456401084942158',
                             'model': '82594327140468152644165290212327556596706350899845336037218353757326571645686282735667256496415302771475198120749686678695735567894079465246555915129526693878806504643404730674364265270530175969846808211028367279065380886055318262742413223464150048767666704064734634538332518118855229121264155757995430028456402954173334890709952629333393654439344393027292764740184039623204155618047162003086334377426378343722553617546604739052438021693466401455171353343994802547919124835739491115562160114379732761632528158801632295245718082498583225476943280179237728260623238053322607703430187816347940273292837807331272943429563',
                             'model_year': '72492171992949395530434635826103955551704386810502886396883227262590021458089658474674295024218845160779451456515770288772699809645000432149142704235019291837104946076726964542791665929318221749538407379094843664794348317626577391610044021127103771468057340475994932665966911827294356312306331426040699212763373511965291075843944806448393281589471281533639581832573879217274438809121415468019391940029150887950865074139655940254007952551082812223245897655929920447441316428377768112108530965140047494877083028199848078606250766053113271946811216573299355364753978250789685170652060037622134213828532885313919428123139',
                             'previous_vbc': '38835704265766875217787560602302194976262697258410268582367874436099617106225658385790893078201644775269108659354883264590276284236444586654474089649643559308349081364905111434420818500420031770692125220732212763496185859341296221364285395271439793216815731275842536394844032984575933415518893165585685477582816682190718444111466407329502436764079823503030103308046336548156833736149560582606266125619971557732303732703247137144473941213587075353622610521195971683535154777830809538788010643511527412327361879939387438831224206998603519357780678435166268313680448554323788473769902153511923974563857777755980354280281',
                             'signature_algorithm': '40594581239700729608533000317414451208271147353116481679235347514073677505367796806010249323546988220771985694460896851787945161299498632167870707049130530677430249658206963334169546628270252712699646599220691444336530963750943498941769697429839531082409536237838735571457263290845726265135195677306575113522868337952478731245447763955438750831034292014654699192487440261165549971625500498112959692162095947298422575011177075690405110954672590523241369757428934359219493745210278249578356601684278127994657224664619471605946273274982668555090184132134137479341982253955881055514028383633721060745562363834126100459812',
                             'transmission_serial_number': '41739304427081172017413136108714213324344359917327123548354393972508748351340685585999420139451824582274357268012119646536085398011325073351677828019971376050375690654075114752750703250076622522222323336246451550626585418388070175124871397618115379920445151212130540444343046399842955904414658043262316393842425109807600998592733340272877957769425691082949600938923755475352232498488437235966852562561175303999752656303120081560133399885595363921994138396312349094101055267144473996978356284878321537410242249962708923120199844920222768814272631736554931732254116777039264975528594556736181702392732563282009946112493',
                             'trim_type': '64358999858394294058410817701732448813206933118863062597978975271666795892467331271392177206297349585004832402224209209465975204918382854979833198642817516776684588313247416881602856806620599801199422790674780332075080137062911226655490858863157085244418468677387909794696721222546572909622430712899534974463908012498156541876108379719028009025292095765703495907755295536377469962998825361699471945116902899292254551477065293585033290108499525367185950704271151025616037068374336551966880941755187877087064053393300056632112812522228726589173005583455780807313709624574044893742284228988091608510301225814501041284486',
                             'uvi': '24069395383485452213485620396628757631683523480798261249623568162872218899689377125126238352466957425424111309226111449600673639421998695511348347696065824509771764128615476391165820741304735912772464591176826766526602991025347069406712305238475628032794885825377804997928993000208630240309020534103395325131527315121545114235189686439543847228369256477898045763415795648556991712905565853288364233352892876120511975734245302090063069080904689159419815719243790923603734365528968074257043793083596288765408830015767384267246643223003491075199594116396580476595322640139132072199524618010558500035574138268271880632717',
                             'vin': '26891717911718477338842831620183237512283908622448974024906561311157213969512739593887840876450751772215372823457067700634761206708149495777969169517094819439861279848007746540223981666398079003074848825664773945712081192087594801799673808165629096114185665407118452277259600090217718546310546518059123812922935610966661113501684566638390501533036850407518501278898986852358030569085758831370226308546623017381879539297309371292091627631273974901176815369782217996112697675232359500042808989405461154370543879360981101202530442363496343027304724063867890124296405671799533748342061116823057482881380232842970105371042'},
                       'rctxt': '1220730591565157012051173404500740960810050074973742054153906866904832010440235909655779595642544596335750697212755883703599834673702274322212307336224733362540994541582631378291899854928563265723751956559854892515318265744098166515712498024515233702160312634065949921878721333853927091847592086635599239907948877599263394972119583680164193943205297282286048136575804625906877177024617434205850224870187588521846513805205433657377424707788116491776976760200574173277162418704242065119125331455868875301504570720681997321645770984810817669913347204365585846634228400644088120297573710416547595950429587457083564773277',
                       's': '2291636872998711471429680528216713647652508786461308004254688732223286410780591042089596881607523237328801704705786856949724599757435302149713022601321617124315858667180802628140729903134410612998268457141333581166790374041566027917233431304631449363052179655716158996294156028654674363394311700181912767766392890144025041913907809341744933914191405565863527469474009533519131703262891846517357832318372909532033312957687935416126327105643772271058034669842939040859665454643921840583998363751919152996943348980979625652163045051849397227197361626666221633205006476758102094522000905046162636811605621044362769819095',
                       'z': '19782878170673944752435781644292418560043697821743326377048750984414221418853864145286816163963294111031812497146592874638785307795657816905488785884037196066467398390939095539892459558090358094628400093373449040774467510361875148930927546322848894615381878707458626320209278024804517805934922568643959784217673817618973110237209279002061058595559087239293296188472947087439373903921629093161783689293371766287821983296702512235712406651409959842155951301436460279192718651378877594161943207159954414988336421597121037568665498436957984786571739189809256265947615315187698723128644197608756591091872121645716367067549'},
           'revocation': {'g': '1 '
                               '12F27BFEF6713914459A33E15BB547A80FC55E2CDCDBA560BA3A851C3197C9C3 '
                               '1 '
                               '1B84D8060CCF741BDA99A9AE3FC651D543F87DDC701A46B4AA61D6A6511AD5BC '
                               '2 '
                               '095E45DDF417D05FB10933FFC63D474548B7FFFF7888802F07FFFFFF7D07A8A8',
                          'g_dash': '1 '
                                    '1B642D14523BFB1943B8778C45188DCF4EB6C6BF066F076F524FC1D3CFD05A06 '
                                    '1 '
                                    '048C90568CA9F7D6956706FA87372E85AEA1BBFFADC590F9ED41A8601C1CA601 '
                                    '1 '
                                    '03831EBCC45269E90E26E3B4FF18FFC0D5720FCF924050B0CC675B83BB7EB3F8 '
                                    '1 '
                                    '1B768D11E7BDB0138E14C07AA6FD38183B5C9A921B21AC480907C310012F0651 '
                                    '2 '
                                    '095E45DDF417D05FB10933FFC63D474548B7FFFF7888802F07FFFFFF7D07A8A8 '
                                    '1 '
                                    '0000000000000000000000000000000000000000000000000000000000000000',
                          'h': '1 '
                               '006CB8164C3B9818CCFE6F570F8DFC5E65E5F341177227F289850873430422EE '
                               '1 '
                               '0654DB12476D56742586542AC54C48D8CE6372E0AAF3F0DC8090E03D00BEA246 '
                               '2 '
                               '095E45DDF417D05FB10933FFC63D474548B7FFFF7888802F07FFFFFF7D07A8A8',
                          'h0': '1 '
                                '147AADB17F29C3CCCFA97A6AD6AB1EB5D0B0D5871B0A0DD44ED21465BBB47CC3 '
                                '1 '
                                '2271C0E90F35A9F360D46A268BCA9B5CFB07A20DE2891F00E860A8AB865762AA '
                                '2 '
                                '095E45DDF417D05FB10933FFC63D474548B7FFFF7888802F07FFFFFF7D07A8A8',
                          'h1': '1 '
                                '22F6EFB2A88DA2804C9F0E480D60CB807E671C41D66D8F1851B7E85D3DF11E1C '
                                '1 '
                                '0016B82726A3CAA32E80F9CE772C3C689296C3AE654C9283B4FBAFF963AB05BE '
                                '2 '
                                '095E45DDF417D05FB10933FFC63D474548B7FFFF7888802F07FFFFFF7D07A8A8',
                          'h2': '1 '
                                '11A020F486D1C8D88B3FD0C56E54811E199FE429E83E6DBA0BF20AF009057A03 '
                                '1 '
                                '21752B19B8CBE2B0685AFA576578CA49013560A62D9201FFF62B1FFF3341F592 '
                                '2 '
                                '095E45DDF417D05FB10933FFC63D474548B7FFFF7888802F07FFFFFF7D07A8A8',
                          'h_cap': '1 '
                                   '0E8EAF5E6D8AD73AF2904D8D73029572D25A52511C48CE3DFC77F9AD439A6F31 '
                                   '1 '
                                   '202136D166EE0FBC6170D5D1DC469965A66919492779B2045D93C8C34618A06E '
                                   '1 '
                                   '0873C7326C9A7D1B8BAD26D7595EDECE4D79D84FC69D815DFBD42CF7CAE25CC3 '
                                   '1 '
                                   '0DF2906B219C2F6B52D7C672AD0DDC3BA06548E28FE34F0AB7EFD594A48D52E4 '
                                   '2 '
                                   '095E45DDF417D05FB10933FFC63D474548B7FFFF7888802F07FFFFFF7D07A8A8 '
                                   '1 '
                                   '0000000000000000000000000000000000000000000000000000000000000000',
                          'htilde': '1 '
                                    '20E88CE34740034455A8A788BCAA5075313A6901F051C3F3CAEDA9EA3AFF94FE '
                                    '1 '
                                    '20374AF82220EAEA7F361C27B8FBCF9430B91D8E76DC2C8D3576C7CAD6686637 '
                                    '2 '
                                    '095E45DDF417D05FB10933FFC63D474548B7FFFF7888802F07FFFFFF7D07A8A8',
                          'pk': '1 '
                                '1E8AF30ADF8937E062EC847FB14C5D6DE69FF4BA4080C67577ED7116706B9522 '
                                '1 '
                                '19E352B0CFF7D789A8C6FB7B3A342B35A999B0E6DEE4BC75414B93EFC1F4CB45 '
                                '2 '
                                '095E45DDF417D05FB10933FFC63D474548B7FFFF7888802F07FFFFFF7D07A8A8',
                          'u': '1 '
                               '23C55A959552908944B99A6570BD480E578826B4326BEC2B4CCF4C58FC19B917 '
                               '1 '
                               '16CC41D1876DD1DEBDF3F433AA302B1F6C17125E77222904CFDA4E0B5C15432A '
                               '1 '
                               '0B808D85BC4C4033A0F6C813E9ACBF333FA70D0DB1963256F0343EE2EDCE6A2B '
                               '1 '
                               '04B20165BE3DA985C7EB82DBF39940EBC8427BCADC7CFEAA7E065271CBF88DFC '
                               '2 '
                               '095E45DDF417D05FB10933FFC63D474548B7FFFF7888802F07FFFFFF7D07A8A8 '
                               '1 '
                               '0000000000000000000000000000000000000000000000000000000000000000',
                          'y': '1 '
                               '134B2F42E837C7D0EA1EAD10FB782924D10836E40782B27E0CBDB50649D36945 '
                               '1 '
                               '18D87EC51BB2C932C660C16ED6F69C5E3E7A844A0B8C905AD5928851EAEDE479 '
                               '1 '
                               '1CC78D110A3D7C88F0CEF0A33CA35E612F97CC5A3796C0C7CA8CEA5FEF3A0A48 '
                               '1 '
                               '23592AEEBD48E1975866E02CDD457DF33E369DDEC1E3FA43FBBC8D8ECD846215 '
                               '2 '
                               '095E45DDF417D05FB10933FFC63D474548B7FFFF7888802F07FFFFFF7D07A8A8 '
                               '1 '
                               '0000000000000000000000000000000000000000000000000000000000000000'}},
 'ver': '1.0'}`

`Schema Def request: 
{'identifier': 'LmfLaUo9aUjfCcbrVnnhYB',
 'operation': {'data': {'primary': {'n': '83629154032880622385855668597280636937736271967919622113434485288503320891572431510666473334380377806562823403162146088855643828853816519602470995470837666517271973173538925041007034806432116899889014546623809802247427192668917926614918817444558164271417688610995304633366924213357590001385739710074947145546397633091506623667461046128389844761437972898436405785356592676754653971863652864173089279507337927770621051406658505977944198717363624464666277726947253652653838341867332742868913335040300202142662897018530871708800105667996325003560393476617467980563533916432838939765487754033259445298858194237428590359897',
                                    'r': {'color': '45502821683921860699782311524828249657671714339594071843600296391559876918093748164749678297540337424206860900635224040556030003165968632585389539191886009826648488595369303464405452889429119233363547760888923597225656798913566675340916942309003137679115618767298101558918444099041914511744190189562552216782325319511080342257479601574967074183170124733042746982139544927987383568459671156657740178989635611456689352642983487111015671486775914741278929580930302749999274610848228326790856203308700608185719560321945899619676947010734032581593349784200894906836953766687431193107414278141969660933982945290660430294361',
                                          'country_of_origin': '51109094475024304877418141959127412328834830397564047506056570767574900424704662500750340813160234595766077925516248022243489035624458113942479671021716207310783381934073475843569846958570741202040812860547719703657420870615196726925775284672073025742292074831132153408761805096078131931729418138139150643815357015668083475738619447425124916401719299783288972565108311227080848912845496192548087590927369538780520346351028692345134381161434531683014112300590921339748848383179015695154583427737998284268294852853378477241078931831744269460616213760822494096650937295797136919004807703229393579726648815764404696937437',
                                          'date_of_production': '35241146781522743549632338005612663660466848637746334928515110796860744764171974835466522453090477879902772520247021725247482123286479258918763333053371791606475514854176246161747624007390340050370158933198640747650417594725070489101934754098136685068305368099875472098491434002573581316524987035890748788992278687661882225368706180368051902672383493757845492088816795008565486304462000165334274854854859929610508694504206145672342547510115918304814702234179860654599327874317004864155351028793921606629044937650374341104672921006109717288976365715697839549179713869570173108092806655947496980729529214016983277053277',
                                          'engine_code': '40996843106002864213255958829658737955192146102615709232495404618880327950556711480181993589958913641288773448422014027248180095277929830959340133077866383160457585719586588779539681642392400088380827821986004529844141113501314767673609312752960805668796460315197187162973040757590541306235783162613810145712218493847429160658747747832596477803959442757710405676000159204721701613863046758265752558879923103672363482956163240732542298652017429355042334121404826535759496929657450584485330004175798955065345188894125763476607962939412600575003043862280040729713640056175350946533868711776285785697752623275230223556063',
                                          'engine_serial_number': '70002906040597738221916013655385455547539679143510707152029033130953514573749579210645574496613854615391352671800837746198860553141461610777826366893326825536718296639912998469891314763995027644631681323308735117387733821029443478341747447026892616274346387799515718855263873239002384524969307781015427812895068336815008795715575869432623236333681941748143382262702181710448746592248795863445441044728166474804389952017806417609284880534714133692364237916238468281677840394005917752653312164188428777738599597723626963866637294740759183168401175804006333121137459832218449371254216870803994048723441753445308015856542',
                                          'fuel_type': '47172903698366838858783637411417897439351549509646921785914076437531092991008265558808293019105882599567089091665695935442884669799961631285648474792374943296900858562223736156244577844710403240488839940478843379738294459831159508678816467434978569989680088503829446245012994182529130366491543161792796416099718988100154272789889252127508789196446423044989159454053902476380676182577936514777884771756090358324955025119454607985858066759373052158118047495367673790098569168100331788830554648821508769470038207844485354184474635643977097146710587957330700425452143099701903493964609799696447710164802423146557542291767',
                                          'manufacturer': '45460242112979216652862168100125941003804142630326552956504677273638138569336482910134436163697657366644328657728938975126124163618689045126094594302042449396879053302325912411235810699505954834542671544654487978082048916909458244645832535849518715359509287822579397020065185827618300956929620541396838967054074540694580402755820517484587578877424663775829888024769673881980714135383134274546377756879895547843481954618594621702521315987815911359727202565500645404812115143736424273418798195663309017528129154806076593146539581756965814853027556026086936635762606225548198905150266471079720981412650289452349839596791',
                                          'master_secret': '32775381470115452871201623798656711667498369741376939230499331463770223233975113350368945714662145346462038694019994709691349397026662963353744305418367324859541178564972379457343163296398034724046537024652292124796006543907968487611249067280043058915989249144481532163870540326990734171297158070303470664842158863128192497247001447060982917404711354362690971184729147453355850366148519321366103071122047558322105181448761947727154529926781642280759693350700739094787828464825153940678480496582150658517961585993302064668443901168643319132625556214099122908034737018541922080276811813500911764557420951456401084942158',
                                          'model': '82594327140468152644165290212327556596706350899845336037218353757326571645686282735667256496415302771475198120749686678695735567894079465246555915129526693878806504643404730674364265270530175969846808211028367279065380886055318262742413223464150048767666704064734634538332518118855229121264155757995430028456402954173334890709952629333393654439344393027292764740184039623204155618047162003086334377426378343722553617546604739052438021693466401455171353343994802547919124835739491115562160114379732761632528158801632295245718082498583225476943280179237728260623238053322607703430187816347940273292837807331272943429563',
                                          'model_year': '72492171992949395530434635826103955551704386810502886396883227262590021458089658474674295024218845160779451456515770288772699809645000432149142704235019291837104946076726964542791665929318221749538407379094843664794348317626577391610044021127103771468057340475994932665966911827294356312306331426040699212763373511965291075843944806448393281589471281533639581832573879217274438809121415468019391940029150887950865074139655940254007952551082812223245897655929920447441316428377768112108530965140047494877083028199848078606250766053113271946811216573299355364753978250789685170652060037622134213828532885313919428123139',
                                          'previous_vbc': '38835704265766875217787560602302194976262697258410268582367874436099617106225658385790893078201644775269108659354883264590276284236444586654474089649643559308349081364905111434420818500420031770692125220732212763496185859341296221364285395271439793216815731275842536394844032984575933415518893165585685477582816682190718444111466407329502436764079823503030103308046336548156833736149560582606266125619971557732303732703247137144473941213587075353622610521195971683535154777830809538788010643511527412327361879939387438831224206998603519357780678435166268313680448554323788473769902153511923974563857777755980354280281',
                                          'signature_algorithm': '40594581239700729608533000317414451208271147353116481679235347514073677505367796806010249323546988220771985694460896851787945161299498632167870707049130530677430249658206963334169546628270252712699646599220691444336530963750943498941769697429839531082409536237838735571457263290845726265135195677306575113522868337952478731245447763955438750831034292014654699192487440261165549971625500498112959692162095947298422575011177075690405110954672590523241369757428934359219493745210278249578356601684278127994657224664619471605946273274982668555090184132134137479341982253955881055514028383633721060745562363834126100459812',
                                          'transmission_serial_number': '41739304427081172017413136108714213324344359917327123548354393972508748351340685585999420139451824582274357268012119646536085398011325073351677828019971376050375690654075114752750703250076622522222323336246451550626585418388070175124871397618115379920445151212130540444343046399842955904414658043262316393842425109807600998592733340272877957769425691082949600938923755475352232498488437235966852562561175303999752656303120081560133399885595363921994138396312349094101055267144473996978356284878321537410242249962708923120199844920222768814272631736554931732254116777039264975528594556736181702392732563282009946112493',
                                          'trim_type': '64358999858394294058410817701732448813206933118863062597978975271666795892467331271392177206297349585004832402224209209465975204918382854979833198642817516776684588313247416881602856806620599801199422790674780332075080137062911226655490858863157085244418468677387909794696721222546572909622430712899534974463908012498156541876108379719028009025292095765703495907755295536377469962998825361699471945116902899292254551477065293585033290108499525367185950704271151025616037068374336551966880941755187877087064053393300056632112812522228726589173005583455780807313709624574044893742284228988091608510301225814501041284486',
                                          'uvi': '24069395383485452213485620396628757631683523480798261249623568162872218899689377125126238352466957425424111309226111449600673639421998695511348347696065824509771764128615476391165820741304735912772464591176826766526602991025347069406712305238475628032794885825377804997928993000208630240309020534103395325131527315121545114235189686439543847228369256477898045763415795648556991712905565853288364233352892876120511975734245302090063069080904689159419815719243790923603734365528968074257043793083596288765408830015767384267246643223003491075199594116396580476595322640139132072199524618010558500035574138268271880632717',
                                          'vin': '26891717911718477338842831620183237512283908622448974024906561311157213969512739593887840876450751772215372823457067700634761206708149495777969169517094819439861279848007746540223981666398079003074848825664773945712081192087594801799673808165629096114185665407118452277259600090217718546310546518059123812922935610966661113501684566638390501533036850407518501278898986852358030569085758831370226308546623017381879539297309371292091627631273974901176815369782217996112697675232359500042808989405461154370543879360981101202530442363496343027304724063867890124296405671799533748342061116823057482881380232842970105371042'},
                                    'rctxt': '1220730591565157012051173404500740960810050074973742054153906866904832010440235909655779595642544596335750697212755883703599834673702274322212307336224733362540994541582631378291899854928563265723751956559854892515318265744098166515712498024515233702160312634065949921878721333853927091847592086635599239907948877599263394972119583680164193943205297282286048136575804625906877177024617434205850224870187588521846513805205433657377424707788116491776976760200574173277162418704242065119125331455868875301504570720681997321645770984810817669913347204365585846634228400644088120297573710416547595950429587457083564773277',
                                    's': '2291636872998711471429680528216713647652508786461308004254688732223286410780591042089596881607523237328801704705786856949724599757435302149713022601321617124315858667180802628140729903134410612998268457141333581166790374041566027917233431304631449363052179655716158996294156028654674363394311700181912767766392890144025041913907809341744933914191405565863527469474009533519131703262891846517357832318372909532033312957687935416126327105643772271058034669842939040859665454643921840583998363751919152996943348980979625652163045051849397227197361626666221633205006476758102094522000905046162636811605621044362769819095',
                                    'z': '19782878170673944752435781644292418560043697821743326377048750984414221418853864145286816163963294111031812497146592874638785307795657816905488785884037196066467398390939095539892459558090358094628400093373449040774467510361875148930927546322848894615381878707458626320209278024804517805934922568643959784217673817618973110237209279002061058595559087239293296188472947087439373903921629093161783689293371766287821983296702512235712406651409959842155951301436460279192718651378877594161943207159954414988336421597121037568665498436957984786571739189809256265947615315187698723128644197608756591091872121645716367067549'},
                        'revocation': {'g': '1 '
                                            '12F27BFEF6713914459A33E15BB547A80FC55E2CDCDBA560BA3A851C3197C9C3 '
                                            '1 '
                                            '1B84D8060CCF741BDA99A9AE3FC651D543F87DDC701A46B4AA61D6A6511AD5BC '
                                            '2 '
                                            '095E45DDF417D05FB10933FFC63D474548B7FFFF7888802F07FFFFFF7D07A8A8',
                                       'g_dash': '1 '
                                                 '1B642D14523BFB1943B8778C45188DCF4EB6C6BF066F076F524FC1D3CFD05A06 '
                                                 '1 '
                                                 '048C90568CA9F7D6956706FA87372E85AEA1BBFFADC590F9ED41A8601C1CA601 '
                                                 '1 '
                                                 '03831EBCC45269E90E26E3B4FF18FFC0D5720FCF924050B0CC675B83BB7EB3F8 '
                                                 '1 '
                                                 '1B768D11E7BDB0138E14C07AA6FD38183B5C9A921B21AC480907C310012F0651 '
                                                 '2 '
                                                 '095E45DDF417D05FB10933FFC63D474548B7FFFF7888802F07FFFFFF7D07A8A8 '
                                                 '1 '
                                                 '0000000000000000000000000000000000000000000000000000000000000000',
                                       'h': '1 '
                                            '006CB8164C3B9818CCFE6F570F8DFC5E65E5F341177227F289850873430422EE '
                                            '1 '
                                            '0654DB12476D56742586542AC54C48D8CE6372E0AAF3F0DC8090E03D00BEA246 '
                                            '2 '
                                            '095E45DDF417D05FB10933FFC63D474548B7FFFF7888802F07FFFFFF7D07A8A8',
                                       'h0': '1 '
                                             '147AADB17F29C3CCCFA97A6AD6AB1EB5D0B0D5871B0A0DD44ED21465BBB47CC3 '
                                             '1 '
                                             '2271C0E90F35A9F360D46A268BCA9B5CFB07A20DE2891F00E860A8AB865762AA '
                                             '2 '
                                             '095E45DDF417D05FB10933FFC63D474548B7FFFF7888802F07FFFFFF7D07A8A8',
                                       'h1': '1 '
                                             '22F6EFB2A88DA2804C9F0E480D60CB807E671C41D66D8F1851B7E85D3DF11E1C '
                                             '1 '
                                             '0016B82726A3CAA32E80F9CE772C3C689296C3AE654C9283B4FBAFF963AB05BE '
                                             '2 '
                                             '095E45DDF417D05FB10933FFC63D474548B7FFFF7888802F07FFFFFF7D07A8A8',
                                       'h2': '1 '
                                             '11A020F486D1C8D88B3FD0C56E54811E199FE429E83E6DBA0BF20AF009057A03 '
                                             '1 '
                                             '21752B19B8CBE2B0685AFA576578CA49013560A62D9201FFF62B1FFF3341F592 '
                                             '2 '
                                             '095E45DDF417D05FB10933FFC63D474548B7FFFF7888802F07FFFFFF7D07A8A8',
                                       'h_cap': '1 '
                                                '0E8EAF5E6D8AD73AF2904D8D73029572D25A52511C48CE3DFC77F9AD439A6F31 '
                                                '1 '
                                                '202136D166EE0FBC6170D5D1DC469965A66919492779B2045D93C8C34618A06E '
                                                '1 '
                                                '0873C7326C9A7D1B8BAD26D7595EDECE4D79D84FC69D815DFBD42CF7CAE25CC3 '
                                                '1 '
                                                '0DF2906B219C2F6B52D7C672AD0DDC3BA06548E28FE34F0AB7EFD594A48D52E4 '
                                                '2 '
                                                '095E45DDF417D05FB10933FFC63D474548B7FFFF7888802F07FFFFFF7D07A8A8 '
                                                '1 '
                                                '0000000000000000000000000000000000000000000000000000000000000000',
                                       'htilde': '1 '
                                                 '20E88CE34740034455A8A788BCAA5075313A6901F051C3F3CAEDA9EA3AFF94FE '
                                                 '1 '
                                                 '20374AF82220EAEA7F361C27B8FBCF9430B91D8E76DC2C8D3576C7CAD6686637 '
                                                 '2 '
                                                 '095E45DDF417D05FB10933FFC63D474548B7FFFF7888802F07FFFFFF7D07A8A8',
                                       'pk': '1 '
                                             '1E8AF30ADF8937E062EC847FB14C5D6DE69FF4BA4080C67577ED7116706B9522 '
                                             '1 '
                                             '19E352B0CFF7D789A8C6FB7B3A342B35A999B0E6DEE4BC75414B93EFC1F4CB45 '
                                             '2 '
                                             '095E45DDF417D05FB10933FFC63D474548B7FFFF7888802F07FFFFFF7D07A8A8',
                                       'u': '1 '
                                            '23C55A959552908944B99A6570BD480E578826B4326BEC2B4CCF4C58FC19B917 '
                                            '1 '
                                            '16CC41D1876DD1DEBDF3F433AA302B1F6C17125E77222904CFDA4E0B5C15432A '
                                            '1 '
                                            '0B808D85BC4C4033A0F6C813E9ACBF333FA70D0DB1963256F0343EE2EDCE6A2B '
                                            '1 '
                                            '04B20165BE3DA985C7EB82DBF39940EBC8427BCADC7CFEAA7E065271CBF88DFC '
                                            '2 '
                                            '095E45DDF417D05FB10933FFC63D474548B7FFFF7888802F07FFFFFF7D07A8A8 '
                                            '1 '
                                            '0000000000000000000000000000000000000000000000000000000000000000',
                                       'y': '1 '
                                            '134B2F42E837C7D0EA1EAD10FB782924D10836E40782B27E0CBDB50649D36945 '
                                            '1 '
                                            '18D87EC51BB2C932C660C16ED6F69C5E3E7A844A0B8C905AD5928851EAEDE479 '
                                            '1 '
                                            '1CC78D110A3D7C88F0CEF0A33CA35E612F97CC5A3796C0C7CA8CEA5FEF3A0A48 '
                                            '1 '
                                            '23592AEEBD48E1975866E02CDD457DF33E369DDEC1E3FA43FBBC8D8ECD846215 '
                                            '2 '
                                            '095E45DDF417D05FB10933FFC63D474548B7FFFF7888802F07FFFFFF7D07A8A8 '
                                            '1 '
                                            '0000000000000000000000000000000000000000000000000000000000000000'}},
               'ref': 0,
               'signature_type': 'CL',
               'tag': 'TAG1',
               'type': '102'},
 'protocolVersion': 2,
 'reqId': 1677719266817988000}`

**Comment by swcurran** [comment]
Nothing obvious — sorry. I was thinking it might be related to “ver”, but AFAIK that looks right.  :-(

Not sure how to help.  I think it has to be something in your setup, but there is not much that can be done wrong here...

**Comment by Swhite215** [comment]
Okay, thank you for trying. I am going to switch to working with Aries directly and confirm I can complete this task through an agent. 

Side note, you did an excellent job with the Hyperledger Aries course. The material was well presented and I feel prepared to tackle building a solution with the technology. Respect.
