### ISSUE TITLE
Question on TPMs and Wallets

### ISSUE THREAD

**Issue by terilenard** [hyperledger/indy-sdk#2583]
Hello,

I am interested in researching how TPMs can be used as a pluggable storage together with an indy wallet. I observed that there is not a lot of material available on the internet so far, even in terms of research papers. I am aware of the API offered in indy, but besides this, it seems like no one tried it. Is anyone aware on a design/prototype that tries to accomplish this?

Thank you!
Best regards,
Teri.

**Comment by swcurran** [comment]
A likely better place to add this is in the Aries Askar repo/context (https://github.com/hyperledger/aries-askar) and in the Hyperledger Discord Aries channel — https://discord.gg/hyperledger. Askar is the successor to the `indy-wallet` part of the indy-sdk. The use of the indy-sdk is being phased out in favour of newer implementations — Askar, AnonCreds (https://github.com/hyperledger/anoncreds-rs — a ledger agnostic version of AnonCreds for Indy and other ledgers) and Indy VDR (https://github.com/hyperledger/indy-vdr — a new client interface for writing/resolving objects on Indy).

I know there has been some discussion with Askar about its use in conjunction with TPMs and I know that some folks have considered it enough to think it is feasible, but it has not been done.  It’s a great topic.

**Comment by terilenard** [comment]
Thank you @swcurran . Will continue with your links!

Teri.

**Comment by terilenard** [comment]
Moving discussion to discord and closing question because it is not relevant for the project.
