### ISSUE TITLE
problem not solved

### ISSUE THREAD

**Issue by Amitjatola** [hyperledger/indy-sdk#2589]
~$ sudo add-apt-repository "deb https://repo.sovrin.org/sdk/deb bionic stable"
Hit:1 http://security.ubuntu.com/ubuntu bionic-security InRelease             
Hit:2 http://us.archive.ubuntu.com/ubuntu bionic InRelease                    
Hit:3 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease            
Hit:4 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease          
Ign:5 https://repo.sovrin.org/sdk/deb (bionic) InRelease
Hit:6 https://repo.sovrin.org/sdk/deb bionic InRelease
Hit:7 https://repo.sovrin.org/sdk/deb xenial InRelease
Err:8 https://repo.sovrin.org/sdk/deb (bionic) Release
  404  Not Found [IP: 3.17.126.236 443]
Reading package lists... Done
E: The repository 'https://repo.sovrin.org/sdk/deb (bionic) Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

i followed the  steps that u(@WadeBarnes) said above but still issue is not solved

**Comment by WadeBarnes** [comment]
Can you run `apt list --upgradable` on your system and see if `libgnutls30` or the `ca-certificates` need to be updated?

**Comment by Amitjatola** [comment]
Hi
I need to make an edge device identification system using hyperledger Indy
but i am not able to find source to study about hyperledger Indy  or
example project can you help by providing any sources ?
