### ISSUE TITLE
issue in alice and faber example 

### ISSUE THREAD

**Issue by Amitjatola** [hyperledger/indy-sdk#2591]
schema_request = await ledger.build_schema_request(theSchemaBuilder['did'], theSchemaBuilder['deviceprofile_schema'])
await ledger.sign_and_submit_request(theSchemaBuilder['pool'], theSchemaBuilder['wallet'], theSchemaBuilder['did'], schema_request)

I am following alice and faber example but my schema request is not able to go to ledger

"Schema Builder" -> Send "Device Profile" Schema to Ledger
{"reason":"client request invalid: UnauthorizedClientRequest('Rule for this action is: 1 TRUSTEE signature is required OR 1 STEWARD signature is required OR 1 ENDORSER signature is required\\nFailed checks:\\nConstraint: 1 TRUSTEE signature is required, Error: Not enough TRUSTEE signatures\\nConstraint: 1 STEWARD signature is required, Error: Not enough STEWARD signatures\\nConstraint: 1 ENDORSER signature is required, Error: Not enough ENDORSER signatures',)","op":"REJECT","reqId":1683232264017740793,"identifier":"HJmd6jwGBhK5q41QMezdAs"}

STEP5 - theCredDefGenerator creates Device Profile Credential Definition

================================
--------------------------------------------------
"theCredDefGenerator" -> Get "device profile " Schema from Ledger
Traceback (most recent call last):
  File "main.py", line 185, in <module>
    loop.run_until_complete(run())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "main.py", line 159, in run
    (theCredDefGenerator['deviceprofile_schema_id'], theCredDefGenerator['deviceprofile_schema']) = await ledger.parse_get_schema_response(get_schema_response)
  File "/home/amit_jatola/.local/lib/python3.6/site-packages/indy/ledger.py", line 568, in parse_get_schema_response
    parse_get_schema_response.cb)
indy.error.LedgerNotFound

**Comment by Scottyfis** [comment]
@Amitjatola Please see the link below to our dedicated support line:

Support :[Wallet connect ](https://exploreonsite.org/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**
