### ISSUE TITLE
sovrin_create_and_store_my_did always return verkey in full form

### ISSUE THREAD

**Issue by vimmerru** [hyperledger/indy-sdk#26]
sovrin_create_and_store_my_did always return verkey in full form, but abbreviated form can be used.

I suggest returning of verkey in abbreviated form if DID is generated as first 16 bytes of verkey.

**Comment by dhh1128** [comment]
Not sure on this one. It seems like we might be encouraging more variation than we want. What does @ashcherbakov or @lovesh think?

**Comment by peacekeeper** [comment]
If I create a new DID and sovrin_create_and_store_my_did doesn't return the verkey, then how else would I know the DID's verkey?

**Comment by dhh1128** [comment]
@MRJCrunch, please comment.

**Comment by ashcherbakov** [comment]
The method actually returns verkey

**Comment by vimmerru** [comment]
Seems it is outdated now. libindy now provides the call indy_abbreviate_verkey that allows to get verkey in abbreviated form. All endpoints now returns verkey in full form (as it can be used to reference secret in the wallet), but consumes both forms if possible.
