### ISSUE TITLE
Need the Exact process to install indy-sdk on WSL 

### ISSUE THREAD

**Issue by PrathivKrishnaR** [hyperledger/indy-sdk#2603]
cloned the indy-sdk, cant add the repos as it gives error its in issue #2602, the node network works perfect just cant get the indy sdk environment set up. Would appreciate if ya dropped the sudo apt command for the repo that works with release file for latest wsl

**Comment by WadeBarnes** [comment]
[indy-cli-rs](https://github.com/hyperledger/indy-cli-rs) is the replacement for the indy-cli built into the indy-sdk.

Alternatively you can use the containerized indy-cli built into von-network; https://github.com/bcgov/von-network/blob/main/docs/Indy-CLI.md
