### ISSUE TITLE
Tried installing sdk in windows, got this error in cargo build

### ISSUE THREAD

**Issue by PrathivKrishnaR** [hyperledger/indy-sdk#2604]
error: failed to run custom build command for `zmq-sys v0.11.0`

Caused by:
  process didn't exit successfully: `C:\Users\HAI\indy-sdk\libindy\target\release\build\zmq-sys-9c063d24928041d5\build-script-main` (exit code: 101)

warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `openssl-sys v0.9.59`

Caused by:
  process didn't exit successfully: `C:\Users\HAI\indy-sdk\libindy\target\release\build\openssl-sys-63294e8bdf26359a\build-script-main` (exit code: 101)

note: 
i have openssl and rust installed as well.
have set path for all given in environment variables pointing to C:\Bin/x64

what do i gotta do to fix it

**Comment by PrathivKrishnaR** [comment]
@WadeBarnes am on aries right now after knowing its depecrated, i want to install libindy and indy-cli , i tried the sudo apt-add-repository "deb https://repo.sovrin.org/sdk/deb bionic master" -y and it gave out a lot of errors, how do i fix it or cud u give me an updated repo for latest ubuntu?

**Comment by WadeBarnes** [comment]
[indy-cli-rs](https://github.com/hyperledger/indy-cli-rs) is the replacement for the indy-cli built into the indy-sdk.

**Comment by WadeBarnes** [comment]
Alternatively you can use the containerized indy-cli built into von-network; https://github.com/bcgov/von-network/blob/main/docs/Indy-CLI.md
