### ISSUE TITLE
sovrin_store_their_did call has excess pk attribute in identity json

### ISSUE THREAD

**Issue by vimmerru** [hyperledger/indy-sdk#27]
sovrin_store_their_did call has excess pk attribute in identity json, but keys for encryption/decription are always can be computed from signkey/verkey.

Looks like it can confuse library user. I suggest removing of this param.

sovrin_encrypt and sovrin_decrypt method also looks excess as we plan to use encryption/decryption on transport protocol layer (CurveCP). It is hard to use these methods directly as NaCL encryption requires nonce and corresponded handshake procedure for safe nonce generation on both sides.

I suggest removing these methods from API.

**Comment by dhh1128** [comment]
I agree with removing the param.

On the sovrin_encrypt and sovrin_decrypt methods, I agree that the methods are unnecessary if we use CurveCP. However, I am not sure that all sovrin-oriented communications will take place over secure channels; perhaps people would like to use libsovrin to do secure comm with another libsovrin user over public email, for example. So I think it is still worth leaving the methods in.

**Comment by jovfer** [comment]
Removed in https://github.com/hyperledger/indy-sdk/pull/330
