### ISSUE TITLE
sovrin_sign and sovrin_verify_signature should support arbitrary byte array

### ISSUE THREAD

**Issue by peacekeeper** [hyperledger/indy-sdk#32]
Right now, `sovrin_sign` and `sovrin_verify_signature` can create/verify signatures for the JSON messages that are sent to the ledger. In these methods, a JSON message is serialized to a byte array using a custom algorithm that is not used outside of Indy/Sovrin ledger communication. Also, the signature is automatically inserted into the JSON message.

I think it would be very useful if those methods could be used more generically, to create/verify signatures on any arbitrary byte array supplied by the library user.

**Comment by vimmerru** [comment]
Personally, I agree with this issue. Looks like the current implementation of sovrin_sign and sovrin_verify_signature calls that only allows signing off messages to pool with very specific digest creation is some result of our internal misunderstanding. Also, it doesn't correspond to this calls docs.

@ashcherbakov 

Can you re-check this?

**Comment by vimmerru** [comment]
From another point of view

The main use case of sovrin_sign call is signing of transaction messages that were created with sovrin_build_*_request calls. It allows splitting of communication logic from private keys management for better security of real aplications. 

Ledger communication requires the creation of complex custom digests and injection of the signature field to original json messages. So we can't just easy make this calls generic wothout loosing of ability to sign ledger messages. Maybe we can add another call that is intended for the signing of generic messages.

@ashcherbakov 
@dhh1128 

What to you think about this?

**Comment by dhh1128** [comment]
An earlier version of the API had a sovrin_sign() function that could sign arbitrary messages. I'm not sure why we removed it, but I've always considered it a good idea.

**Comment by peacekeeper** [comment]
Closing this Github issue and creating JIRA issue instead: https://jira.hyperledger.org/browse/INDY-361

**Comment by dhh1128** [comment]
Moved again; this time to https://jira.hyperledger.org/browse/IS-158
