### ISSUE TITLE
RUST_TEST_THREADS=1 cargo test command fails on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by numical** [hyperledger/indy-sdk#462]
Hi - similar scenario to [issue 447](https://github.com/hyperledger/indy-sdk/issues/447) but different problem.
Running the [Setup Indy SDK build environment instructions](https://github.com/hyperledger/indy-sdk/blob/master/doc/ubuntu-build.md),
All OK (including `cargo build`) until step 'Run tests' `RUST_TEST_THREADS=1 cargo test`.  
Then error: `error: linking with 'cc' failed: exit code: 1`

I thought this might be similar to [issue 295](https://github.com/hyperledger/indy-sdk/issues/295) as my `libsodium` version was 1.0.8-5.  Upgraded `libsodium8` and `libsodium-dev` to 1.0.13.1 but this made no difference.

Environment detail:
* `uname -a`  :   `Linux hidalgo 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
* `rustc --version`  :   `rustc 1.22.1 (05e2e1c41 2017-11-22)`

What further info would help diagnose the issue?
Thanks!

**Comment by numical** [comment]
I have raised a [PR](https://github.com/hyperledger/indy-sdk/pull/463) with the fix that worked for me added to `ubuntu-build.md`

**Comment by eramitg** [comment]
just use sudo RUST_TEST_THREADS=1 cargo test commands in Ubuntu16.04 ,folks it's work, no need to update rust
