### ISSUE TITLE
Indy CLI doesn't work for file input.

### ISSUE THREAD

**Issue by dwjohnston** [hyperledger/indy-sdk#484]
[According to the documentation](https://github.com/hyperledger/indy-sdk/blob/master/cli/README.md) I can use the Indy CLI in batch mode with: 

```
indy-cli <path-to-text-file>
```

I'm running it like: 

```
indy /usr/myapp/setup.indy
```

And I get: 

```
Loading module /usr/local/lib/python3.5/dist-packages/config/config-crypto-example1.py
Module loaded.

Indy-CLI (c) 2017 Evernym, Inc.
Type 'help' for more information.
Running Indy 1.2.270


Running command: '/usr/myapp/setup.indy'...

Invalid command: '/usr/myapp/setup.indy'
```

A note about my setup - I'm essentially following the docker build instructions [here](https://gist.github.com/nuxibyte/208326d6f7910a4fe2089fa515855411) 

which uses the following dependencies: 

```

# Config apt
RUN add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu xenial main universe"
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 68DB5E88
RUN add-apt-repository "deb https://repo.sovrin.org/deb xenial master"
RUN add-apt-repository "deb https://repo.sovrin.org/sdk/deb xenial stable"

# Update apt
RUN apt-get update

# Install packages
RUN apt-get install -y libsodium18
RUN apt-get install -y python3-charm-crypto
RUN apt-get install -y libindy 
RUN apt-get install -y libindy-crypto

####################
##  Indy
####################

# Config apt

# Update apt
RUN apt-get update

# Install packages
RUN apt-get install -y indy-node
```

**Comment by vimmerru** [comment]
For current moment Indy provides 2 different CLI tools:

1. The old one python based CLI with code in indy-node repo. It will be deprecated soon.
2. The new one libindy based in indy-sdk repo. This CLI tool is in active development and will be released soon. 

You are reading documentation for new CLI, but executes the old one.
