### ISSUE TITLE
E: Unable to locate package indy-cli

### ISSUE THREAD

**Issue by dwjohnston** [hyperledger/indy-sdk#485]
Following [the instructions here:](https://github.com/hyperledger/indy-sdk/blob/master/cli/README.md#binaries)

```
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 68DB5E88
sudo add-apt-repository "deb https://repo.sovrin.org/sdk/deb xenial stable"
sudo apt-get update
sudo apt-get install -y indy-cli
```

yeilds: 

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package indy-cli
```

Can somone please advise?

**Comment by vimmerru** [comment]
Hi,

Instruction says ```change stable to master or rc if needed```. For current moment we don't have CLI in stable and rc repos as there was no CLI release. So you can use only  master repo now:

```
sudo add-apt-repository "deb https://repo.sovrin.org/sdk/deb xenial master"
```

Not sure that we need change instruction as release is planned soon.
