### ISSUE TITLE
docker setup experience

### ISSUE THREAD

**Issue by kdenhartog** [hyperledger/indy-sdk#545]
when walking through the getting started guide using docker, the setup is somewhat difficult. I've had to make changes to the docker-compose.yaml (IP-pools) as well as I can't identify why there's about 20 docker images, and what each one does. Is there a way that we could build a docker image and commit it to the docker repository, helping to streamline the getting started process. Additional steps should be added to the instruction guides to indicate that cargo build should be run in indy-sdk and indy-crypto to get tests passing.

**Comment by vimmerru** [comment]
It looks strange for me. The setup is just one command on ubuntu and windows. Just

docker-compose up

You don't need to change any ips as iPython and indy-pool will be executed in network that docker-compose creates. I suggest to contact offline and check it together. Also the best way to handle is create the ticket in Jira,.

**Comment by kdenhartog** [comment]
Sounds good, I'll move this over to jira to continue this.
