### ISSUE TITLE
cargo test failure problem

### ISSUE THREAD

**Issue by WandyLau** [hyperledger/indy-sdk#561]
When I tried to issue: cargo test. I got this error:

**"Unexpected SQLite error: disk I/O error"**

I have installed libsqlite-dev. 
Is there any package I missed? Or something else?

**Comment by lovesh** [comment]
Try RUST_TEST_THREADS=1 cargo test. Sometimes multiple threads running the test cause problems.

**Comment by vimmerru** [comment]
Documentation says about RUST_TEST_THREADS=1. So i believe we can close this issue.

**Comment by WandyLau** [comment]
Yes, this set reduce some errors, but not all of them. But I think more investigations will be needed.

**Comment by lovesh** [comment]
@WandyLau Which tests have errors? Can you please paste a stacktrace?

**Comment by WandyLau** [comment]
This error comes from:  cargo test in libindy/

failures:

---- services::pool::tests::catchup_handler_start_catchup_works stdout ----
	thread 'services::pool::tests::catchup_handler_start_catchup_works' panicked at 'called `Result::unwrap()` on a

---- services::pool::tests::pool_service::pool_service_close_works stdout ----
	thread 'services::pool::tests::pool_service::pool_service_close_works' panicked at 'assertion failed: `(left ==
  left: `1`,
 right: `2`', src/services/pool/mod.rs:737:13

---- services::pool::tests::pool_service::pool_service_refresh_works stdout ----
	thread 'services::pool::tests::pool_service::pool_service_refresh_works' panicked at 'assertion failed: `(left 
  left: `1`,
 right: `2`', src/services/pool/mod.rs:759:13

---- services::pool::tests::pool_worker_connect_to_known_nodes_works stdout ----
	thread 'services::pool::tests::pool_worker_connect_to_known_nodes_works' panicked at 'called `Result::unwrap()`

---- services::pool::tests::remote_node_connect_works_and_can_ping_pong stdout ----
	thread 'services::pool::tests::remote_node_connect_works_and_can_ping_pong' panicked at 'join: Any', /checkout/

**Comment by lovesh** [comment]
@WandyLau Can you please paste the stacktrace, so use the flag `RUST_BACKTRACE=full RUST_TEST_THREADS=1 cargo test`

**Comment by vimmerru** [comment]
- We never saw this issues for a few month
- We don't support s390 for current moment
- We don't have answer from requested for few month

I suggest to close this for now. @WandyLau I suggest to re-check on the latest stable or master and if problem is still here re-open with logs from

```
RUST_LOG=trace RUST_BACKTRACE=full RUST_TEST_THREADS=1 cargo test
```
