### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by WandyLau** [hyperledger/indy-sdk#562]
When I run cargo test: I got this error. 
Any clue?

**services::wallet::tests::wallet_service_get_pool_name_works stdout ----
	thread 'services::wallet::tests::wallet_service_get_pool_name_works' panicked at 'called `Result::unwrap()` on an `Err` value: CommonError(IOError(Error { repr: Os { code: 2, message: "No such file or directory" } }))', /checkout/src/libcore/result.rs:916:5**

**services::wallet::tests::wallet_service_set_get_not_expired_works_for_expired stdout ----
	thread 'services::wallet::tests::wallet_service_set_get_not_expired_works_for_expired' panicked at 'called `Result::unwrap()` on an `Err` value: CommonError(InvalidState("Unexpected SQLite error: unable to open database file"))', /checkout/src/libcore/result.rs:916:5**

**Comment by lovesh** [comment]
Try `RUST_TEST_THREADS=1 cargo test`. Sometimes multiple threads running the test cause problems.

**Comment by vimmerru** [comment]
RUST_TEST_THREADS=1 is present in docs. So i suggest to close this issue.
