### ISSUE TITLE
CLI: many commands missing compared to indy-node CLI

### ISSUE THREAD

**Issue by lodo1995** [hyperledger/indy-sdk#663]
According to the [indy-node readme](https://github.com/hyperledger/indy-node/#dependent-projects), the indy-sdk cli should replace the indy-node cli.

But, looking at [the source of the former](https://github.com/hyperledger/indy-node/blob/stable/indy_client/cli/command.py#L18), [the source of the latter](https://github.com/hyperledger/indy-sdk/blob/master/cli/src/main.rs#L55) and [the design document of the latter](https://github.com/hyperledger/indy-sdk/blob/master/doc/cli-design.md#commands), it appears that the indy-sdk cli is still missing many functions.

I found [a jira issue about the overall switch between the two clis](https://jira.hyperledger.org/projects/IS/issues/IS-380?filter=allopenissues), but I didn't manage to understand whether the missing commands will be implemented and, if so, whether they will be available soon or require some more time.

**Comment by dbluhm** [comment]
I noticed you were able to talk with @dhh1128 about this on RocketChat. Is there anything you can add here to clarify what seems to be missing?

**Comment by lodo1995** [comment]
According to the documentation in indy-node, the CLI implemented there has commands to perform the following actions, which are currently missing from the CLI in this repository:

- load a JSON file containing a connection request (`load <file>`)
- show a connection / connection request (`show connection <name>`)
- accept a connection request (`accept request from <name>`)
- check secure agent-to-agent communication channel (`ping <name>`)
- show a claim from the wallet or available from a remote agent (`show claim <name>`)
- obtain a claim from a remote agent (`request claim <name>`)
- show a proof request (`show proof request <name>`)
- send a proof to a remote agent (`send proof <name> to <name>`)

Most of these commands require the implementation of agent-to-agent communication, which is implemented in indy-node/indy_client (reusing some code from indy-plenum), but not in libindy.

**Comment by burdettadam** [comment]
We are using Jira to track issues now, please use this [Jira IS-995 ticket](https://jira.hyperledger.org/browse/IS-995) for any further discussion.
