### ISSUE TITLE
Running indy-pool.dockerfile fails in Plenum Python package

### ISSUE THREAD

**Issue by PJUllrich** [hyperledger/indy-sdk#698]
I have been creating Docker containers of the indy-pool with the provided [indy-pool.dockerfile](https://github.com/hyperledger/indy-sdk/blob/d3e1e4a161ba44caef9ca87ac1f69aa2eb7c8c18/ci/indy-pool.dockerfile) for over 2 months now. This morning it simply stopped working with the following error message:

```
Step 21/23 : RUN generate_indy_pool_transactions --nodes 4 --clients 5 --nodeNum 1 2 3 4 --ips="$pool_ip,$pool_ip,$pool_ip,$pool_ip"
 ---> Running in 77a61ead17ea
Traceback (most recent call last):
  File "/usr/local/bin/generate_indy_pool_transactions", line 19, in <module>
    getTxnOrderedFields(), ConfigHelper, NodeConfigHelper)
  File "/usr/local/lib/python3.5/dist-packages/plenum/common/test_network_setup.py", line 207, in bootstrapTestNodes
    steward_defs, node_defs = cls.gen_defs(args.ips, args.nodes, startingPort)
  File "/usr/local/lib/python3.5/dist-packages/plenum/common/test_network_setup.py", line 291, in gen_defs
    d.verkey = s_signer.verkey
  File "/usr/local/lib/python3.5/dist-packages/plenum/common/signer_did.py", line 54, in verkey
    return self.abbr_prfx + self._verkey
TypeError: Can't convert 'bytes' object to str implicitly
ERROR: Service 'pool' failed to build: The command '/bin/sh -c generate_indy_pool_transactions --nodes 4 --clients 5 --nodeNum 1 2 3 4 --ips="$pool_ip,$pool_ip,$pool_ip,$pool_ip"' returned a non-zero code: 1
```

This seems rather unusual to me since all indy-package versions are specified within the dockerfile (e.g. `ARG indy_plenum_ver=1.2.237`). Any thoughts on why the provided dockerfile is failing on me out of a sudden?

**Comment by kdenhartog** [comment]
this is an issue that appears due to the base58 version. It was recently updated and we chose to freeze the version we we're using and will update later. For now, if you run `sudo pip install base58==0.2.5 ` then you the problem should be resolved.

**Comment by PJUllrich** [comment]
So although I pinned (or froze) every version of every possible indy package (e.g. libindy, indy-plenum, anoncreds, etc. as specified in the indy-pool.dockerfile), still the latest versions of python packages are pulled? Shouldn't those be pinned as well within the ubuntu packages of e.g. indy-plenum?

**Comment by vimmerru** [comment]
As i know team that supports Indy Node already solved this.

**Comment by PJUllrich** [comment]
@vimmerru can you link to an Issue or file where they fix this? I'm having another issue because of this as well and am blocked until this is resolved.

**Comment by PJUllrich** [comment]
Thank you. We fixed this by pinning the `base58` package ourselves by pinning the `base58` package in the `apt-get update` command.
Note the added `python3-base58=0.2.4 \` command.
```
RUN apt-get update -y && apt-get install -y \
        indy-plenum=${indy_plenum_ver} \
        indy-anoncreds=${indy_anoncreds_ver} \
        indy-node=${indy_node_ver} \
        python3-indy-crypto=${python3_indy_crypto_ver} \
        libindy-crypto=${indy_crypto_ver} \
        python3-base58=0.2.4 \
        vim
```
