### ISSUE TITLE
[Feature request] Filesystem paths need to be configurable

### ISSUE THREAD

**Issue by lodo1995** [hyperledger/indy-sdk#702]
Currently the paths where configurations and wallets are searched for and saved to are fixed in `EnvironmentUtils::indy_home_path` and similar functions.

It would be better to have the following system to set the indy home path:

1. An API (e.g. `indy_set_home_path(const char*)`); if this API has not been called yet when the path is needed, then
2. An environment variable (e.g. `INDY_HOME_PATH`); if this variable is not set then
3. A default system-specific path (as implemented now).

It would be even better to have the above system available at finer granularity, so that `EnvironmentUtils::<whatever>_home_path` (where `<whatever>` is currently either `wallet` or `pool`) can be controlled in the following ways:

1. An API (e.g. `indy_set_<whatever>_path(const char*)`); if this API has not been called yet when the path is needed, then
2. An environment variable (e.g. `INDY_<WHATEVER>_PATH`); if this variable is not set then
3. The current default `<EnvironmentUtils::indy_home_path>/<whatever>`, where `EnvironmentUtils::indy_home_path` can be controlled as explained above.

If this is to be implemented, the ability to set the temporary directory in the same way as explained above for the home directory would make the feature more complete, but is arguably less useful in practical scenarios.

**Comment by vimmerru** [comment]
@lodo1995 Can we move discussion to Hyperledger Jira? You can find the link in main Readme.

**Comment by lodo1995** [comment]
@vimmerru moved to Jira as [IS-700](https://jira.hyperledger.org/browse/IS-700)
