### ISSUE TITLE
ci/indy-pool.dockerfile doesn't run on Raspberry Pi

### ISSUE THREAD

**Issue by saholman** [hyperledger/indy-sdk#756]
The dependencies installed in `ci/indy-pool.dockerfile` don't work on raspberry pi. Is there a version of this file that pulls and compiles directly from the repositories rather than using `apt-get` to install them?

**Comment by saholman** [comment]
The error: ```
E: Unable to locate package indy-plenum
E: Unable to locate package indy-anoncreds
E: Unable to locate package indy-node
E: Unable to locate package python3-indy-crypto
E: Unable to locate package libindy-crypto
The command '/bin/sh -c apt-get update -y && apt-get install -y         indy-plenum=${indy_plenum_ver}         indy-anoncreds=${indy_anoncreds_ver}         indy-node=${indy_node_ver}         python3-indy-crypto=${python3_indy_crypto_ver}         libindy-crypto=${indy_crypto_ver}         vim' returned a non-zero code: 100

```

**Comment by vimmerru** [comment]
Indy Node supports x86 only and support of something different look like very non-trivial task. Raspberry Pi doesn't look like appropriate device for hosting Indy Node at all. 

I suggest to just close this. @saholman If you have real use case important for Indy community you can re-open this or create an issue in indy-node repo.

**Comment by saholman** [comment]
@vimmerru I guess I was hoping it was a more trivial task, it was really only for testing.  It would make a little more sense for the indy-sdk to have an ARM build so that we could run an agent on it, but its not a priority right now.  Thanks!

**Comment by vimmerru** [comment]
Indy SDK (libindy) can be build for ARM and there is a PR with Android build instructions, but Indy Node isn't intended to be executed on such platforms.
