### ISSUE TITLE
Can not run the source code of tutorials "Write a DID and Query Its Verkey"

### ISSUE THREAD

**Issue by nbxtruong** [hyperledger/indy-sdk#762]
I do this [tutorial](https://github.com/hyperledger/indy-sdk/blob/master/doc/how-tos/write-did-and-query-verkey/java/README.md). I run "mvn clean install" It show "Build Success" on terminal. I already have libindy.so file in ./lib/

But, When I click button "Run App" on Eclipse IDE, It show this [error](https://imgur.com/pTtosrV).

And this is my pom.xml file:

<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<groupId>org.hyperledger.indy-sdk-java</groupId>
	<artifactId>indy-sdk-java-sample</artifactId>
	<packaging>jar</packaging>
	<version>0.0.1</version>
	<name>indy-sdk-java</name>
	<description>This is the sample of usage java wrapper for Hyperledger Indy SDK.
	</description>
	<licenses>
		<license>
			<name>MIT/Apache-2.0</name>
			<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
			<distribution>repo</distribution>
		</license>
	</licenses>

	<scm>
		<url>https://github.com/hyperledger/indy-sdk</url>
		<connection>scm:git:git://github.com/hyperledger/indy-sdk.git</connection>
		<developerConnection>scm:git:git@github.com:hyperledger/indy-sdk.git</developerConnection>
	</scm>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<github.global.server>github</github.global.server>
	</properties>

	<repositories>
		<repository>
			<id>evernym</id>
			<url>https://repo.evernym.com/artifactory/libindy-maven-local</url>
		</repository>
	</repositories>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.3</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
				<version>2.4</version>
				<executions>
					<execution>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.18.1</version>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>2.10</version>
				<executions>
					<execution>
						<id>execution</id>
						<phase>package</phase>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<includeScope>runtime</includeScope>
				</configuration>
			</plugin>

		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.5</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.5</version>
		</dependency>
		<dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
			<version>20160810</version>
		</dependency>
		<dependency>
			<groupId>org.hyperledger</groupId>
			<artifactId>indy</artifactId>
			<version>1.4.0</version>
		</dependency>
	</dependencies>
</project>

Help me, I run on Ubuntu 16.04, this is the first time I work with maven.

Thank you.

**Comment by vsudip** [comment]
Can you paste your error here ?

**Comment by burdettadam** [comment]
We are using Jira to track issues now, please use this [Jira IS-993 ticket](https://jira.hyperledger.org/browse/IS-993) for any further discussion.
