### ISSUE TITLE
Can't compile libindy on Mac machine - zmq-sys v0.8.2 problem

### ISSUE THREAD

**Issue by nveskovic** [hyperledger/indy-sdk#778]
Console log is showing this

```
error: failed to run custom build command for `zmq-sys v0.8.2`
```

**Comment by nveskovic** [comment]
just add
`brew install zeromq`
to mac-os requirements

**Comment by vimmerru** [comment]
@nveskovic Could you send PR with updated instruction?

**Comment by nveskovic** [comment]
sure
#820 created so I'll close this issue
