### ISSUE TITLE
Getting Started - Create wallet error

### ISSUE THREAD

**Issue by MaxenceAdnot** [hyperledger/indy-sdk#817]
Hi,

I tried the getting started code with the docker-compose provided and I encounter an error when trying to create the Steward wallet:

`IndyError                                 Traceback (most recent call last)
<ipython-input-4-55f4877086b1> in run()
     25         await wallet.create_wallet(pool_name, steward_wallet_name, None, None,
---> 26                                    None)
     27     except IndyError as ex:

/usr/local/lib/python3.5/dist-packages/indy/wallet.py in create_wallet(pool_name, name, xtype, config, credentials)
     51                   c_credentials,
---> 52                   create_wallet.cb)
     53 

/usr/lib/python3.5/asyncio/futures.py in __iter__(self)
    362         assert self.done(), "yield from wasn't used with future"
--> 363         return self.result()  # May raise too.
    364 

/usr/lib/python3.5/asyncio/futures.py in result(self)
    273         if self._exception is not None:
--> 274             raise self._exception
    275         return self._result

IndyError: ErrorCode.CommonInvalidParam6`

Do you have any idea of what is causing this ?

**Comment by vimmerru** [comment]
We will check this. What branch do you use currently?

**Comment by vimmerru** [comment]
The latest wallet changes merged to master broken GSG. Change is a quite small. Now credentials param of walelt.create and wallet.open is mandatory as wallet will be always encrypted.

**Comment by zhigunenko-dsr** [comment]
Hello @MaxenceAdnot 
Your problem has been fixed successfully. So you can update your master branch and continue to work
