### ISSUE TITLE
indy_create_and_store_credential_def: `support_revocation` is documented as optional but is actually mandatory

### ISSUE THREAD

**Issue by lodo1995** [hyperledger/indy-sdk#829]
From the documentation in [`api/anoncreds.rs`](https://github.com/hyperledger/indy-sdk/blob/master/libindy/src/api/anoncreds.rs):

    /// config_json: type-specific configuration of credential definition as json:
    /// - 'CL':
    ///   - support_revocation: whether to request non-revocation credential (optional, default false)

But if config_json is left empty, as the documentation suggests, the following error pops up:

    Invalid structure: Cannot deserialize CredentialDefinitionConfig: InvalidStructure("missing field `support_revocation` at line 1 column 2")

This is due to the fact that in [`domain/anoncreds/credential_definition.rs`](https://github.com/hyperledger/indy-sdk/blob/master/libindy/src/domain/anoncreds/credential_definition.rs) `CredentialDefinitionConfig::support_revocation` has type `bool` instead of `Option<bool>`.

**Comment by jcace** [comment]
Also, this line in the comment looks like a mistake to me. Seems like it was mistakenly copy-pasted from the section above:
> /// - 'CL':
It's in the documentation for the wrappers too. This was confusing & the line should be removed.

**Comment by zhigunenko-dsr** [comment]
@lodo1995 
We fixed parameter as optional in current master branch
Please let us know if problem wouldn't be resolved

**Comment by vimmerru** [comment]
@lodo1995 problem was solved and i am closing the ticket. You can re-open if you still experience this problem.
