### ISSUE TITLE
Information about not installing too recent libsodium releases can be removed

### ISSUE THREAD

**Issue by lodo1995** [hyperledger/indy-sdk#841]
The limitation of libsodium <= 1.0.14 does not hold any longer now that sodiumoxide dependency has been updated from 0.0.14 to 0.0.16. It should be removed or at least upgraded to libsodium <= 1.0.16.

**Comment by vimmerru** [comment]
@lodo1995 Thansk! Could you send a PR?

**Comment by burdettadam** [comment]
We are using Jira to track issues now, please use this [Jira IS-992 ticket](https://jira.hyperledger.org/browse/IS-992) for any further discussion.
