### ISSUE TITLE
nonce in node getting started

### ISSUE THREAD

**Issue by AxelNennker** [hyperledger/indy-sdk#897]
This line has a constant nonce
https://github.com/hyperledger/indy-sdk/blob/master/samples/nodejs/gettingStarted.js#L246

Two questions: 

1. What are the requirements on nonce? Is there a minimum length or an exact length requirement? Some Rust code suggests that some nonces have an exact length.
https://github.com/hyperledger/indy-sdk/blob/master/libindy/src/utils/crypto/chacha20poly1305_ietf/sodium.rs#L10

2. In the Rust code there is a method gen_nonce. Would it make sense to expose that to the API and wrappers? If not, would you consider providing random nonce generation examples in all the getting_started guides to help developers generate them and not copying the static ones to production code. 
```
var crypto = require('crypto'),
    biguint = require('biguint-format');
biguint.format(crypto.randomBytes(16), 'dec');
```
There is zero information about what nonce is in https://www.npmjs.com/package/indy-sdk.

**Comment by AxelNennker** [comment]
The gettingStarted.js is about proof requests and https://github.com/hyperledger/indy-sdk/blob/master/libindy/src/domain/anoncreds/proof_request.rs#L4 uses indy-crypto::cl::Nonce https://github.com/AxelNennker/indy-crypto/blob/master/libindy-crypto/src/cl/mod.rs#L27

I think the other languages should use a similar or the same getNonce.
pub const LARGE_NONCE: usize = 80;
https://github.com/AxelNennker/indy-crypto/blob/master/libindy-crypto/src/cl/constants.rs#L22
This is the number of bits of the resulting random BigNumber.
https://github.com/sfackler/rust-openssl/blob/master/openssl/src/bn.rs#L419

**Comment by burdettadam** [comment]
We are using Jira to track issues now, please use this [Jira IS-991 ticket](https://jira.hyperledger.org/browse/IS-991) for any further discussion.
