### ISSUE TITLE
setProtocolVersion is not a function

### ISSUE THREAD

**Issue by phillipgibb** [hyperledger/indy-sdk#899]
OS: MAC OS X
Running getting started node.js sample:

`TypeError: indy.setProtocolVersion is not a function`

If I do not set the protocol function:

`Pool worker thread finished with error PoolIncompatibleProtocolVersion("Libindy PROTOCOL_VERSION is 1 but Pool Genesis Transactions are of version 1.4.Call indy_set_protocol_version(2) to set correct PROTOCOL_VERSION")`

**Comment by vimmerru** [comment]
You have 2 options:

1. Don't use the latest master of Indy Node (use latest stable)
2. Build node.js wrappepr manually from sources. We don't have CD pipeline and npm will be updated in about one week after 1.5 libindy release.

**Comment by phillipgibb** [comment]
Thanks, I have built from source and have gotten past this error.
