### ISSUE TITLE
Providing more info with Exceptions (Java SDK wrapper)

### ISSUE THREAD

**Issue by Qingbao** [hyperledger/indy-sdk#905]
Current Java SDK wrapper only returning general information when exception occurs, for example "org.hyperledger.indy.sdk.InvalidStructureException: A value being processed is not valid." when passing a JSON to Indy node which is not helpful to dig into it. Hope it can provide more information when such errors happened.

**Comment by AxelNennker** [comment]
Please issues on jira https://jira.hyperledger.org/browse/IS-511?jql=project%20%3D%20%22IS%22%20AND%20text%20~%20%22error%20message%22

**Comment by vimmerru** [comment]
For development purposes you can enable trace level logging. Set RUST_LOG=trace env variable for your process. Logs will be printed to stdout. In logs you will find cause.

We have https://jira.hyperledger.org/browse/IS-511 in our pipeline. So we plan to expose error messages with each error.
