### ISSUE TITLE
Migrate with how-tos

### ISSUE THREAD

**Issue by Qingbao** [hyperledger/indy-sdk#906]
Current how-tos seem based on 1.3.0 which are not working with 1.4.0, hope can provide more examples with 1.4.0. Or at least give some example JSONs in Libindy migration Guide.

**Comment by jovfer** [comment]
Unfortunately main Indy SDK team doesn't support/update how-tos. As result it's may be out-dated.
I can suggest you take a look on samples directory.

**Comment by vimmerru** [comment]
@jovfer I believe we support should them and integrate checking to our CI pipeline. There are corresponded tasks and help is wanted.

**Comment by kdenhartog** [comment]
I agree @vimmerru it would be good to support these. I think the code that runs with them could be system-tests that are ran by the indy-sdk CI/CD pipeline to make sure they are remaining up to date. One problem with this is that if the node side breaks them, there won't be a check for this, but I think we could easily solve this.

**Comment by burdettadam** [comment]
We are using Jira to track issues now, please use this [Jira IS-990 ticket](https://jira.hyperledger.org/browse/IS-990) for any further discussion.
