### ISSUE TITLE
Plans to support Predicate p_types other than GE

### ISSUE THREAD

**Issue by xtrycatchx** [hyperledger/indy-sdk#923]
This is more of a question and not really a bug/limitation. Is there a plan to support p_type's other than Greater-Than-Or-Equal-To in predicates? 
 ```json
{"attr_name": "age", "p_type": "OTHER_THAN_GE", "value": 18} 
```

Or are there other ways/tricks to switch attribute vs. value in a way that GE is also reversed, something like 
 ```json
{"value": 18, "p_type": "GE", "attr_name": "age" } 
```

**Comment by xtrycatchx** [comment]
I just learned about the roadmap which Evernym Indy-SDK Team includes this plan and can be found here : [https://wiki.hyperledger.org/projects/indy/roadmap](https://wiki.hyperledger.org/projects/indy/roadmap)

May i know where to find the list of these Additional Predicates in the future?

**Comment by jovfer** [comment]
@xtrycatchx Current anoncreds algorithm allows to operate with ordering predicates. So in the future `<`, `<=` and `>` will be added.
@esplinr @vimmerru I think we should update our roadmap and explain that we just plan to support all ordering predicates, not string predicate `like` or something similar.

**Comment by xtrycatchx** [comment]
Thank you @jovfer and to the Indy SDK team. I will patiently wait for the updated sdk in the future :)
