### ISSUE TITLE
 fatal error errors occurs when running Java Samples

### ISSUE THREAD

**Issue by pradeeppadmarajaiah** [hyperledger/indy-sdk#931]

**Comment by pradeeppadmarajaiah** [comment]
Changed the node ip from 0.0.0.0 to 127.0.0.1.Able to run successfully with the fresh setup.

**Comment by pradeeppadmarajaiah** [comment]
@vsudip , Please remove the container and restart it. It tested in ubuntu VM. Make sure firewall is opened for all the required port. Once u start, try connecting via telnet

**Comment by vsudip** [comment]
Thanks it worked!
