### ISSUE TITLE
What to specify for EVERNYM_REPO_KEY in iOS build sh file

### ISSUE THREAD

**Issue by animeshd** [hyperledger/indy-sdk#942]
Hello,

I am trying to get libindy for iOS, so I am following https://github.com/hyperledger/indy-sdk/blob/master/wrappers/ios/README.md.

Step 6 says

> Edit script build-libindy-core-ios.sh: set the following variables to fit your environment:
> 
> export OPENSSL_DIR=/usr/local/Cellar/openssl/1.0.2k
> export EVERNYM_REPO_KEY=~/Documents/EvernymRepo
> export LIBINDY_POD_VERSION=0.0.1
> 
> EVERNYM_REPO_KEY - path to file with private key to be authorized on deb server

I don't know how to get that private key.

Please help.

Thank you,
Animesh

**Comment by vimmerru** [comment]
You don't need this step to get libindy for iOS. ```How to install``` section is enough

**Comment by vimmerru** [comment]
Also instruction seems outdated you don't need EVERNYM_REPO_KEY for now to run build script
