### ISSUE TITLE
Generate pool_transactions_genesis with DOCKERHOST for indy-pool

### ISSUE THREAD

**Issue by vitalrev** [hyperledger/indy-sdk#943]
Currently the docker file names `ci/indy-pool.dockerfile` generates indy pool transactions for IP's 127.0.0.1.
`generate_indy_pool_transactions --nodes 4 --clients 5 --nodeNum 1 2 3 4 --ips="127.0.0.1,127.0.0.1,127.0.0.1,127.0.0.1"`
This need to be changed to `DOCKERHOST` to generate correct `pool_transactions_genesis` files.

**Comment by vitalrev** [comment]
I have done this in a feature branch `feature/gentx_dockerhost`.
will push and make a pull request...

**Comment by vitalrev** [comment]
in my solution, i generate the `pool_transactions_genesis` not at the docker build but later at the docker run

**Comment by vitalrev** [comment]
see PR:  
https://github.com/hyperledger/indy-sdk/pull/946

**Comment by burdettadam** [comment]
We are using Jira to track issues now, please use this [Jira IS-1000 ticket](https://jira.hyperledger.org/browse/IS-1000) for any further discussion.
