### ISSUE TITLE
Android build.sh always uses arm dependencies when downloading pre-built

### ISSUE THREAD

**Issue by kchan628** [hyperledger/indy-sdk#948]
https://github.com/hyperledger/indy-sdk/blob/f58e5fde80b71f0dc99ee60ad86c8b3634f8e341/libindy/build_scripts/android/build.sh#L28

should be

```
    export OPENSSL_DIR=dependencies/openssl/openssl_${TARGET_ARCH}
    export SODIUM_DIR=dependencies/sodium/libsodium_${TARGET_ARCH}
    export LIBZMQ_DIR=dependencies/zmq/libzmq_${TARGET_ARCH}
```

**Comment by AxelNennker** [comment]
Seems to make sense. The error does not happen when the directories are cleared between building platforms which was previously the case, I think. @faisal00813

**Comment by faisal00813** [comment]
It should be openssl_${TARGET_ARCH}
@kchan628 Thank you for reporting.

**Comment by faisal00813** [comment]
PR for the fix https://github.com/hyperledger/indy-sdk/pull/950

**Comment by faisal00813** [comment]
Fix is in master now.
