### ISSUE TITLE
Issue about the document

### ISSUE THREAD

**Issue by dongwangdw** [hyperledger/indy-sdk#949]
The "get verinym" 6 point:
<img width="925" alt="screen shot 2018-07-13 at 11 54 48 am" src="https://user-images.githubusercontent.com/2303377/42671638-9a298b84-8693-11e8-8867-e4480a7ac2d5.png">

The faber_verykey should be the one included in the faber_did_info, right?
Because the document says, 'ask ledger for the verykey, but I can not get it. there is no verykey on the ledger right now. And the did now here is different from the one before for connecting with steward.  Or I missed something? Thanks in advance.

**Comment by WandyLau** [comment]
I still can not get it right now. because the faber key corresponding to this did is not on ledger right now. Why to get it from ledger? It is produced above.

**Comment by burdettadam** [comment]
We are using Jira to track issues now, please use this [Jira IS-999 ticket](https://jira.hyperledger.org/browse/IS-999) for any further discussion.
