### ISSUE TITLE
Got error when try to run the example for .Net Core

### ISSUE THREAD

**Issue by nbxtruong** [hyperledger/indy-sdk#960]
I am using:

1. Docker for setup Ledger work with 4 Node.
2. donet-sdk-2.1
3. package Hyperledger.Indy.Sdk --version 1.4.0 
4. Ubuntu 16.04

I have this error at step 10 when try to run [AnonCredsDemo.cs](https://github.com/hyperledger/indy-sdk/blob/master/samples/dotnet/Samples/AnonCredsDemo.cs). You can check [this screenshot](https://imgur.com/a/HCj7sfX)

@tmarkovski You have updated this example. Can you help me solve this problem?
Thank you

**Comment by tmarkovski** [comment]
@nbxtruong Which version of libindy do you have installed on your linux machine? The nuget package only works with libindy 1.4.
The samples are updated for 1.5 pending a PR, if you want to check that out.

https://github.com/hyperledger/indy-sdk/pull/953

**Comment by nbxtruong** [comment]
@tmarkovski I build the package by following [this post](https://github.com/hyperledger/indy-sdk/blob/master/doc/ubuntu-build.md). But, I got error. You can check [this screenshot](https://imgur.com/a/lLQJnUh)

Thank you

**Comment by tmarkovski** [comment]
This error is fixed by updating your rust compiler. You're probably using version 1.24. You need at least 1.26. Try running `rustc -V` to check. You can update to latest using `rustup update`

**Comment by nbxtruong** [comment]
Thank you @tmarkovski I compile success. But, How I use this package after it compiled. Do I need update [this file](https://github.com/hyperledger/indy-sdk/blob/master/samples/dotnet/Samples/Samples.csproj). I do not know how to run this example after this package compiled.

**Comment by tmarkovski** [comment]
@nbxtruong You should copy the .so file into your library folder, usually /usr/lib under Linux or /usr/local/lib on Mac.

**Comment by burdettadam** [comment]
We are using Jira to track issues now, please use this [Jira IS-998 ticket](https://jira.hyperledger.org/browse/IS-998) for any further discussion.
