### ISSUE TITLE
Indy Java Wrapper eats the exception when it can't load libindy via jna

### ISSUE THREAD

**Issue by kchan628** [hyperledger/indy-sdk#966]
https://github.com/hyperledger/indy-sdk/blob/master/wrappers/java/src/main/java/org/hyperledger/indy/sdk/LibIndy.java#L186

```
	static {

		try {

			init();
		} catch (UnsatisfiedLinkError ex) {

			// Library could not be found in standard OS locations.
			// Call init(File file) explicitly with absolute library path.
		}
	}
```

The exception is getting eaten and no log output or anything, this results in a null pointer exception later on but we don't know what the cause is. Ideally we should at least print this out using a logger or system.out.

**Comment by jovfer** [comment]
@kchan628 it's better to have this issue as ticket in https://jira.hyperledger.org/projects/IS/
Would you like to create it from yourself or I may do it?

**Comment by kchan628** [comment]
hi @jovfer you can create it. I just wanted to report the issue to hopefully smooth out usage for later. What I ended up doing is building from source and removing that catch to get at the exception to find the root cause of why it wasn't linking.
