### ISSUE TITLE
Get Indy errors 308 Pool Incompatible Protocol Version 

### ISSUE THREAD

**Issue by nbxtruong** [hyperledger/indy-sdk#977]
I create two docker. The first, It for indy_pool. The second, It for DAPP. When I create Pool ledger and steward. I got errors 308.

I set static IP & Port for both of It, and It can see each other. The DApp run on real machine, It worked fine. But, The DApp has this error when run on docker container.

Thank you.

**Comment by Alexis-Falquier** [comment]
I am having the same error when trying to do the 'Write a DID and Query Its Verkey' tutorial. at step 2 "open ledger and get handle" I get 

```
_indy_loop_callback: Function returned error 308
Error occurred: ErrorCode.PoolIncompatibleProtocolVersion
```

I followed all the steps to set up the environment so I do not know what could be causing this

**Comment by nbxtruong** [comment]
Thank you @Alexis-Falquier 
I add this line to the script: await pool.set_protocol_version(2)
and use: npm i indy-sdk@1.5.0-beta
indy-pool version 1.3

But I have this error: UnhandledPromiseRejectionWarning: TypeError: indy.set_protocol_version is not a function

**Comment by Alexis-Falquier** [comment]
I am not sure, it seems you might be using varying / older versions of the sdk / pool which would explain why it says it is not a function, as it might have been added in a newer verison. libindy i believe is in version 1.4 maybe try re-installing everything and building sdk from source to make sure you have the most up to date version of everything.

**Comment by benjsmi** [comment]
I'm seeing this same error.

**Comment by benjsmi** [comment]
Ah, in my case, npm was stuck on installing `indy-sdk` package at `0.2.5`.  If I were you, I'd check to see if `npm install --save indy-sdk@1.6.1-beta` does the trick. Or specify it in your package.json.  The strange thing is that npmjs.com does show that 1.6.1-beta is the latest release and the default release. Not sure why I ended up with 0.2.5.

**Comment by burdettadam** [comment]
We are using Jira to track issues now, please use this [Jira IS-987 ticket](https://jira.hyperledger.org/browse/IS-987) for any further discussion.
